/** Analyser of the `mission` kind: the same mission under the centralised, decentralised and hybrid architectures (chapter 3), with the trade-offs measured. */
import type { ReportSection } from '../ctl/analysis';
import { Metrics, f, sec, lines, bars, paths } from './report';
import { MissionSpec, MissionMetrics, Architecture, ARCHITECTURES, MissionSim, compareArchitectures } from './mission';

const ARCH_LABEL: Record<Architecture, string> = { centralized: 'centralised (coordinator plans, robots execute)', decentralized: 'decentralised (neighbours only)', hybrid: 'hybrid (coordinator plans, local laws, fallback)' };

export function analyseMission(d: MissionSpec, S: ReportSection[], M: Metrics): boolean {
  for (const ph of d.phases) { if (ph.kind === 'goto' && !ph.at) throw new Error(`phase ${ph.name}: zone=${ph.zone} is resolved on the station in Run on fleet; add at=x,y for the analysis`); if (ph.kind === 'allocate' && !ph.targets.length) throw new Error(`phase ${ph.name}: zones=… are resolved on the station in Run on fleet; add targets=x,y;… for the analysis`); }
  const archs: Architecture[] = d.architecture === 'compare' ? ARCHITECTURES : [d.architecture];
  const runs = compareArchitectures(d, archs); let ok = true;
  const faults = [...d.failures.map((x) => `${d.robots[x.robot].name} fails at ${x.at} s`), ...(d.coordinator.fail !== undefined ? [`coordinator down ${d.coordinator.fail}–${d.coordinator.recover ?? '∞'} s`] : [])];
  S.push(sec('Mission', 'info', [`${d.robots.length} robots, phases: ${d.phases.map((p) => `${p.name} (${p.kind}${p.kind === 'allocate' ? `, ${p.targets.length} targets` : p.kind === 'goto' ? ` → ${p.zone ?? p.at?.join(',')}` : ''})`).join(' → ')}`, `radio: range ${d.comm.radius} m, loss ${d.comm.drop}, period ${d.comm.period} s, lost after ${d.comm.lost} s; coordinator at (${d.coordinator.at}) with range ${Number.isFinite(d.coordinator.range) ? d.coordinator.range + ' m' : '∞'}`, `safety reflex in every architecture: barrier filter d_safe = ${d.safety.dSafe} m, γ = ${d.safety.gamma}, sensing ${d.safety.sense} m${d.obstacles.length ? `, ${d.obstacles.length} obstacles` : ''}`, faults.length ? `faults: ${faults.join('; ')}` : 'no faults']));
  const rows = runs.map(({ metrics: m }) => [ARCH_LABEL[m.architecture].split(' (')[0], m.completed ? `yes (${f(m.time, 0)} s)` : `NO — still in: ${m.lagging.join(', ')}`, m.phases.map((p) => (p.doneAt === null ? '—' : f(p.doneAt - p.startedAt, 0))).join(' / '), m.uplink + m.downlink, m.peer, f(m.stalledSeconds, 0), f(m.fallbackSeconds, 0), f(m.travelled, 1), f(m.minDistance, 2), `${m.tasksDone}/${m.tasksTotal}`]);
  const level = runs.every((r) => r.metrics.minDistance >= d.safety.dSafe - 5e-3) ? (runs.some((r) => !r.metrics.completed) ? 'warn' : 'ok') : 'error';
  S.push(sec('Architectures compared', level, [
    'centralised: one planner with global information (Hungarian slots and tasks, global phase decisions) — optimal assignments and the fewest peer messages, but a robot out of the coordinator\'s range or during its outage has no command and holds (stalled time)',
    'decentralised: every robot decides from its neighbours — no single point of failure and the traffic stays local, but slots are taken by index, CBBA and the phase gossip need agreement time and a partitioned group converges separately',
    'hybrid: global plans while the coordinator is reachable, local consensus between updates, automatic fallback to the decentralised laws after `lost` seconds of silence and resynchronisation when the coordinator returns',
  ], { table: { head: ['architecture', 'complete', 'phase durations, s', 'coordinator msgs ↑↓', 'peer msgs', 'stalled, s', 'fallback, s', 'travelled, m', 'min distance, m', 'tasks'], rows } }));
  S.push(sec('Formation error over time', 'info', ['the RMS deviation of pᵢ − δᵢ from its mean while a formation phase is active (0 otherwise)'], { plot: lines('formation error, m', runs.map((r) => ({ name: r.metrics.architecture, points: r.errHistory.filter((_, k) => k % Math.max(1, Math.floor(r.errHistory.length / 400)) === 0) })), 't, s', 'm') }));
  S.push(sec('Messages', 'info', [], { plot: bars('messages per architecture', runs.flatMap((r) => [{ label: `${r.metrics.architecture.slice(0, 3)} ↑↓`, value: r.metrics.uplink + r.metrics.downlink }, { label: `${r.metrics.architecture.slice(0, 3)} ⇄`, value: r.metrics.peer }])) }));
  for (const r of runs) { const m = r.metrics; ok = ok && m.minDistance >= d.safety.dSafe - 5e-3 && (d.architecture !== 'compare' ? m.completed : true); S.push(sec(`${ARCH_LABEL[m.architecture]} — log`, m.completed ? 'info' : 'warn', [`${m.completed ? 'mission complete' : 'mission NOT complete'} at ${f(m.time, 0)} s; robots alive ${m.robotsAlive}/${d.robots.length}; coordinator down ${f(m.coordinatorDown, 0)} s`, ...r.log.filter((l) => !/finished/.test(l)).slice(0, 25)], { plot: trajPlot(r.sim, d) })); M[`${m.architecture} time`] = m.completed ? Number(f(m.time, 0)) : 'incomplete'; M[`${m.architecture} msgs`] = m.uplink + m.downlink + m.peer; M[`${m.architecture} stalled s`] = Number(f(m.stalledSeconds, 0)); M[`${m.architecture} fallback s`] = Number(f(m.fallbackSeconds, 0)); M[`${m.architecture} min distance`] = Number(f(m.minDistance, 2)); }
  if (d.architecture === 'compare') { const done = runs.filter((r) => r.metrics.completed); if (done.length) { const best = done.reduce((b, r) => (r.metrics.time < b.metrics.time ? r : b)); M['fastest'] = best.metrics.architecture; } M['all complete'] = runs.every((r) => r.metrics.completed); }
  return ok;
}
function trajPlot(sim: MissionSim, d: MissionSpec) { const pts = sim.p; return paths('Final positions and targets', d.robots.map((r, i) => ({ name: r.name, points: [[d.robots[i].at[0], d.robots[i].at[1]], [pts[i][0], pts[i][1]]] as Array<[number, number]> })), { markers: [{ x: d.coordinator.at[0], y: d.coordinator.at[1], kind: 'station', label: 'coordinator' }, ...d.obstacles.map((o) => ({ x: o.at[0], y: o.at[1], kind: 'obstacle' as const, label: o.name })), ...d.phases.flatMap((p) => p.targets.map((t, j) => ({ x: t[0], y: t[1], kind: 'task' as const, label: p.targetNames[j] }))), ...d.phases.filter((p) => p.at).map((p) => ({ x: p.at![0], y: p.at![1], kind: 'goal' as const, label: p.name }))] }); }
export type { MissionMetrics };
