/** Analysers of the practicum kinds: consensus (ПР1), swarm (ПР2), allocation (ПР3), gridmapf (ПР4), coverage & estimation (ПР5), safety (ПР6), warehouse (homework). */
import type { ReportSection } from '../ctl/analysis';
import { Metrics, f, sec, lines, paths, grid, seriesOf, trajectories, networkView, mean } from './report';
import { Rng, Vec2, dist } from './rng';
import { Matrix, TOPOLOGIES, graphFromEdges, diskGraph, laplacianSpectrum, algebraicConnectivity, maxConsensusStep, degrees, edgeCount, isConnected, diameter, vertexConnectivity, robustness, metropolisWeights, randomGeometricGraph } from './graph';
import { runConsensus, disagreement, convergenceFactor, formationVelocity, formationError, formationOffsets, rendezvousVelocity, wmsrStep, consensusStep, eventTriggeredConsensus, cooperativeTransport } from './consensus';
import { simulate, CommModel } from './sim';
import { boidsStep, polarization, minPairDistance, vicsekOrder, psoOptimize, robotPsoSearch, gaussianSource, acoTsp, fireflyOptimize, greyWolfOptimize, beeColonyOptimize } from './swarm';
import { costMatrix, greedyAssignment, optimalAssignment, ssiAuction, totalLength, makespan, bruteForceRouting, runCbba, isConflictFree, totalScore, vickreyAuction, contractNetMessages } from './allocation';
import { loadMap, freeCells, prioritizedPlanning, cbs, firstConflict, sumOfCosts, makespanOf, executeAdg, executeNaive, spaceTimeAStar, Cell, Path } from './mapf';
import { gridPoints, gaussianDensity, voronoiLabels, massCentroids, coverageCost, lloydStep, limitedLloydStep, limitedCost, informationConsensus, naiveAverageConsensus, centralizedEstimate, covarianceIntersection, M2 } from './coverage';
import { runGroup, antipodal, goToGoal, minPairDistance as minDist } from './safety';
import { FleetSim, Warehouse } from './warehouse';
import { ConsensusDoc, SwarmDoc, AllocationDoc, GridMapfDoc, CoverageDoc, EstimationDoc, SafetyDoc, WarehouseDoc, GraphSpec } from './dsl';

// ---------------------------------------------------------------------------------------------------------------------
// consensus
// ---------------------------------------------------------------------------------------------------------------------
export function buildGraph(spec: GraphSpec, positions?: Vec2[]): Matrix {
  if (spec.type === 'edges') return graphFromEdges(spec.n, spec.edges);
  if (spec.type === 'disk') { if (!positions) throw new Error('a disk graph needs robot positions'); return diskGraph(positions, spec.radius); }
  return TOPOLOGIES[spec.type](spec.n);
}
export function consensusPositions(d: ConsensusDoc): Vec2[] { const rng = new Rng(d.seed); return d.robots.map((r) => r.at ?? [rng.uniform(0, d.box), rng.uniform(0, d.box)]); }
export function analyseConsensus(d: ConsensusDoc, S: ReportSection[], M: Metrics): boolean {
  const n = d.graph.n; const names = d.robots.map((r) => r.name); const pos = consensusPositions(d); const A = buildGraph(d.graph, pos); let ok = true;
  const lam = laplacianSpectrum(A); const lam2 = algebraicConnectivity(A); const emax = maxConsensusStep(A); const conn = isConnected(A);
  const gl = [`${n} robots, ${edgeCount(A)} links, degrees ${degrees(A).map((x) => f(x, 2)).join(' ')}, diameter ${conn ? diameter(A) : '∞'}${n <= 10 ? `, vertex connectivity ${vertexConnectivity(A)}` : ''}`, `Laplacian spectrum: ${lam.map((x) => f(x, 4)).join(', ')}`, `algebraic connectivity λ₂ = ${f(lam2, 4)} → the graph is ${conn ? 'connected (Fiedler: λ₂ > 0)' : 'NOT connected (λ₂ = 0): consensus converges only inside components'}`, `admissible discrete step: ε < 1/Δmax = ${f(emax, 4)}; optimal ε* = 2/(λ₂ + λₙ) = ${f(2 / (lam2 + lam[n - 1]), 4)}`];
  if (n <= 9) { const r = robustness(A); gl.push(`r-robustness = ${r} (W-MSR tolerates F = ${Math.floor((r - 1) / 2)} malicious neighbours)`); M['robustness'] = r; }
  S.push(sec('Communication graph', conn ? 'ok' : 'error', gl, { graph: networkView(A, names, d.graph.type === 'disk' || d.robots.every((r) => r.at) ? pos : undefined) }));
  M['robots'] = n; M['links'] = edgeCount(A); M['lambda2'] = Number(f(lam2, 4)); M['connected'] = conn; M['max step'] = Number(f(emax, 4)); if (!conn) ok = false;
  // discrete consensus
  const eps = d.eps ?? 0.9 * emax; const rng = new Rng(d.seed); const x0 = d.x0 ?? Array.from({ length: n }, () => Number(rng.uniform(0, 10).toFixed(2)));
  const cf = convergenceFactor(A, eps); const xs = runConsensus(x0, A, eps, d.steps); const avg = mean(x0); const dis = xs.map((x) => disagreement(x));
  const it1 = dis.findIndex((v) => v <= 0.01 * dis[0]); const cl: string[] = [`ε = ${f(eps, 4)}${d.eps === undefined ? ' (0.9/Δmax by default)' : ''}: convergence factor ρ = max|1 − ελᵢ| = ${f(cf.rho, 4)}${cf.rho < 1 ? `, ≈ ${cf.iterationsFor1pc} iterations for 1 % (measured: ${it1 < 0 ? `> ${d.steps}` : it1})` : ' ≥ 1 — the protocol does NOT converge'}`, `average of x(0) = ${f(avg, 4)} is preserved: mean after ${d.steps} steps = ${f(mean(xs[d.steps]), 4)}, disagreement ${f(dis[0], 4)} → ${f(dis[d.steps], 6)}`];
  if (eps >= emax) { cl.push(`⚠ ε ≥ 1/Δmax: P = I − εL loses the positive diagonal; the iteration may oscillate or diverge (task 2 of chapter 4)`); ok = ok && cf.rho < 1; }
  const first = Math.min(3, d.steps); S.push(sec('Discrete consensus x⁺ = x − εLx', cf.rho < 1 ? 'ok' : 'error', cl, { table: { head: ['k', ...names.map((nm) => `x(${nm})`), 'disagreement'], rows: Array.from({ length: first + 1 }, (_, k) => [k, ...xs[k].map((v) => f(v, 4)), f(dis[k], 4)]) }, plot: lines('States xᵢ(k)', names.map((nm, i) => seriesOf(nm, xs.map((x) => x[i]))), 'k', 'x') }));
  M['rho'] = Number(f(cf.rho, 4)); M['iterations to 1%'] = it1 < 0 ? `> ${d.steps}` : it1; M['epsilon'] = Number(f(eps, 4));
  if (d.continuous) { const h = 0.01; const xc = runConsensus(x0, A, h, Math.round(d.steps / h)); const tt = Math.log(100) / lam2; S.push(sec('Continuous protocol ẋ = −Lx (Euler, h = 0.01)', 'info', [`disagreement decays as e^{−λ₂t}: theoretical time to 1 % ≈ ln(100)/λ₂ = ${f(tt, 2)} s`], { plot: lines('Continuous consensus', names.map((nm, i) => seriesOf(nm, xc.filter((_, k) => k % 10 === 0).map((x) => x[i]), 0, 0.1)), 't, s', 'x') })); }
  if (d.compare.length) { const rows = d.compare.filter((t) => TOPOLOGIES[t]).map((t) => { const B = TOPOLOGIES[t](n); const l2 = algebraicConnectivity(B); const e = 0.9 * maxConsensusStep(B); const c = convergenceFactor(B, e); return [t, edgeCount(B), f(l2, 4), diameter(B), f(e, 3), f(c.rho, 4), c.iterationsFor1pc, n <= 9 ? robustness(B) : '—']; }); S.push(sec(`Topology comparison for n = ${n} (table 4.1)`, 'info', ['complete graph: fastest but n(n−1)/2 links; path / ring: λ₂ ~ 1/n²; star: λ₂ = 1 independent of n but vertex connectivity 1'], { table: { head: ['topology', 'links', 'λ₂', 'diameter', 'ε = 0.9/Δmax', 'ρ', 'iterations to 1 %', 'robustness'], rows } })); }
  if (d.formation) { const off = formationOffsets(d.formation.shape, n, d.formation.r); const comm = d.comm ? new CommModel(d.comm.radius, d.comm.drop, new Rng(d.seed + 7)) : undefined; const fails: Record<number, number[]> = {}; for (const fl of d.failures) (fails[Math.round(fl.at / d.formation.dt)] ??= []).push(fl.robot); const gain = d.formation.gain; const { hist } = simulate(pos, (_t, p, Ak) => formationVelocity(p, comm ? Ak : A, off, gain), d.formation.steps, { dt: d.formation.dt, comm, failures: fails, recordEvery: Math.max(1, Math.floor(d.formation.steps / 300)) }); const errs = hist.p.map((p) => formationError(p, off)); const e0 = errs[0], eN = errs[errs.length - 1]; const okF = eN < 0.01 * Math.max(e0, 1e-6) || eN < 1e-3; S.push(sec(`Formation "${d.formation.shape}" by offsets (§4.5.1)`, okF ? 'ok' : 'warn', [`ξᵢ = pᵢ − δᵢ reduces the formation to consensus: shape error ${f(e0, 4)} → ${f(eN, 5)} m after ${f(d.formation.steps * d.formation.dt, 1)} s (gain ${gain})`, `the centre of the formation is the mean of the initial ξ (not chosen in advance); links ${comm ? `${hist.edges[0]} → ${hist.edges[hist.edges.length - 1]} (disk graph, radius ${d.comm!.radius}, loss ${d.comm!.drop})` : `${edgeCount(A)} (${d.graph.type})${d.failures.length ? ` before the failures` : ''}`}`, ...(d.failures.length ? [`failures: ${d.failures.map((x) => `${names[x.robot]} at ${x.at} s`).join(', ')} — the survivors keep the shape with the remaining links`] : [])], { plot: paths('Formation trajectories', trajectories(hist.p, names), { markers: hist.p[hist.p.length - 1].map((p, i) => ({ x: p[0], y: p[1], label: names[i], kind: 'robot' as const })) }) })); S.push(sec('Formation error over time', 'info', [], { plot: lines('formation error, m', [seriesOf('error', errs, 0, hist.t[1] - hist.t[0])], 't, s', 'm') })); M['formation error'] = Number(f(eN, 5)); ok = ok && okF; }
  if (d.rendezvous) { const R = d.rendezvous.radius; const A0 = diskGraph(pos, R); const c0 = isConnected(A0); const { hist } = simulate(pos, (_t, p) => rendezvousVelocity(p, A0, R, d.rendezvous!.gain), d.rendezvous.steps, { dt: d.rendezvous.dt, vmax: d.rendezvous.vmax, recordEvery: Math.max(1, Math.floor(d.rendezvous.steps / 300)) }); let broken = 0; for (const P of hist.p) for (let i = 0; i < n; i++) for (let j = i + 1; j < n; j++) if (A0[i][j] && dist(P[i], P[j]) >= R) broken++; const last = hist.p[hist.p.length - 1]; const c: Vec2 = [mean(last.map((p) => p[0])), mean(last.map((p) => p[1]))]; const spread = Math.max(...last.map((p) => dist(p, c))); const plain = simulate(pos, (_t, p) => consensusStep(p, A0, 1).map((q, i) => [(q[0] - p[i][0]) * d.rendezvous!.gain, (q[1] - p[i][1]) * d.rendezvous!.gain] as Vec2), d.rendezvous.steps, { dt: d.rendezvous.dt, vmax: d.rendezvous.vmax, recordEvery: 50 }); let brokenPlain = 0; for (const P of plain.hist.p) for (let i = 0; i < n; i++) for (let j = i + 1; j < n; j++) if (A0[i][j] && dist(P[i], P[j]) >= R) { brokenPlain++; break; } S.push(sec('Rendezvous with connectivity maintenance (Ji & Egerstedt weights)', broken === 0 && c0 ? 'ok' : 'error', [`initial disk graph (R = ${R}): ${edgeCount(A0)} links, ${c0 ? 'connected' : 'NOT connected'}`, `weights w(d) = (2R − d)/(R − d)² over the initial links: ${broken === 0 ? 'no initial link was ever broken' : `${broken} link violations`}; final spread ${f(spread, 3)} m`, `plain consensus over the same links breaks a link in ${brokenPlain} recorded steps`], { plot: paths('Rendezvous', trajectories(hist.p, names)) })); M['links broken'] = broken; ok = ok && broken === 0; }
  if (d.wmsr) { const w = d.wmsr; const mal = w.malicious.length ? w.malicious : [n - 1]; let x = x0.slice(); const hist: number[][] = [x.slice()]; let y = x0.slice(); const normal = [...Array(n).keys()].filter((i) => !mal.includes(i)); const lo = Math.min(...normal.map((i) => x0[i])), hi = Math.max(...normal.map((i) => x0[i])); for (let k = 0; k < w.steps; k++) { const v = w.pattern === 'alternate' ? (k % 2 ? w.value : -w.value) : w.pattern === 'ramp' ? (w.value * k) / w.steps : w.value; for (const m of mal) { x[m] = v; y[m] = v; } x = wmsrStep(x, A, w.F, w.eps, mal); y = consensusStep(y, A, w.eps); hist.push(x.slice()); } const vals = normal.map((i) => x[i]); const range = Math.max(...vals) - Math.min(...vals); const inside = mean(vals) >= lo - 1e-9 && mean(vals) <= hi + 1e-9; const r = n <= 9 ? robustness(A) : NaN; const okW = range < 1e-2 && inside; S.push(sec(`W-MSR with F = ${w.F} against ${mal.map((m) => names[m]).join(', ')} (§16.8.3)`, okW ? 'ok' : 'warn', [`malicious value pattern "${w.pattern}" (±${w.value}); normal agents after ${w.steps} steps: spread ${f(range, 5)}, mean ${f(mean(vals), 4)} ${inside ? 'inside' : 'OUTSIDE'} the initial range [${f(lo, 2)}, ${f(hi, 2)}]`, `plain consensus is hijacked: mean of the normal agents ${f(mean(normal.map((i) => y[i])), 2)}`, Number.isNaN(r) ? 'graph too large for the robustness check' : `graph is ${r}-robust; W-MSR needs (2F+1) = ${2 * w.F + 1}-robustness → ${r >= 2 * w.F + 1 ? 'guaranteed' : 'NOT guaranteed (sparse chains and trees are defenceless)'}`], { plot: lines('W-MSR: normal agents', normal.map((i) => seriesOf(names[i], hist.map((h) => h[i]))), 'k', 'x') })); M['wmsr spread'] = Number(f(range, 5)); ok = ok && okW; }
  if (d.event) { const et = eventTriggeredConsensus(x0, A, eps, d.steps, d.event.sigma, d.event.abs); S.push(sec('Event-triggered consensus (§13.5.2)', 'info', [`broadcast only when |x̂ᵢ − xᵢ| > ${d.event.sigma}·|xᵢ| + ${d.event.abs}: ${et.broadcasts} messages instead of ${et.periodicMessages} periodic (${f((100 * et.broadcasts) / et.periodicMessages, 1)} %)`, `final disagreement ${f(disagreement(et.xs[d.steps]), 4)} (periodic: ${f(dis[d.steps], 6)}) — the residual is bounded by the threshold`], { plot: lines('Event-triggered states', names.map((nm, i) => seriesOf(nm, et.xs.map((x) => x[i]))), 'k', 'x') })); M['event messages'] = et.broadcasts; }
  if (d.transport) { const tr = cooperativeTransport(pos, d.transport.target, { m: d.transport.m, kp: d.transport.kp, kd: d.transport.kd }); S.push(sec('Cooperative transport with a PD law (§4.5.2)', 'info', [`m ẍₒ + k_d ẋₒ + k_p (xₒ − x_d) = 0 with m = ${d.transport.m}, k_p = ${d.transport.kp}, k_d = ${d.transport.kd}: ${tr.regime} regime${tr.regime === 'oscillatory' ? ` (ω = ${f(tr.omega, 3)} rad/s)` : ''}; k_d² ${tr.regime === 'critical' ? '=' : tr.regime === 'overdamped' ? '>' : '<'} 4 m k_p`, `settling to 2 %: ${Number.isNaN(tr.settlingTime) ? 'not within the horizon' : `${f(tr.settlingTime, 2)} s`}, overshoot ${f(100 * tr.overshoot, 1)} % (fragile loads want critical damping k_d = 2√(m k_p) = ${f(2 * Math.sqrt(d.transport.m * d.transport.kp), 3)})`], { plot: lines('Object distance to the target', [seriesOf('‖xₒ − x_d‖', tr.xo.map((p) => dist(p, d.transport!.target)), 0, tr.t[1] - tr.t[0])], 't, s', 'm') })); }
  return ok;
}

// ---------------------------------------------------------------------------------------------------------------------
// swarm
// ---------------------------------------------------------------------------------------------------------------------
export function analyseSwarm(d: SwarmDoc, S: ReportSection[], M: Metrics): boolean {
  const rng = new Rng(d.seed); let ok = true; const names = (i: number) => d.robotNames[i] ?? `r${i + 1}`;
  if (d.model === 'boids') {
    let p: Vec2[] = Array.from({ length: d.n }, () => [rng.uniform(0, d.box), rng.uniform(0, d.box)]); let v: Vec2[] = Array.from({ length: d.n }, () => [rng.normal(0, 0.1), rng.normal(0, 0.1)]); const pol = [polarization(v)]; const dmin = [minPairDistance(p)]; const hist: Vec2[][] = [p]; const every = Math.max(1, Math.floor(d.steps / 200));
    for (let k = 0; k < d.steps; k++) { ({ p, v } = boidsStep(p, v, d.dt, d.vmin, d.vmax, { rSep: d.rSep, rView: d.rView, wSep: d.wSep, wAli: d.wAli, wCoh: d.wCoh })); pol.push(polarization(v)); dmin.push(minPairDistance(p)); if (k % every === 0) hist.push(p); }
    const phi = pol[pol.length - 1]; const dm = Math.min(...dmin); const dEnd = dmin[dmin.length - 1]; ok = phi > 0.9 && dEnd > d.rSep / 2;
    S.push(sec('Reynolds flock (§5.3, ПР2 step 1)', ok ? 'ok' : 'warn', [`${d.n} robots, rules: separation (r < ${d.rSep}, w = ${d.wSep}), alignment (w = ${d.wAli}), cohesion (w = ${d.wCoh}) within r_view = ${d.rView}; speed kept in [${d.vmin}, ${d.vmax}]`, `polarization φ = ‖Σv‖/Σ‖v‖: ${f(pol[0], 3)} → ${f(phi, 3)} after ${d.steps} steps (${phi > 0.9 ? 'the flock is aligned' : 'not aligned yet'})`, `minimum pair distance ${f(dEnd, 3)} m in the final flock (${f(dm, 3)} m over the whole run, r_sep/2 = ${f(d.rSep / 2, 3)}); emergence: no robot knows the global heading`], { plot: lines('Order parameter', [seriesOf('φ', pol, 0, d.dt), seriesOf('min distance', dmin, 0, d.dt)], 't, s') })); S.push(sec('Trajectories', 'info', [], { plot: paths('Flock trajectories', trajectories(hist, [...Array(d.n).keys()].map(names)), { markers: p.map((q, i) => ({ x: q[0], y: q[1], kind: 'robot' as const, label: i < 3 ? names(i) : undefined })) }) })); M['polarization'] = Number(f(phi, 3)); M['min distance'] = Number(f(dEnd, 3));
  } else if (d.model === 'vicsek') {
    const rows = d.etas.map((eta) => { const o = vicsekOrder(d.n, d.box, d.radius, eta, d.steps, rng, d.speed); return { eta, o }; }); const lo = rows[0].o, hi = rows[rows.length - 1].o; ok = lo > hi;
    S.push(sec('Vicsek model: order–disorder phase transition (§1.1.4, §5.3, ПР2 step 2)', ok ? 'ok' : 'warn', [`${d.n} particles on a ${d.box}×${d.box} torus, interaction radius ${d.radius}, speed ${d.speed}, ${d.steps} steps (order averaged over the second half)`, `noise η = ${rows[0].eta}: φ = ${f(lo, 3)} (ordered flock); η = ${rows[rows.length - 1].eta}: φ = ${f(hi, 3)} (disorder) — the transition is the hallmark of a complex system`], { table: { head: ['η', 'order φ'], rows: rows.map((r) => [r.eta, f(r.o, 3)]) }, plot: lines('Phase transition', [{ name: 'φ(η)', points: rows.map((r) => [r.eta, r.o]), markers: true }], 'noise η', 'φ') })); M['order low noise'] = Number(f(lo, 3)); M['order high noise'] = Number(f(hi, 3));
  } else if (d.model === 'pso' && !d.robots) {
    const field = gaussianSource(d.source, d.sigma, 1, d.distractors); const x0: Vec2[] = Array.from({ length: d.n }, () => [rng.uniform(d.range[0], d.range[1]), rng.uniform(d.range[0], d.range[1])]); const r = psoOptimize(field, x0, d.steps, rng, d.k); const err = dist(r.best, d.source); ok = err < 0.05;
    S.push(sec('PSO with a ring (lbest) topology (§5.6, ПР2 step 3)', ok ? 'ok' : 'warn', [`${d.n} particles, ${d.steps} steps, w = 0.72, c₁ = c₂ = 1.49, neighbourhood ±${d.k}`, `best point (${f(r.best[0], 3)}, ${f(r.best[1], 3)}) with value ${f(r.value, 4)}; source at (${d.source[0]}, ${d.source[1]}) → error ${f(err, 4)}${d.distractors.length ? ` with ${d.distractors.length} distractor maxima` : ''}`, 'the best value never decreases (the swarm remembers)'], { plot: lines('Best value found', [seriesOf('max pbest', r.history)], 'iteration', 'value') })); M['source error'] = Number(f(err, 4));
  } else if (d.model === 'pso') {
    const field = gaussianSource(d.source, d.sigma, 1, d.distractors); const x0: Vec2[] = Array.from({ length: d.n }, () => [rng.uniform(d.range[0], d.range[1]), rng.uniform(d.range[0], d.range[1])]); const r = robotPsoSearch(field, x0, d.steps, rng, { vmax: d.vmax, dMin: d.dMin, k: d.k, noiseStd: d.noise, forget: d.forget }); const last = r.traj[r.traj.length - 1]; const c: Vec2 = [mean(last.map((q) => q[0])), mean(last.map((q) => q[1]))]; const err = dist(c, d.source); let maxStep = 0; for (let k = 1; k < r.traj.length; k++) for (let i = 0; i < d.n; i++) maxStep = Math.max(maxStep, dist(r.traj[k][i], r.traj[k - 1][i])); const dm = Math.min(...r.traj.map((P) => minPairDistance(P))); ok = err < 0.3;
    S.push(sec('Swarm source seeking by robots (ПР2 step 4)', ok ? 'ok' : 'warn', [`${d.n} robots, step ≤ ${d.vmax} m (measured max ${f(maxStep, 4)}), repulsion below ${d.dMin} m (min distance ${f(dm, 3)}), measurement noise σ = ${d.noise}${d.forget ? `, forgetting ${d.forget}` : ''}`, `swarm centre after ${d.steps} steps: (${f(c[0], 3)}, ${f(c[1], 3)}), source (${d.source[0]}, ${d.source[1]}) → error ${f(err, 3)} m; best measured point (${f(r.bestPoint[0], 2)}, ${f(r.bestPoint[1], 2)})`], { plot: paths('Robot trajectories', trajectories(r.traj, [...Array(d.n).keys()].map(names)), { markers: [{ x: d.source[0], y: d.source[1], kind: 'source', label: 'source' }, ...d.distractors.map((dd) => ({ x: dd[0][0], y: dd[0][1], kind: 'obstacle' as const, label: 'distractor' }))] }) })); S.push(sec('True field value at the best record', 'info', [], { plot: lines('field(pbest*)', [seriesOf('value', r.best)], 'step', 'value') })); M['source error'] = Number(f(err, 3)); M['min distance'] = Number(f(dm, 3));
  } else if (d.model === 'aco') {
    const pts: Vec2[] = d.points.length ? d.points : new Rng(d.seed).shuffle(Array.from({ length: d.n }, (_, i) => [Math.cos((2 * Math.PI * i) / d.n), Math.sin((2 * Math.PI * i) / d.n)] as Vec2)); const r = acoTsp(pts, rng, { ants: d.ants, iterations: d.iterations, alpha: d.alpha, beta: d.beta, rho: d.rho }); ok = r.length <= r.greedyLength + 1e-9;
    S.push(sec('Ant colony optimisation of a closed route (§5.5)', ok ? 'ok' : 'warn', [`${pts.length} waypoints, ${d.ants} ants × ${d.iterations} iterations, α = ${d.alpha}, β = ${d.beta}, ρ = ${d.rho}`, `best tour length ${f(r.length, 4)} (nearest-neighbour heuristic: ${f(r.greedyLength, 4)}); tour: ${r.tour.map((i) => i + 1).join(' → ')}`], { plot: paths('Best tour', [{ name: 'tour', points: [...r.tour, r.tour[0]].map((i) => [pts[i][0], pts[i][1]] as [number, number]) }], { markers: pts.map((p, i) => ({ x: p[0], y: p[1], kind: 'task' as const, label: String(i + 1) })) }) })); S.push(sec('Convergence', 'info', [], { plot: lines('best length per iteration', [seriesOf('length', r.history, 1)], 'iteration', 'length') })); M['tour length'] = Number(f(r.length, 4)); M['greedy length'] = Number(f(r.greedyLength, 4));
  } else {
    const field = gaussianSource(d.source, d.sigma, 1, d.distractors); const x0: Vec2[] = Array.from({ length: d.n }, () => [rng.uniform(d.range[0], d.range[1]), rng.uniform(d.range[0], d.range[1])]); const r = d.model === 'firefly' ? fireflyOptimize(field, x0, d.steps, rng) : d.model === 'gwo' ? greyWolfOptimize(field, x0, d.steps, rng) : beeColonyOptimize(field, x0, d.steps, rng); const err = dist(r.best, d.source); ok = err < 0.1;
    S.push(sec(`${d.model === 'firefly' ? 'Firefly algorithm (§5.8)' : d.model === 'gwo' ? 'Grey wolf optimiser (§5.9)' : 'Bee colony (§5.7)'}`, ok ? 'ok' : 'warn', [`${d.n} agents, ${d.steps} iterations; best (${f(r.best[0], 3)}, ${f(r.best[1], 3)}) value ${f(r.value, 4)}, error to the source ${f(err, 4)}`], { plot: lines('Best value', [seriesOf('best', r.history)], 'iteration', 'value') })); M['source error'] = Number(f(err, 4));
  }
  return ok;
}

// ---------------------------------------------------------------------------------------------------------------------
// allocation
// ---------------------------------------------------------------------------------------------------------------------
export function allocationInstance(d: AllocationDoc): { robots: Vec2[]; tasks: Vec2[]; rewards: number[]; values: number[]; rNames: string[]; tNames: string[] } {
  if (d.random) { const rng = new Rng(d.random.seed); const robots: Vec2[] = Array.from({ length: d.random.robots }, () => [rng.uniform(0, d.random!.area), rng.uniform(0, d.random!.area)]); const tasks: Vec2[] = Array.from({ length: d.random.tasks }, () => [rng.uniform(0, d.random!.area), rng.uniform(0, d.random!.area)]); const rewards = tasks.map(() => rng.uniform(5, 15)); return { robots, tasks, rewards, values: rewards.map((r) => r * 2), rNames: robots.map((_, i) => `r${i + 1}`), tNames: tasks.map((_, i) => `t${i + 1}`) }; }
  return { robots: d.robots.map((r) => r.at), tasks: d.tasks.map((t) => t.at), rewards: d.tasks.map((t) => t.reward), values: d.tasks.map((t) => t.value), rNames: d.robots.map((r) => r.name), tNames: d.tasks.map((t) => t.name) };
}
export function analyseAllocation(d: AllocationDoc, S: ReportSection[], M: Metrics): boolean {
  const inst = allocationInstance(d); const { robots, tasks, rewards, rNames, tNames } = inst; const C = costMatrix(robots, tasks); let ok = true; const want = (m: string) => d.methods.includes(m);
  S.push(sec('Instance', 'info', [`${robots.length} robots, ${tasks.length} tasks${d.random ? ` (random, seed ${d.random.seed}, area ${d.random.area} m)` : ''}; cost = Euclidean distance`], { table: robots.length <= 6 && tasks.length <= 10 ? { head: ['robot \\ task', ...tNames], rows: C.map((r, i) => [rNames[i], ...r.map((v) => f(v, 2))]) } : undefined }));
  const routesPlot = (title: string, routes: number[][]) => paths(title, routes.map((r, i) => ({ name: rNames[i], points: [robots[i], ...r.map((j) => tasks[j])].map((p) => [p[0], p[1]] as [number, number]) })), { markers: [...robots.map((p, i) => ({ x: p[0], y: p[1], kind: 'robot' as const, label: rNames[i] })), ...tasks.map((p, j) => ({ x: p[0], y: p[1], kind: 'task' as const, label: tNames[j] }))] });
  if (want('greedy') || want('hungarian')) { const g = greedyAssignment(C), o = optimalAssignment(C); const ratio = g.cost / o.cost; S.push(sec('One task per robot: greedy vs optimal (Hungarian, §10.2, ПР3 step 1)', ratio > 1.5 ? 'warn' : 'ok', [`greedy (cheapest free pair first): total ${f(g.cost, 3)} — ${Object.entries(g.assignment).map(([i, j]) => `${rNames[+i]}→${tNames[j]}`).join(', ')}`, `optimal (Hungarian): total ${f(o.cost, 3)} — ${Object.entries(o.assignment).map(([i, j]) => `${rNames[+i]}→${tNames[j]}`).join(', ')}`, `ratio greedy / optimal = ${f(ratio, 3)}${ratio > 1.5 ? ' — greedy pays for its first cheap choice (the course matrix gives 11.0 vs 3.1)' : ''}`])); M['greedy cost'] = Number(f(g.cost, 3)); M['optimal cost'] = Number(f(o.cost, 3)); M['greedy / optimal'] = Number(f(ratio, 3)); }
  if (want('ssi')) { const s = ssiAuction(robots, tasks); const tot = totalLength(robots, s.routes, tasks); const bf = bruteForceRouting(robots, tasks); S.push(sec('Sequential single-item auction, MiniSum (ПР3 step 2)', 'ok', [`${s.rounds} rounds, ${s.bids} bids (robots × remaining tasks per round); total route length ${f(tot, 3)}, makespan ${f(makespan(robots, s.routes, tasks), 3)}`, ...s.routes.map((r, i) => `${rNames[i]}: ${r.length ? r.map((j) => tNames[j]).join(' → ') : '—'} (${f(totalLength([robots[i]], [r], tasks), 2)})`), Number.isNaN(bf) ? 'instance too large for the exhaustive optimum' : `exhaustive optimum ${f(bf, 3)} → SSI is within ${f(tot / bf, 3)}× (guaranteed ≤ 2× for MiniSum)`], { table: { head: ['round', 'task', 'winner', 'bid (length increase)'], rows: s.log.map((l) => [l.round, tNames[l.task], rNames[l.winner], f(l.bid, 3)]) }, plot: routesPlot('SSI routes', s.routes) })); M['ssi total'] = Number(f(tot, 3)); M['ssi rounds'] = s.rounds; if (!Number.isNaN(bf)) M['ssi / optimum'] = Number(f(tot / bf, 3)); }
  if (want('cbba')) { const g = d.cbba.graph; const A: Matrix = g === 'disk' ? diskGraph(robots, d.cbba.radius) : TOPOLOGIES[g](robots.length); const r = runCbba(robots, tasks, rewards, A, { capacity: d.cbba.capacity, lam: d.cbba.lam, speed: d.cbba.speed }); const cf = isConflictFree(r.agents); const assigned = r.agents.reduce((s, a) => s + a.path.length, 0); ok = ok && cf; S.push(sec('CBBA: bundle building + max-consensus (§10.4, ПР3 steps 3–4)', cf ? 'ok' : 'error', [`communication graph "${g}" with ${edgeCount(A)} links${isConnected(A) ? '' : ' (NOT connected — agreement only inside components)'}; capacity ${d.cbba.capacity}, score Σ R λ^t with λ = ${d.cbba.lam}`, `converged after ${r.iterations} bundle–consensus iterations, ${r.messages} messages; ${cf ? 'conflict-free (every task has one owner and all agents agree)' : 'CONFLICTS remain'}; ${assigned}/${tasks.length} tasks assigned, total score ${f(totalScore(r.agents, tasks, rewards, d.cbba.speed, d.cbba.lam), 3)}`, ...r.agents.map((a) => `${rNames[a.idx]}: ${a.path.length ? a.path.map((j) => `${tNames[j]} (${f(a.y[j], 2)})`).join(' → ') : '—'}`)], { plot: routesPlot('CBBA routes', r.agents.map((a) => a.path)) })); M['cbba iterations'] = r.iterations; M['cbba messages'] = r.messages; M['cbba conflict-free'] = cf; M['cbba assigned'] = assigned; }
  if (want('vickrey')) { const v = vickreyAuction(robots, tasks, inst.values); S.push(sec('Second-price (Vickrey) sequential auction (§9.7)', 'info', [`utility = value − distance; the winner pays the second-best bid, so truthful bids are a dominant strategy`, ...v.rounds.map((r) => `${tNames[r.task]} → ${rNames[r.winner]}: bid ${f(r.bid, 2)}, price ${f(r.price, 2)} (surplus ${f(r.bid - r.price, 2)})`)])); const cnp = contractNetMessages(robots.length, tasks.length); S.push(sec('Contract-net protocol traffic (chapter 6)', 'info', [`announce ${cnp.announce} + bids ${cnp.bids} + awards ${cnp.awards} = ${cnp.total} messages for ${tasks.length} tasks and ${robots.length} robots (vs CBBA above)`])); }
  return ok;
}

// ---------------------------------------------------------------------------------------------------------------------
// grid MAPF
// ---------------------------------------------------------------------------------------------------------------------
export function gridInstance(d: GridMapfDoc): { grid: boolean[][]; starts: Cell[]; goals: Cell[]; names: string[] } {
  const grid = loadMap(d.map.join('\n')); if (d.random) { const rng = new Rng(d.random.seed); const free = freeCells(grid); const idx = rng.sample(free.length, 2 * d.random.agents); return { grid, starts: idx.slice(0, d.random.agents).map((i) => free[i]), goals: idx.slice(d.random.agents).map((i) => free[i]), names: Array.from({ length: d.random.agents }, (_, i) => String.fromCharCode(97 + i)) }; }
  for (const a of d.agents) for (const c of [a.start, a.goal]) if (c[0] < 0 || c[0] >= grid.length || c[1] < 0 || c[1] >= grid[0].length || grid[c[0]][c[1]]) throw new Error(`agent ${a.name}: cell ${c} is outside the map or on a shelf`);
  return { grid, starts: d.agents.map((a) => a.start), goals: d.agents.map((a) => a.goal), names: d.agents.map((a) => a.name) };
}
export function analyseGridMapf(d: GridMapfDoc, S: ReportSection[], M: Metrics): boolean {
  const { grid, starts, goals, names } = gridInstance(d); let ok = true; const R = grid.length, Cn = grid[0].length;
  const obstacles = grid.flatMap((row, r) => row.map((b, c) => (b ? { x: c, y: -r, w: 1, h: 1 } : null)).filter(Boolean)) as Array<{ x: number; y: number; w: number; h: number }>;
  const plotPaths = (title: string, ps: Path[]) => paths(title, ps.map((p, i) => ({ name: names[i], points: p.map((c) => [c[1] + 0.5, -c[0] - 0.5] as [number, number]) })), { obstacles: obstacles.map((o) => ({ ...o, y: o.y - 1 })), markers: [...starts.map((c, i) => ({ x: c[1] + 0.5, y: -c[0] - 0.5, kind: 'start' as const, label: names[i] })), ...goals.map((c, i) => ({ x: c[1] + 0.5, y: -c[0] - 0.5, kind: 'goal' as const, label: names[i] }))] });
  const single = starts.map((s, i) => spaceTimeAStar(grid, s, goals[i])); const lb = single.reduce((s, p) => s + (p ? p.length - 1 : Infinity), 0);
  S.push(sec('Instance', single.every(Boolean) ? 'info' : 'error', [`${R}×${Cn} grid, ${freeCells(grid).length} free cells, ${starts.length} agents; sum of individual shortest paths (lower bound) = ${lb}`, ...(single.every(Boolean) ? [] : ['some goal is unreachable'])]));
  if (!single.every(Boolean)) return false;
  let best: Path[] | null = null;
  if (d.methods.includes('prioritized')) { const pp = prioritizedPlanning(grid, starts, goals); const soc = pp ? sumOfCosts(pp) : NaN; S.push(sec('Prioritized planning with a reservation table (ПР4 step 2)', pp ? 'ok' : 'warn', pp ? [`order ${names.join(' > ')}: sum of costs ${soc} (lower bound ${lb}), makespan ${makespanOf(pp)}; first conflict: ${firstConflict(pp) ? 'FOUND' : 'none'}`] : ['no solution in this priority order — prioritized planning is not complete (an agent parked on its goal can wall in a later one)'], pp ? { plot: plotPaths('Prioritized paths', pp) } : {})); M['prioritized SOC'] = pp ? soc : 'fail'; if (pp) best = pp; }
  if (d.methods.includes('cbs')) { const r = cbs(grid, starts, goals); if (r.paths) { const soc = sumOfCosts(r.paths); const c = firstConflict(r.paths); ok = ok && !c; S.push(sec('Conflict-based search (ПР4 step 4)', c ? 'error' : 'ok', [`optimal sum of costs ${soc} (lower bound ${lb}, ${r.nodes} constraint-tree nodes expanded), makespan ${makespanOf(r.paths)}; conflicts: ${c ? 'FOUND' : 'none'}`, ...r.paths.map((p, i) => `${names[i]}: ${p.map((cc) => `(${cc[0]},${cc[1]})`).join(' ')}`)], { plot: plotPaths('CBS paths', r.paths) })); M['cbs SOC'] = soc; M['cbs nodes'] = r.nodes; best = r.paths; } else { ok = false; S.push(sec('Conflict-based search', 'error', [`no solution within ${r.nodes} nodes`])); } }
  if (d.execute && best) { const rng = new Rng(d.execute.seed); const rows: Array<Array<string | number>> = []; let coll = 0, naive = 0; for (let k = 0; k < d.execute.runs; k++) { const ex = executeAdg(best, d.execute.delay, rng); const nv = executeNaive(best, d.execute.delay, new Rng(d.execute.seed + 100 + k)); coll += ex.collisions; naive += nv; rows.push([k + 1, ex.ticks ?? 'stuck', ex.collisions, nv]); } ok = ok && coll === 0; S.push(sec(`Execution with delays through the action dependency graph (ПР4 step 5, delay probability ${d.execute.delay})`, coll === 0 ? 'ok' : 'error', [`ADG: a robot enters a cell only after every robot that planned to be there earlier has left it — ${coll} collisions in ${d.execute.runs} runs (plan makespan ${makespanOf(best)} ticks)`, `clock-driven execution without coordination: ${naive} robot pairs in the same cell over the same runs`], { table: { head: ['run', 'ticks (ADG)', 'collisions (ADG)', 'collisions (naive)'], rows } })); M['adg collisions'] = coll; M['naive collisions'] = naive; }
  return ok;
}

// ---------------------------------------------------------------------------------------------------------------------
// coverage / estimation
// ---------------------------------------------------------------------------------------------------------------------
export function coverageSetup(d: CoverageDoc): { q: Vec2[]; dA: number; phi: number[]; p0: Vec2[]; names: string[] } {
  const { q, dA } = gridPoints(d.area[0], d.area[1], d.area[2], d.area[3], d.res); const phi = d.density.kind === 'uniform' ? q.map(() => 1) : gaussianDensity(q, d.density.center, d.density.sigma, d.density.base); const rng = new Rng(d.seed);
  const p0: Vec2[] = Array.from({ length: d.n }, (_, i) => d.robots[i]?.at ?? [rng.uniform(d.spawn[0], d.spawn[1]), rng.uniform(d.spawn[0], d.spawn[1])]); return { q, dA, phi, p0, names: Array.from({ length: d.n }, (_, i) => d.robots[i]?.name ?? `r${i + 1}`) };
}
export function analyseCoverage(d: CoverageDoc, S: ReportSection[], M: Metrics): boolean {
  const { q, dA, phi, p0, names } = coverageSetup(d); let p = p0; const cost = (P: Vec2[]) => (d.range ? limitedCost(P, q, phi, dA, d.range) : coverageCost(P, q, phi, dA)); const costs = [cost(p)]; const hist: Vec2[][] = [p];
  for (let k = 0; k < d.iterations; k++) { p = d.range ? limitedLloydStep(p, q, phi, dA, d.range, d.gain) : lloydStep(p, q, phi, dA, d.gain); costs.push(cost(p)); hist.push(p); }
  const mono = costs.every((c, i) => i === 0 || c <= costs[i - 1] + 1e-9); const red = costs[costs.length - 1] / costs[0]; const lab = voronoiLabels(p, q); const { M: masses } = massCentroids(p, q, phi, dA, lab); const ok = mono && red < 0.9;
  const cols = Math.round((d.area[1] - d.area[0]) / d.res); const rows = Math.round((d.area[3] - d.area[2]) / d.res); const cells: number[][] = []; for (let r = rows - 1; r >= 0; r--) cells.push(lab.slice(r * cols, (r + 1) * cols).map((v) => v + 1));
  const c: Vec2 = [mean(p.map((z) => z[0])), mean(p.map((z) => z[1]))];
  S.push(sec(`${d.range ? `Limited-range Lloyd (r_sense = ${d.range}, ПР5 step 3)` : 'Lloyd iteration on the Voronoi partition (Cortés et al. 2004, ПР5 steps 1–2)'}`, ok ? 'ok' : 'warn', [`${d.n} robots, grid ${cols}×${rows} (res ${d.res}), density ${d.density.kind}${d.density.kind === 'gaussian' ? ` centred at (${d.density.center[0]}, ${d.density.center[1]}), σ = ${d.density.sigma}, base ${d.density.base}` : ''}`, `coverage functional H = Σ φ minᵢ‖q − pᵢ‖² dA: ${f(costs[0], 4)} → ${f(costs[costs.length - 1], 4)} after ${d.iterations} iterations (${f(100 * (1 - red), 1)} % lower); ${mono ? 'monotone non-increasing as the theory promises' : 'NOT monotone'}`, `cell masses: ${masses.map((m, i) => `${names[i]} ${f(m, 3)}`).join(', ')}; centroid of the robots (${f(c[0], 2)}, ${f(c[1], 2)})`, ...(d.range ? ['each robot only needs neighbours closer than 2·r_sense: the algorithm is decentralised; robots outside the density stay put'] : [])], { plot: paths('Robot motion', trajectories(hist, names), { markers: p.map((z, i) => ({ x: z[0], y: z[1], kind: 'robot' as const, label: names[i] })).concat(d.density.kind === 'gaussian' ? [{ x: d.density.center[0], y: d.density.center[1], kind: 'source' as never, label: 'hot spot' }] : []) }) }));
  S.push(sec('Coverage cost per iteration', 'info', [], { plot: lines('H(p)', [seriesOf('H', costs)], 'iteration', 'H') })); S.push(sec('Final Voronoi partition (labels)', 'info', [], { plot: grid('Voronoi cells', cells, 'labels') }));
  M['H0'] = Number(f(costs[0], 4)); M['H final'] = Number(f(costs[costs.length - 1], 4)); M['reduction %'] = Number(f(100 * (1 - red), 1)); M['monotone'] = mono; return ok;
}
export function analyseEstimation(d: EstimationDoc, S: ReportSection[], M: Metrics): boolean {
  const rng = new Rng(d.seed); const g = d.graph === 'disk' ? randomGeometricGraph(d.n, d.radius, rng) : { p: undefined, A: TOPOLOGIES[d.graph](d.n) }; const A = g.A; const W = metropolisWeights(A); const names = Array.from({ length: d.n }, (_, i) => `r${i + 1}`);
  const R: M2[] = Array.from({ length: d.n }, () => [[rng.uniform(d.noise[0], d.noise[1]), 0], [0, rng.uniform(d.noise[0], d.noise[1])]]); const z: Vec2[] = R.map((Ri) => [d.target[0] + rng.normal(0, Math.sqrt(Ri[0][0])), d.target[1] + rng.normal(0, Math.sqrt(Ri[1][1]))]);
  const cen = centralizedEstimate(z, R); const est = informationConsensus(z, R, W, d.iterations); const nav = naiveAverageConsensus(z, W, d.iterations); const err = (E: Vec2[][]) => E.map((e) => Math.max(...e.map((x) => dist(x, cen.x)))); const eI = err(est), eN = err(nav); const errTrue = dist(cen.x, d.target); const naiveTrue = dist(nav[d.iterations][0], d.target); const ok = eI[eI.length - 1] < 1e-4;
  S.push(sec('Information-form consensus of measurements (ПР5 step 4)', ok ? 'ok' : 'warn', [`${d.n} robots on a ${d.graph} graph (${edgeCount(A)} links, λ₂ = ${f(algebraicConnectivity(A), 3)}), Metropolis weights; measurement variances in [${d.noise[0]}, ${d.noise[1]}]`, `centralised estimate (${f(cen.x[0], 4)}, ${f(cen.x[1], 4)}) — error to the true target ${f(errTrue, 4)}; every robot's estimate converges to it: max deviation ${f(eI[0], 3)} → ${f(eI[eI.length - 1], 6)} after ${d.iterations} iterations`, `plain averaging ignores the accuracy of the sensors: it converges to (${f(nav[d.iterations][0][0], 3)}, ${f(nav[d.iterations][0][1], 3)}), error to the target ${f(naiveTrue, 4)} (centralised: ${f(errTrue, 4)})`], { graph: networkView(A, names, g.p), plot: lines('Max deviation from the centralised estimate', [seriesOf('information consensus', eI), { ...seriesOf('plain average', eN), dashed: true }], 'iteration', 'm', { ylog: true }) }));
  M['centralised error'] = Number(f(errTrue, 4)); M['naive error'] = Number(f(naiveTrue, 4)); M['final deviation'] = Number(f(eI[eI.length - 1], 6));
  if (d.ci) { const A2: M2 = [[d.ci.A[0], 0], [0, d.ci.A[1]]], B2: M2 = [[d.ci.B[0], 0], [0, d.ci.B[1]]]; const ci = covarianceIntersection(d.ci.a, A2, d.ci.b, B2); S.push(sec('Covariance intersection of two correlated estimates (ПР5 step 5)', 'info', [`a = (${d.ci.a}), diag A = (${d.ci.A}); b = (${d.ci.b}), diag B = (${d.ci.B}) → ω = ${f(ci.omega, 3)}, x = (${f(ci.x[0], 3)}, ${f(ci.x[1], 3)}), diag P = (${f(ci.P[0][0], 3)}, ${f(ci.P[1][1], 3)})`, 'CI never claims more accuracy than either source when their correlation is unknown (P ≥ the naive independent fusion)'])); M['ci omega'] = Number(f(ci.omega, 3)); }
  return ok;
}

// ---------------------------------------------------------------------------------------------------------------------
// safety
// ---------------------------------------------------------------------------------------------------------------------
export function safetyInstance(d: SafetyDoc): { p: Vec2[]; goals: Vec2[]; names: string[] } {
  if (d.scenario === 'custom') return { p: d.robots.map((r) => r.at), goals: d.robots.map((r) => r.goal), names: d.robots.map((r) => r.name) };
  if (d.scenario === 'crossing') return { p: [[0, 0], [1, 0.05]], goals: [[1, 0], [0, 0.05]], names: ['r1', 'r2'] };
  const a = antipodal(d.n, d.radius); return { p: a.p, goals: a.goals, names: a.p.map((_, i) => `r${i + 1}`) };
}
export function analyseSafety(d: SafetyDoc, S: ReportSection[], M: Metrics): boolean {
  const { p, goals, names } = safetyInstance(d); const o = { dSafe: d.dSafe, gamma: d.gamma, vmax: d.vmax, dt: d.dt, senseRadius: d.sense, gain: d.gain, uncooperative: d.uncooperative, speeds: d.scenario === 'custom' ? d.robots.map((r) => r.speed ?? d.vmax) : undefined }; let ok = true;
  const run = runGroup(p, goals, d.steps, { ...o, unstuck: !!d.unstuck, holdSteps: d.unstuck?.hold, staleLag: d.stale?.lag }); const safe = run.dmin >= d.dSafe - 3e-3; const pushed = !!d.stale && run.deadlock; const deadlock = run.deadlock && !pushed; ok = safe && !deadlock;
  S.push(sec(`Barrier-function filter (h = ‖pᵢ − pⱼ‖² − d², ḣ ≥ −γh with share ½; ПР6 steps 1–3)${d.unstuck ? ' + keep-right deadlock rule (step 4)' : ''}${d.stale ? ' + stale-data margins (step 5)' : ''}`, ok ? 'ok' : deadlock && safe ? 'warn' : 'error', [`${p.length} robots, d_safe = ${d.dSafe} m, γ = ${d.gamma}, vmax = ${d.vmax} m/s, sensing ${d.sense} m, dt = ${d.dt} s × ${d.steps} steps`, `minimum pair distance ${f(run.dmin, 4)} m → ${safe ? 'the safety set was never left' : 'SAFETY VIOLATED'}; max distance to goals at the end ${f(run.maxGoalError, 3)} m → ${deadlock ? 'DEADLOCK (the symmetric configuration is a fixed point of the filter)' : pushed ? 'a robot was pushed away from its goal by the intruder (the minimum-norm evasion is straight back; the goal is regained once the intruder is out of range)' : `all goals reached${run.arrivedAt !== null ? ` at t = ${f(run.arrivedAt, 1)} s` : ''}`}`, ...(d.uncooperative.length ? [`uncooperative robots (no filter): ${d.uncooperative.map((i) => names[i]).join(', ')}`] : []), ...(d.stale ? [`neighbour positions are ${d.stale.lag} steps (${f(d.stale.lag * d.dt, 2)} s) old: d' = d + vmax·age and share = 1 with the worst-case approach term`] : [])], { plot: paths('Trajectories with the safety filter', trajectories(run.traj, names), { markers: goals.map((g, i) => ({ x: g[0], y: g[1], kind: 'goal' as const, label: names[i] })) }) }));
  M['min distance'] = Number(f(run.dmin, 4)); M['max goal error'] = Number(f(run.maxGoalError, 3)); M['deadlock'] = deadlock; if (run.arrivedAt !== null) M['arrival time'] = Number(f(run.arrivedAt, 1));
  if (d.unstuck) { const plain = runGroup(p, goals, d.steps, o); S.push(sec('Without the deadlock rule', plain.deadlock ? 'warn' : 'info', [`min distance ${f(plain.dmin, 4)} m, max goal error ${f(plain.maxGoalError, 3)} m → ${plain.deadlock ? 'deadlock: everyone yields symmetrically and nobody passes' : 'no deadlock in this configuration'}`, `the rule rotates the nominal velocity by ${f((d.unstuck.angle * 180) / Math.PI, 0)}° for ${d.unstuck.hold} steps once progress stalls — all robots turn the same way, breaking the symmetry consistently (hysteresis keeps it from switching off at the first sideways step)`], { plot: paths('Trajectories without the rule', trajectories(plain.traj, names), { markers: goals.map((g, i) => ({ x: g[0], y: g[1], kind: 'goal' as const, label: names[i] })) }) })); M['deadlock without rule'] = plain.deadlock; }
  if (d.compareNominal) { let q = p.map((z) => [z[0], z[1]] as Vec2); let dmin = Infinity; for (let k = 0; k < d.steps; k++) { const u = goToGoal(q, goals, d.gain, d.vmax); q = q.map((z, i) => [z[0] + d.dt * u[i][0], z[1] + d.dt * u[i][1]] as Vec2); dmin = Math.min(dmin, minDist(q)); } S.push(sec('Nominal go-to-goal without the filter', dmin < d.dSafe ? 'warn' : 'info', [`min pair distance ${f(dmin, 4)} m → ${dmin < d.dSafe ? 'collision (below d_safe)' : 'no collision here'}`])); M['nominal min distance'] = Number(f(dmin, 4)); }
  return ok;
}

// ---------------------------------------------------------------------------------------------------------------------
// warehouse fleet (homework)
// ---------------------------------------------------------------------------------------------------------------------
export function analyseWarehouse(d: WarehouseDoc, S: ReportSection[], M: Metrics): boolean {
  const cfg = d.cfg; const sim = new FleetSim(cfg); const wh = sim.wh; const m = sim.run(cfg.duration); const ok = m.pathConflicts === 0 && m.delivered > 0;
  const obstacles = wh.grid.flatMap((row, r) => row.map((b, c) => (b ? { x: (c - 0.5) * wh.cell, y: (-r - 0.5) * wh.cell, w: wh.cell, h: wh.cell } : null)).filter(Boolean)) as Array<{ x: number; y: number; w: number; h: number }>;
  const stationMarkers = Object.entries(wh.stations).map(([n, c]) => { const [x, y] = wh.cellXY(c); return { x, y, kind: 'station' as const, label: n }; });
  const traj = sim.snapshots.length ? sim.snapshots.map((s) => s.pos as Vec2[]) : [sim.robots.map((r) => [r.x, r.y] as Vec2)];
  S.push(sec(`Fleet simulation: ${cfg.robots.names.length} robots, ${f(cfg.duration, 0)} s (homework stages 1–4)`, ok ? 'ok' : 'error', [`orders: ${m.created} created (first batch ${cfg.orders.firstBatch}, rate ${cfg.orders.rate}/s), ${m.delivered} delivered, ${m.open} open at the end; throughput ${f(m.throughputPerHour, 1)} orders/h`, `order latency (creation → delivery): mean ${f(m.meanLatency, 1)} s, max ${f(m.maxLatency, 1)} s; robot utilisation ${f(100 * m.utilisation, 0)} %; deliveries per robot: ${Object.entries(m.perRobot).map(([k, v]) => `${k} ${v}`).join(', ')}`, `CBBA (capacity ${cfg.cbba.capacity}, λ = ${cfg.cbba.discount}, period ${cfg.cbba.period} s, commit after ${cfg.cbba.commitAfter} s, lost after ${cfg.cbba.lostAfter} s): ${m.doubleCommits} conflicting claims (double commits) — radio range ${cfg.robots.radioRange} m, loss ${cfg.robots.radioDrop}; ${m.messages} state messages`, `traffic (settle ${cfg.traffic.settle} s, lookahead ${cfg.traffic.lookahead}, wait limit ${cfg.traffic.waitLimit} s${cfg.traffic.protective === false ? ', protective layer OFF' : ', protective layer on'}): ${m.pathConflicts} path conflicts (two robots in one cell), ${m.nearMisses} near misses, ${m.replans} detours, ${m.proximityStops} proximity stops`, ...(cfg.faults.length ? [`faults: ${cfg.faults.map((x) => `${x.robot} ${x.kind} at ${x.at} s`).join(', ')}`] : [])], { plot: paths('Robot positions (5 s snapshots)', trajectories(traj, cfg.robots.names), { obstacles, markers: stationMarkers }) }));
  const del = sim.deliveredOrders; S.push(sec('Deliveries over time', 'info', [], { plot: lines('delivered orders', [{ name: 'delivered', points: [[0, 0], ...del.map((x, i) => [x.deliveredAt, i + 1] as [number, number])] }, { name: 'created', points: [[0, cfg.orders.firstBatch], ...[...sim.orders.values()].filter((o) => (o.createdAt ?? 0) > 0).map((o, i) => [o.createdAt ?? 0, cfg.orders.firstBatch + i + 1] as [number, number])], dashed: true }], 't, s', 'orders') }));
  const events = sim.log.filter((l) => /FAULT|recovered|reclaims|DOUBLE|CONFLICT|detours|released/.test(l)); const faultLines = events.filter((l) => /FAULT|recovered/.test(l)); const others = events.filter((l) => !/FAULT|recovered/.test(l)); if (events.length) S.push(sec(`Faults, reclaims, conflicts and detours (${events.length} events)`, cfg.faults.length || m.doubleCommits || m.pathConflicts ? 'warn' : 'info', [...faultLines, ...others.slice(0, 25), ...(others.length > 25 ? [`… ${others.length - 25} more`] : [])]));
  S.push(sec('Event log (last 40 lines)', 'info', sim.log.slice(-40)));
  M['delivered'] = m.delivered; M['throughput /h'] = Number(f(m.throughputPerHour, 1)); M['mean latency s'] = Number(f(m.meanLatency, 1)); M['max latency s'] = Number(f(m.maxLatency, 1)); M['double commits'] = m.doubleCommits; M['path conflicts'] = m.pathConflicts; M['detours'] = m.replans; M['messages'] = m.messages; M['utilisation'] = Number(f(m.utilisation, 2));
  void Warehouse; return ok;
}
