/** Analysers of the chapter-theory kinds: game (ch. 9), marl (ch. 7), evo (ch. 12), ca (§4.6), fuzzy (§13.4), resilience (ch. 16, §13.5). */
import type { ReportSection } from '../ctl/analysis';
import { Metrics, f, sec, lines, paths, grid, bars, seriesOf, networkView, mean } from './report';
import { Rng } from './rng';
import { TOPOLOGIES, edgeCount, algebraicConnectivity, maxConsensusStep } from './graph';
import { convergenceFactor } from './consensus';
import { dominatedStrategies, pureNash, mixedNash2x2, paretoOptimal, bestResponseDynamics, fictitiousPlay, exactPotential, shapleyValue, inCore, isSuperadditive, replicatorDynamics } from './games';
import { gridWorldFromMap, qLearning, optimalQ, greedyPath, independentQLearning, sKey } from './learning';
import { geneticAlgorithm, rouletteTable, differentialEvolution, evolutionStrategy, BENCHMARKS } from './evo';
import { wolframRun, wolframStats, lifeFromText, lifeRun, pheromoneStep } from './ca';
import { obstacleController, fuzzyInfer, simulateFuzzyAvoidance } from './fuzzy';
import { byzantineAgreement, byzantineBound, trustConsensus, degradation, commonLyapunov, dwellTimeSweep } from './resilience';
import { evalExpr } from '../ctl/expr';
import { GameDoc, MarlDoc, EvoDoc, CaDoc, FuzzyDoc, ResilienceDoc } from './dsl';

export function analyseGame(d: GameDoc, S: ReportSection[], M: Metrics): boolean {
  let ok = true;
  if (d.game) {
    const g = d.game; const cell = (i: number, j: number) => `${g.rows[i]} / ${g.cols[j]}`; const dom = dominatedStrategies(g); const pn = pureNash(g); const mx = mixedNash2x2(g); const par = paretoOptimal(g);
    S.push(sec(`Normal-form game: ${d.players[0]} (rows) vs ${d.players[1]} (columns)`, 'info', [], { table: { head: ['', ...g.cols], rows: g.rows.map((r, i) => [r, ...g.cols.map((_, j) => `(${g.u[i][j][0]}, ${g.u[i][j][1]})`)]) } }));
    const nl = [`strictly dominated strategies: ${dom.row.length || dom.col.length ? `${d.players[0]}: ${dom.row.join(', ') || '—'}; ${d.players[1]}: ${dom.col.join(', ') || '—'}` : 'none'}`, `pure Nash equilibria: ${pn.length ? pn.map(([i, j]) => `(${cell(i, j)}) → (${g.u[i][j][0]}, ${g.u[i][j][1]})`).join('; ') : 'none (only mixed)'}`, mx ? `mixed equilibrium (2×2): ${d.players[0]} plays ${g.rows[0]} with p = ${f(mx.p, 3)}, ${d.players[1]} plays ${g.cols[0]} with q = ${f(mx.q, 3)}; expected payoffs (${f(mx.payoff[0], 3)}, ${f(mx.payoff[1], 3)})` : 'no fully mixed equilibrium (2×2 formula not applicable)', `Pareto-optimal outcomes: ${par.map(([i, j]) => `(${cell(i, j)})`).join(', ')}${pn.some(([i, j]) => !par.some(([a, b]) => a === i && b === j)) ? ' — an equilibrium that is not Pareto-optimal is the price of anarchy in action' : ''}`];
    S.push(sec('Dominance, equilibria and efficiency (§9.2–9.3)', 'ok', nl)); M['pure equilibria'] = pn.length; if (mx) { M['mixed p'] = Number(f(mx.p, 3)); M['mixed payoff'] = Number(f(mx.payoff[0], 3)); }
    const br = bestResponseDynamics(g, d.start && d.start[0] >= 0 && d.start[1] >= 0 ? d.start : [0, 0]); const fp = fictitiousPlay(g, d.rounds); const pot = exactPotential(g);
    S.push(sec('Learning the equilibrium: best response and fictitious play (§9.8.2)', br.converged ? 'ok' : 'warn', [`best-response dynamics from (${cell(br.trace[0][0], br.trace[0][1])}): ${br.converged ? `converges in ${br.steps} steps to (${cell(br.profile[0], br.profile[1])})` : `cycles (${br.trace.slice(0, 6).map(([i, j]) => cell(i, j)).join(' → ')} …)`}`, `fictitious play, ${d.rounds} rounds: empirical frequencies ${d.players[0]} (${g.rows.map((r, i) => `${r} ${f(fp.rowFreq[i], 2)}`).join(', ')}), ${d.players[1]} (${g.cols.map((c, j) => `${c} ${f(fp.colFreq[j], 2)}`).join(', ')}); last profile (${cell(fp.last[0], fp.last[1])})`, pot.isPotential ? `exact potential game: Φ = ${JSON.stringify(pot.phi!.map((r) => r.map((v) => Number(f(v, 2)))))} — every improvement path ends in a pure equilibrium` : 'not an exact potential game (best-response cycles are possible)'])); M['potential game'] = pot.isPotential; M['best response converges'] = br.converged;
    if (d.replicator && g.rows.length === 2) { const A = g.u.map((r) => r.map((c) => c[0])); const rd = replicatorDynamics(A, d.replicator); S.push(sec('Replicator dynamics of the symmetric game (§9.6)', 'info', [`share of ${g.rows[0]}: ${f(d.replicator[0], 2)} → ${f(rd[rd.length - 1][0], 3)}`], { plot: lines('population share', [seriesOf(g.rows[0], rd.map((x) => x[0]))], 'time', 'share') })); }
  }
  if (d.coalition) { const { v, n, names } = d.coalition; const phi = shapleyValue(v, n); const core = inCore(v, n, phi); const sup = isSuperadditive(v, n); const eq = inCore(v, n, Array(n).fill((v[[...Array(n).keys()].join(',')] ?? 0) / n)); ok = ok && core.inCore; S.push(sec('Cooperative game: Shapley value and the core (§9.5)', core.inCore ? 'ok' : 'warn', [`characteristic function ${sup ? 'is' : 'is NOT'} superadditive; grand coalition value ${v[[...Array(n).keys()].join(',')] ?? 0}`, `Shapley value φ = (${phi.map((x) => f(x, 2)).join(', ')}) for (${names.join(', ')}) — the average marginal contribution over all orderings`, `φ ${core.inCore ? 'lies in the core (no coalition can profitably deviate)' : `is NOT in the core: blocking coalitions ${core.blocking.map((b) => b.split(',').map((i) => names[+i]).join('')).join(', ')}`}; equal split ${eq.inCore ? 'is also in the core' : `is blocked by ${eq.blocking.map((b) => b.split(',').map((i) => names[+i]).join('')).join(', ')}`}`], { plot: bars('Shapley value', phi.map((x, i) => ({ label: names[i], value: Number(f(x, 2)) }))) })); M['shapley'] = phi.map((x) => f(x, 2)).join(' / '); M['in core'] = core.inCore; }
  return ok;
}

export function analyseMarl(d: MarlDoc, S: ReportSection[], M: Metrics): boolean {
  const w = gridWorldFromMap(d.map.join('\n'), { stepReward: d.stepReward, goalReward: d.goalReward }); const corridor = w.actions.length === 2; const opt = optimalQ(w, d.gamma); const names = w.actionNames; let ok = true;
  if (d.forceRight || (corridor && d.map.join('') === 'S..G')) { const r = qLearning(w, { alpha: d.alpha, gamma: d.gamma, epsilon: 0, episodes: 3, forceAction: 1, snapshots: [1, 2, 3] }); const st = ['0,0', '0,1', '0,2'].filter((k) => opt[k]); S.push(sec('Table 7.2: Q(s, right) after episodes 1–3 along the fixed path (α = 0.5, γ = 0.9)', 'info', ['the value of the goal "leaks" backwards one cell per episode (temporal differences); the course table prints 4.03 for Q(s₂) after episode 3 — the update 1.5 + 0.5·(−1 + 0.9·7.5 − 1.5) gives 3.625'], { table: { head: ['state', 'start', 'ep. 1', 'ep. 2', 'ep. 3', 'Q*'], rows: st.map((k, i) => [`s${i + 1}`, 0, ...r.snapshots.map((s) => f(s.Q[k]?.[1] ?? 0, 3)), f(opt[k][1], 3)]) } })); }
  const r = qLearning(w, { alpha: d.alpha, gamma: d.gamma, epsilon: d.epsilon, episodes: d.episodes, sarsa: d.sarsa, rng: new Rng(d.seed) }); const path = greedyPath(w, r.Q); const startQ = r.Q.get(sKey(w.start)) ?? []; const bestStart = Math.max(...startQ); const optStart = Math.max(...opt[sKey(w.start)]); const reached = path.length && path[path.length - 1][0] === w.goal[0] && path[path.length - 1][1] === w.goal[1]; ok = !!reached;
  const win = Math.max(1, Math.floor(d.episodes / 20)); const avgRet = r.returns.map((_, i) => mean(r.returns.slice(Math.max(0, i - win + 1), i + 1)));
  S.push(sec(`${d.sarsa ? 'SARSA' : 'Q-learning'} on the ${w.rows}×${w.cols} grid (ε-greedy ε = ${d.epsilon}, ${d.episodes} episodes)`, ok ? 'ok' : 'warn', [`greedy policy from the start: ${path.map((c) => `(${c[0]},${c[1]})`).join(' → ')} — ${reached ? `reaches the goal in ${path.length - 1} steps` : 'does NOT reach the goal yet'}`, `Q(start) = ${f(bestStart, 3)} vs Q* = ${f(optStart, 3)} (value iteration); learned Q per state: ${[...r.Q].slice(0, 6).map(([k, q]) => `${k}: ${q.map((x, a) => `${names[a]} ${f(x, 2)}`).join(' ')}`).join(' | ')}${r.Q.size > 6 ? ' …' : ''}`], { plot: lines('Return per episode (moving average)', [seriesOf('return', avgRet, 1), seriesOf('steps', r.steps, 1)], 'episode') })); M['Q(start)'] = Number(f(bestStart, 3)); M['Q*(start)'] = Number(f(optStart, 3)); M['greedy steps'] = path.length - 1;
  if (d.agents) { const a = d.agents; const res = independentQLearning(w, [[a.starts[0][0], a.starts[0][1]], [a.starts[1][0], a.starts[1][1]]], [[a.goals[0][0], a.goals[0][1]], [a.goals[1][0], a.goals[1][1]]], { episodes: a.episodes, collisionPenalty: a.penalty, rng: new Rng(d.seed + 1), alpha: d.alpha, gamma: d.gamma }); const okA = res.collisionsLast <= res.collisionsFirst; ok = ok && okA; const k = Math.max(1, Math.floor(a.episodes / 20)); const ret = res.returns[0].map((_, i) => mean(res.returns[0].slice(Math.max(0, i - k + 1), i + 1)) + mean(res.returns[1].slice(Math.max(0, i - k + 1), i + 1))); S.push(sec('Independent Q-learning of two robots (§7.4.2): each treats the other as part of the environment', okA ? 'ok' : 'warn', [`collision penalty ${a.penalty}; collisions per episode ${f(res.collisionsFirst, 2)} (first 10 %) → ${f(res.collisionsLast, 2)} (last 10 %); episode length ${f(res.stepsFirst, 1)} → ${f(res.stepsLast, 1)} steps`, 'no convergence guarantee (the environment is non-stationary for each learner), but with weak coupling the robots learn compatible paths'], { plot: lines('Joint return (moving average)', [seriesOf('return', ret, 1)], 'episode') })); M['iql collisions last'] = Number(f(res.collisionsLast, 2)); }
  return ok;
}

export function analyseEvo(d: EvoDoc, S: ReportSection[], M: Metrics): boolean {
  let ok = true;
  for (const m of d.methods) {
    if (m.method === 'ga') {
      const fit = (x: number) => { const v = evalExpr(m.fitness, { x }); return typeof v === 'number' && Number.isFinite(v) ? v : 0; }; const ga = geneticAlgorithm(fit, { bits: m.bits, popSize: m.pop, generations: m.generations, pc: m.pc, pm: m.pm, elitism: m.elitism, rng: new Rng(m.seed), initial: m.initial }); const t0 = rouletteTable(ga.history[0].population, ga.history[0].fitness); let best = 0, bv = -Infinity; for (let x = 0; x < 1 << m.bits; x++) { const v = fit(x); if (v > bv) { bv = v; best = x; } } const okG = ga.bestFitness >= bv - 1e-9; ok = ok && okG;
      S.push(sec(`Genetic algorithm: maximise ${m.fitness} on ${m.bits}-bit integers (§12.2)`, okG ? 'ok' : 'warn', [`population ${m.pop}, roulette selection, one-point crossover p_c = ${m.pc}, bit mutation p_m = ${m.pm}${m.elitism ? ', elitism' : ''}, ${m.generations} generations`, `initial population: mean fitness ${f(ga.history[0].mean, 2)}, best ${ga.history[0].bestFitness}; final best ${ga.best} (x = ${ga.bestX}, f = ${f(ga.bestFitness, 2)}) — optimum x* = ${best}, f = ${f(bv, 2)} ${okG ? 'found' : 'not found yet'}`], { table: { head: ['individual', 'x', 'f', 'p (roulette)', 'expected copies'], rows: t0.map((r) => [r.individual, r.x, f(r.f, 2), f(r.p, 3), f(r.expected, 2)]) }, plot: lines('Fitness per generation', [seriesOf('best', ga.history.map((h) => h.bestFitness)), { ...seriesOf('mean', ga.history.map((h) => h.mean)), dashed: true }], 'generation', 'f') })); M['ga best x'] = ga.bestX; M['ga best f'] = Number(f(ga.bestFitness, 2));
    } else if (m.objective === 'consensus') {
      const A = (TOPOLOGIES[m.graph] ?? TOPOLOGIES.path)(m.n); const emax = maxConsensusStep(A); const obj = (x: number[]) => { const c = convergenceFactor(A, x[0]); return c.rho; }; const es = evolutionStrategy(obj, [0.5 * emax], { generations: m.generations, sigma0: 0.2 * emax, rng: new Rng(m.seed), lo: [1e-4], hi: [2 * emax] }); const c = convergenceFactor(A, 1); S.push(sec(`Evolution strategy tuning the consensus step on a ${m.graph} of ${m.n} robots (§12.3, §12.5)`, 'ok', [`objective: the convergence factor ρ(ε) of x⁺ = x − εLx; (μ, λ) ES with self-adaptive σ, ${m.generations} generations`, `found ε = ${f(es.best[0], 4)} with ρ = ${f(es.value, 4)}; theory: ε* = 2/(λ₂ + λₙ) = ${f(c.epsOpt, 4)} with ρ* = ${f(c.rhoOpt, 4)} (1/Δmax = ${f(emax, 4)})`], { plot: lines('best ρ per generation', [seriesOf('ρ', es.history)], 'generation', 'ρ') })); M['es eps'] = Number(f(es.best[0], 4)); M['eps optimum'] = Number(f(c.epsOpt, 4)); ok = ok && Math.abs(es.best[0] - c.epsOpt) < 0.05 * emax + 1e-6;
    } else {
      const b = BENCHMARKS[m.benchmark] ?? BENCHMARKS.sphere; const lo = Array(m.dim).fill(b.lo), hi = Array(m.dim).fill(b.hi); const r = m.method === 'de' ? differentialEvolution(b.f, lo, hi, { popSize: m.pop, generations: m.generations, rng: new Rng(m.seed) }) : evolutionStrategy(b.f, m.x0 ?? Array(m.dim).fill((b.lo + b.hi) / 3), { generations: m.generations, rng: new Rng(m.seed), lo, hi }); const okB = r.value < 0.05 * Math.max(1, Math.abs(b.f(lo))); ok = ok && okB; S.push(sec(`${m.method === 'de' ? 'Differential evolution (DE/rand/1/bin)' : '(μ, λ) evolution strategy'} on ${m.benchmark} in ${m.dim}-D (§12.3)`, okB ? 'ok' : 'warn', [`${m.generations} generations${m.method === 'de' ? `, population ${m.pop}, F = 0.8, CR = 0.9` : ', self-adaptive step'}: best f = ${f(r.value, 6)} at (${r.best.map((x) => f(x, 3)).join(', ')}); optimum ${b.optimum}`], { plot: lines('best value', [seriesOf('f', r.history)], 'generation', 'f', { ylog: true }) })); M[`${m.method} ${m.benchmark}`] = Number(f(r.value, 6));
    }
  }
  return ok;
}

export function analyseCa(d: CaDoc, S: ReportSection[], M: Metrics): boolean {
  if (d.wolfram) { const sp = wolframRun(d.wolfram.rule, d.wolfram.width, d.wolfram.steps); const st = wolframStats(sp); S.push(sec(`Elementary cellular automaton, rule ${d.wolfram.rule} (Wolfram, §4.6)`, 'info', [`${d.wolfram.width} cells, ${d.wolfram.steps} steps from a single live cell; ${st.symmetric ? 'left–right symmetric pattern (rule 90: XOR of the neighbours → Sierpiński triangle)' : 'asymmetric, aperiodic pattern (rule 30: chaotic)'}; ${st.distinctRows} distinct rows, final density ${f(st.density[st.density.length - 1], 3)}`], { plot: grid(`rule ${d.wolfram.rule}`, sp, 'binary') })); M['ca symmetric'] = st.symmetric; }
  if (d.life) { const L = d.life; const g0 = Array.from({ length: L.size }, () => Array(L.size).fill(0)); const pat = lifeFromText(L.pattern.join('\n')); pat.forEach((r, i) => r.forEach((v, j) => { if (i < L.size && j < L.size) g0[i][j] = v; })); const life = lifeRun(g0, d.life.steps); S.push(sec(`Game of Life (Conway): ${d.life.steps} steps on a ${d.life.size}×${d.life.size} torus`, 'info', [`population ${life.population[0]} → ${life.population[life.population.length - 1]}; ${life.period ? `the pattern repeats itself after ${life.period} steps shifted by (${life.shift![0]}, ${life.shift![1]}) — a moving configuration that carries a signal through the medium` : 'no translation-periodic repetition detected within the horizon'}`], { plot: grid('initial (left) and final generation', life.grids[0].map((r, i) => [...r, 0, ...life.grids[life.grids.length - 1][i]]), 'binary') })); M['life period'] = life.period ?? 'none'; }
  if (d.pheromone) { const P = d.pheromone; let fld = Array.from({ length: P.size }, () => Array(P.size).fill(0)); for (let k = 0; k < P.steps; k++) { const idx = k % P.path.length; fld = pheromoneStep(fld, [[Math.round(P.path[idx][0]), Math.round(P.path[idx][1])]], P.rho, P.kappa); } const total = fld.flat().reduce((s, v) => s + v, 0); S.push(sec('Stigmergy: a pheromone trail laid by one robot (evaporation + diffusion, §5.5)', 'info', [`${d.pheromone.steps} deposits along a ${d.pheromone.path.length}-cell path, evaporation ρ = ${d.pheromone.rho}, diffusion κ = ${d.pheromone.kappa}; total pheromone ${f(total, 2)} — the trail is a shared memory in the environment that other ants / robots read`], { plot: grid('pheromone field', fld, 'heat') })); }
  return true;
}

export function analyseFuzzy(d: FuzzyDoc, S: ReportSection[], M: Metrics): boolean {
  const ctrl = obstacleController(); if (d.rules.length) ctrl.rules = d.rules; let ok = true;
  const inp = d.input ?? { dL: 2.0, dF: 0.7, dR: 1.6 }; const r = fuzzyInfer(ctrl, inp); const active = r.strengths.map((s, i) => ({ i, s })).filter((a) => a.s > 0);
  S.push(sec(`Mamdani inference for d_L = ${inp.dL}, d_F = ${inp.dF}, d_R = ${inp.dR} (§13.4.2)`, 'ok', [`memberships: ${Object.entries(r.memberships).map(([v, t]) => `${v} {${Object.entries(t).filter(([, m]) => m > 0).map(([n, m]) => `${n} ${f(m, 2)}`).join(', ')}}`).join('; ')}`, `active rules: ${active.map((a) => `#${a.i + 1} (${Object.values(ctrl.rules[a.i].if).join(', ')}) → ${Object.values(ctrl.rules[a.i].then).join(' / ')} at ${f(a.s, 2)}`).join('; ')}`, `centroid defuzzification: v = ${f(r.outputs.v, 3)} of max, ω = ${f(r.outputs.omega, 3)} (positive = left) — a smooth compromise between the rules, not a switch`], { table: { head: ['#', 'd_L', 'd_F', 'd_R', 'v', 'ω', 'strength'], rows: ctrl.rules.map((rl, i) => [i + 1, rl.if.dL, rl.if.dF, rl.if.dR, rl.then.v, rl.then.omega, f(r.strengths[i], 2)]) } }));
  M['v'] = Number(f(r.outputs.v, 3)); M['omega'] = Number(f(r.outputs.omega, 3));
  const sweep = Array.from({ length: 31 }, (_, k) => 0.1 + (2.9 * k) / 30).map((dF) => [dF, fuzzyInfer(ctrl, { dL: 3, dF, dR: 3 }).outputs.v] as [number, number]); S.push(sec('Response surface: speed vs frontal distance (open sides)', 'info', [], { plot: lines('v(d_F)', [{ name: 'v', points: sweep }], 'd_F, m', 'v') }));
  if (d.obstacles.length && d.goal) { const sim = simulateFuzzyAvoidance(d.obstacles, d.goal, { start: d.start }); ok = sim.reachedGoal && sim.minObstacleDistance > 0.3; S.push(sec('Closed loop: fuzzy avoidance blended with go-to-goal', ok ? 'ok' : 'warn', [`${d.obstacles.length} obstacles, goal (${d.goal[0]}, ${d.goal[1]}): ${sim.reachedGoal ? `goal reached in ${sim.steps} steps` : 'goal NOT reached'}; minimum distance to an obstacle ${f(sim.minObstacleDistance, 2)} m`], { plot: paths('Path', [{ name: 'robot', points: sim.path }], { markers: [...d.obstacles.map((o) => ({ x: o[0], y: o[1], kind: 'obstacle' as const })), { x: d.goal[0], y: d.goal[1], kind: 'goal', label: 'goal' }] }) })); M['min obstacle distance'] = Number(f(sim.minObstacleDistance, 2)); }
  return ok;
}

export function analyseResilience(d: ResilienceDoc, S: ReportSection[], M: Metrics): boolean {
  let ok = true;
  if (d.agents.length) { const r = byzantineAgreement(d.agents); const nf = d.agents.filter((a) => a.lies).length; const b = byzantineBound(d.agents.length, nf); ok = ok && r.agreementAmongHonest; S.push(sec(`Byzantine agreement with oral messages, n = ${d.agents.length}, f = ${nf} (§16.8.1–16.8.2)`, r.agreementAmongHonest ? 'ok' : 'error', [`n ≥ 3f + 1 → ${b.tolerable ? 'satisfied' : 'VIOLATED'} (at most ${b.maxFaulty} traitors tolerable); OM(${nf}) sends ${b.messagesOM} messages`, `decisions: ${Object.entries(r.decisions).map(([n, v]) => `${n} → ${v}${d.agents.find((a) => a.name === n)?.lies ? ' (traitor)' : ''}`).join(', ')}; honest agents ${r.agreementAmongHonest ? `agree on "${r.honestDecision}"` : 'DISAGREE'}; ${r.ambiguous} tied evidence votes`], { table: { head: ['receiver', 'about', 'evidence (direct, relays)', 'majority'], rows: Object.entries(r.evidence).flatMap(([t, e]) => Object.entries(e).map(([s, vals]) => [t, s, vals.join(', '), vals.sort().reduce((best, v, _, arr) => (arr.filter((x) => x === v).length > arr.filter((x) => x === best).length ? v : best), vals[0])])) } })); M['byzantine agreement'] = r.agreementAmongHonest; }
  if (d.trust) { const t = d.trust; const A = (TOPOLOGIES[t.graph] ?? TOPOLOGIES.complete)(t.n); const x0 = t.x0 ?? Array.from({ length: t.n }, (_, i) => Number(new Rng(i + 1).uniform(0, 1).toFixed(2))); const liars: Record<number, (k: number) => number> = {}; for (const i of t.liars) liars[i] = (k) => (k % 2 ? t.value : -t.value); const tc = trustConsensus(x0, A, t.eps, t.steps, liars); const normal = [...Array(t.n).keys()].filter((i) => !liars[i]); const last = normal.map((i) => tc.xs[t.steps][i]); const spread = Math.max(...last) - Math.min(...last); const inRange = Math.max(...last) <= Math.max(...normal.map((i) => x0[i])) + 1e-6 && Math.min(...last) >= Math.min(...normal.map((i) => x0[i])) - 1e-6; const okT = spread < 0.05 && inRange; ok = ok && okT; S.push(sec(`Trust / reputation-weighted consensus on a ${t.graph} of ${t.n} (§16.8.4)`, okT ? 'ok' : 'warn', [`liars ${t.liars.map((i) => `r${i + 1}`).join(', ')} alternate ±${t.value}; trust of a neighbour decays when its value is an outlier against the local median and recovers slowly`, `honest agents after ${t.steps} steps: spread ${f(spread, 4)}, ${inRange ? 'inside' : 'OUTSIDE'} the honest initial range; residual trust in the liars ${f(tc.finalTrustOfLiars, 3)}`], { plot: lines('honest states', normal.map((i) => seriesOf(`r${i + 1}`, tc.xs.map((x) => x[i]))), 'k', 'x') })); M['trust in liars'] = Number(f(tc.finalTrustOfLiars, 3)); }
  if (d.degrade) { const g = d.degrade; const A = (TOPOLOGIES[g.graph] ?? TOPOLOGIES.star)(g.n); const rows = degradation(A, g.order); const firstBreak = rows.find((r) => !r.connected); S.push(sec(`Graceful degradation of a ${g.graph} formation of ${g.n} (§16.5.3)`, firstBreak ? 'warn' : 'ok', [`removing robots ${g.order.map((i) => `r${i + 1}`).join(', ')} in turn: ${firstBreak ? `the network splits after ${firstBreak.removed.length} failure(s) (${firstBreak.removed.map((i) => `r${i + 1}`).join(', ')})` : 'the network stays connected throughout'}; λ₂ per step: ${rows.map((r) => f(r.lambda2, 3)).join(' → ')}`, 'a star degrades catastrophically when its hub fails; rings and denser graphs lose λ₂ gradually'], { graph: networkView(A, Array.from({ length: g.n }, (_, i) => `r${i + 1}`)), table: { head: ['removed', 'alive', 'connected', 'λ₂'], rows: rows.map((r) => [r.removed.map((i) => `r${i + 1}`).join(', ') || '—', r.alive, r.connected ? 'yes' : 'no', f(r.lambda2, 3)]) } })); M['links'] = edgeCount(A); M['lambda2'] = Number(f(algebraicConnectivity(A), 3)); }
  if (d.switched) { const s = d.switched; const cl = commonLyapunov(s.modes); const sw = dwellTimeSweep(s.modes, s.tauMin, s.tauMax, 60); S.push(sec(`Switched linear system with ${s.modes.length} stable modes (§13.5.1)`, cl.exists || sw.dwellTime !== null ? 'info' : 'warn', [cl.exists ? `a common quadratic Lyapunov function exists (P = [[${f(cl.P![0][0], 2)}, ${f(cl.P![0][1], 2)}], [${f(cl.P![1][0], 2)}, ${f(cl.P![1][1], 2)}]]): stable under ANY switching` : 'no common quadratic Lyapunov function found on the search grid: stability depends on the switching signal', sw.unstableFor.length ? `periodic switching with dwell τ ≤ ${f(Math.max(...sw.unstableFor), 3)} s makes ‖x‖ grow although each mode is stable; minimum dwell time from the sweep ≈ ${sw.dwellTime === null ? 'not found' : f(sw.dwellTime, 3) + ' s'} — this is why supervisors add hysteresis and minimum-stay timers` : 'every dwell time in the sweep is stable'], { plot: lines('growth of ‖x‖ per switching cycle', [{ name: 'growth factor', points: sw.table.map((r) => [r.tau, Math.min(r.growth, 10)]) }, { name: '1', points: [[s.tauMin, 1], [s.tauMax, 1]], dashed: true }], 'dwell τ, s', 'factor') })); M['common lyapunov'] = cl.exists; M['dwell time'] = sw.dwellTime === null ? 'none' : Number(f(sw.dwellTime, 3)); }
  return ok;
}
