/**
 * Coverage tests for the RoboDK-compatible scripting API (src/api): every public method of RobolinkItem /
 * Robolink is exercised at least once with an assertion on real behaviour, plus the JSON-RPC layer and the
 * browser-side WebSocket bridge against a real `ws` server.
 */
import { describe, it, expect, vi, afterAll } from 'vitest';
import { WebSocketServer, WebSocket as WsClient } from 'ws';
import { Station, SceneObject, Tool, Frame, Target, Camera, ItemType } from '../src/core/items/item';
import { Robot } from '../src/core/items/robot';
import { Program } from '../src/core/items/program';
import * as RL from '../src/api/robolink';
import { executeRpc, executeRpcAsync } from '../src/api/rpc';
import { connectToStudioServer } from '../src/api/ws-client';
import { demos } from '../src/demos';
import { transl, mul, rotx, rotz, DEG, identity } from '../src/core/math/pose';

const { Robolink, RobolinkItem, Mat, robomath } = RL;

function demoCell() {
  const st = demos[0].build();
  const RDK = new Robolink(st);
  const robot = RDK.Item('UR10e', RL.ITEM_TYPE_ROBOT);
  const prog = RDK.Item('PickPlace', RL.ITEM_TYPE_PROGRAM);
  return { st, RDK, robot, prog };
}

describe('robomath Mat', () => {
  it('converts between pose representations and prints rows', () => {
    const m = robomath.transl(100, 200, 300).mul(robomath.rotz(90 * DEG));
    expect(m.Pos()).toEqual([100, 200, 300]);
    expect(m.rows().length).toBe(4);
    expect(m.toString().split('\n').length).toBe(4);
    expect(m.toArray().length).toBe(16);
    const back = m.mul(m.inv());
    expect(back.Pos()[0]).toBeCloseTo(0, 6);
    expect(back.rows()[0][0]).toBeCloseTo(1, 9);
    m.setPos([1, 2, 3]);
    expect(m.Pos()).toEqual([1, 2, 3]);
    const xyzrpw = m.Pose_2_TxyzRxyz();
    expect(xyzrpw.slice(0, 3)).toEqual([1, 2, 3]);
    expect(robomath.TxyzRxyz_2_Pose(xyzrpw).Pos()[2]).toBeCloseTo(3);
    const kuka = m.Pose_2_KUKA();
    expect(robomath.KUKA_2_Pose(kuka).rows()[0][0]).toBeCloseTo(m.rows()[0][0], 6);
    expect(robomath.Pose_2_KUKA(m)).toEqual(kuka);
    expect(robomath.Pose_2_TxyzRxyz(m)).toEqual(xyzrpw);
    const fanuc = m.Pose_2_Fanuc();
    expect(robomath.Fanuc_2_Pose(fanuc).Pos()[1]).toBeCloseTo(2);
    const ur = m.Pose_2_UR();
    expect(ur.length).toBe(6);
    expect(robomath.UR_2_Pose(ur).Pos()[0]).toBeCloseTo(1);
    expect(robomath.Pose_2_UR(m)).toEqual(ur);
    const abb = m.Pose_2_ABB();
    expect(abb.length).toBe(7);
    expect(robomath.ABB_2_Pose(abb).Pos()[2]).toBeCloseTo(3);
    expect(robomath.eye().rows()[3]).toEqual([0, 0, 0, 1]);
    expect(robomath.rotx(0).rows()[1][1]).toBe(1);
    expect(robomath.roty(0).rows()[2][2]).toBe(1);
    expect(RL.transl_(5, 6, 7).Pos()).toEqual([5, 6, 7]);
    expect(Mat.fromRows(m.rows()).toArray()).toEqual(m.toArray());
    expect(robomath.pi).toBe(Math.PI);
  });
});

describe('RobolinkItem: tree, poses, frames, tools', () => {
  it('manipulates the item tree and poses', () => {
    const st = new Station('S');
    const RDK = new Robolink(st);
    const stn = RDK.AddStation('Renamed');
    expect(stn.Name()).toBe('Renamed');
    expect(stn.Type()).toBe(RL.ITEM_TYPE_STATION);
    expect(RDK.ActiveStation().item).toBe(st);
    const folder = RDK.AddFolder('Group');
    expect(folder.Type()).toBe(RL.ITEM_TYPE_FOLDER);
    const frame = RDK.AddFrame('Base frame', folder);
    expect(frame.Parent().item).toBe(folder.item);
    expect(folder.Childs().map((c) => c.Name())).toEqual(['Base frame']);
    frame.setName('World frame');
    expect(frame.Name()).toBe('World frame');
    expect(frame.Visible()).toBe(true);
    frame.setVisible(false);
    expect(frame.Visible()).toBe(false);
    frame.setPose(robomath.transl(100, 0, 0));
    const child = RDK.AddFrame('Child', frame);
    child.setPose(robomath.transl(50, 0, 0));
    expect(child.PoseAbs().Pos()[0]).toBeCloseTo(150);
    child.setParentStatic(stn);
    expect(child.Parent().Type()).toBe(RL.ITEM_TYPE_STATION);
    expect(child.Pose().Pos()[0]).toBeCloseTo(150);
    child.setParent(frame);
    expect(child.Pose().Pos()[0]).toBeCloseTo(150);
    expect(child.PoseAbs().Pos()[0]).toBeCloseTo(250);
    child.setPoseAbs(robomath.transl(300, 0, 0));
    expect(child.Pose().Pos()[0]).toBeCloseTo(200);
    child.setPoseAbs(Array.from(transl(400, 0, 0)));
    expect(child.PoseAbs().Pos()[0]).toBeCloseTo(400);
    child.setPose([[1, 0, 0, 10], [0, 1, 0, 20], [0, 0, 1, 30], [0, 0, 0, 1]]);
    expect(child.Pose().Pos()).toEqual([10, 20, 30]);
    // non-robot / non-tool items report identity tool and frame poses
    expect(child.PoseTool().Pos()).toEqual([0, 0, 0]);
    expect(child.PoseFrame().Pos()).toEqual([0, 0, 0]);
    expect(child.Joints()).toEqual([]);
    expect(child.Type_()).toBe(RL.ITEM_TYPE_FRAME);
    expect(String(child)).toBe('Item(Child)');
    child.Delete();
    expect(child.Valid()).toBe(false);
    expect(child.Name()).toBe('');
    expect(child.Type()).toBe(-1);
    expect(() => child.setName('x')).toThrow(/Invalid item/);
    expect(frame.Childs().length).toBe(0);
    expect(new RobolinkItem(RDK, null).Parent().Valid()).toBe(false);
  });

  it('robot kinematics, tools, frames, limits and IO', () => {
    const st = new Station('S');
    const RDK = new Robolink(st);
    const r = RDK.AddRobot('UR5e');
    const robot = r.item as Robot;
    expect(r.DOF()).toBe(6);
    expect(r.Connect('10.0.0.1')).toBe(true);
    expect(r.ConnectedState()).toBe(RL.ROBOTCOM_READY);
    expect(r.ConnectSafe('192.168.0.5')).toBe(RL.ROBOTCOM_READY);
    expect(r.ConnectionParams()[0]).toBe('192.168.0.5');
    r.setConnectionParams('192.168.0.6', 30002);
    expect(r.ConnectionParams().slice(0, 2)).toEqual(['192.168.0.6', 30002]);
    expect(r.Disconnect()).toBe(r);
    // home & limits
    const home = r.JointsHome();
    expect(home.length).toBe(6);
    r.setJointsHome([1, -91, 89, -89, -91, 1]);
    expect(r.JointsHome()).toEqual([1, -91, 89, -89, -91, 1]);
    const [lo, hi] = r.JointLimits();
    expect(lo.length).toBe(6);
    expect(hi[0]).toBeGreaterThan(lo[0]);
    r.setJointLimits(lo.map(() => -100), hi.map(() => 100));
    expect(r.JointLimits()[1][0]).toBe(100);
    expect(r.MoveJ_Test([0, 0, 0, 0, 0, 0], [150, 0, 0, 0, 0, 0])).toBe(-2);
    r.setJointLimits(lo, hi);
    // tools
    const tool = r.AddTool(robomath.transl(0, 0, 80), 'Gripper');
    expect(tool.Type()).toBe(RL.ITEM_TYPE_TOOL);
    expect(tool.PoseTool().Pos()[2]).toBeCloseTo(80);
    tool.setPoseTool(robomath.transl(0, 0, 90));
    expect(r.PoseTool().Pos()[2]).toBeCloseTo(90);
    r.setPoseTool(robomath.transl(0, 0, 100));
    expect(r.PoseTool().Pos()[2]).toBeCloseTo(100);
    expect(r.getLink(RL.ITEM_TYPE_TOOL).item).toBe(tool.item);
    expect(tool.getLink(RL.ITEM_TYPE_ROBOT).item).toBe(robot);
    expect(r.getLink(RL.ITEM_TYPE_ROBOT).item).toBe(robot);
    // frames
    expect(r.PoseFrame().Pos()).toEqual([0, 0, 0]);
    r.setPoseFrame(robomath.transl(0, 300, 0));
    expect(r.PoseFrame().Pos()[1]).toBeCloseTo(300);
    expect(r.getLink(RL.ITEM_TYPE_FRAME).Type()).toBe(RL.ITEM_TYPE_FRAME);
    const f2 = RDK.AddFrame('F2');
    f2.setPose(robomath.transl(0, 0, 10));
    r.setPoseFrame(f2);
    expect(r.getLink(RL.ITEM_TYPE_FRAME).item).toBe(f2.item);
    // joints, FK/IK
    r.setJoints([0, -90, 90, -90, -90, 0]);
    expect(r.Joints()).toEqual([0, -90, 90, -90, -90, 0]);
    const fk = r.SolveFK(r.Joints());
    const all = r.SolveIK_All(fk);
    expect(all.length).toBeGreaterThan(0);
    expect(all.every((q) => q.length === 6)).toBe(true);
    const cfg = r.JointsConfig(r.Joints());
    expect(cfg.length).toBe(9);
    const [filtered, qf] = r.FilterTarget(fk, r.Joints());
    expect(filtered.Pos()[2]).toBeCloseTo(fk.Pos()[2]);
    expect(qf.length).toBe(6);
    expect(r.FilterProgram()[0]).toBe(0);
    expect(r.SolveIK(robomath.transl(10000, 0, 0))).toEqual([]);
    expect(() => r.setPose(robomath.transl(10000, 0, 0))).toThrow(/not reachable/);
    expect(() => r.MoveJ(robomath.transl(10000, 0, 0))).toThrow(/MoveJ/);
    expect(() => r.MoveL(robomath.transl(10000, 0, 0))).toThrow(/MoveL/);
    const p = r.Pose();
    r.setPose(robomath.transl(0, 0, -20).mul(p));
    expect(r.Pose().Pos()[2]).toBeCloseTo(p.Pos()[2] - 20, 1);
    r.setPose(Array.from(p.m));
    expect(r.Pose().Pos()[2]).toBeCloseTo(p.Pos()[2], 1);
    expect(r.JointPoses([0, 0, 0, 0, 0, 0]).length).toBe(7);
    expect(r.setJointsConfig()).toBe(r);
    // motion params
    r.setSpeed(250, 60, 1000, 200);
    expect(robot.motion.speedLinear).toBe(250);
    expect(robot.motion.speedJoints).toBe(60);
    expect(robot.motion.accelLinear).toBe(1000);
    expect(robot.motion.accelJoints).toBe(200);
    r.setSpeed(-1);
    expect(robot.motion.speedLinear).toBe(250);
    r.setRounding(3);
    expect(robot.motion.rounding).toBe(3);
    r.setZoneData(7);
    expect(robot.motion.rounding).toBe(7);
    r.setAcceleration(1500);
    r.setAccelerationJoints(300);
    r.setSpeedJoints(75);
    expect([robot.motion.accelLinear, robot.motion.accelJoints, robot.motion.speedJoints]).toEqual([1500, 300, 75]);
    // IO on the robot
    r.setDO('gripper', '1');
    r.setDO('lamp', 0);
    r.setAO('speed', 0.5);
    expect(r.getDI('gripper')).toBe(true);
    expect(r.getDI('lamp')).toBe(0);
    expect(r.getDI('missing')).toBe(0);
    expect(r.getAI('speed')).toBe(0.5);
    expect(r.getAI('gripper')).toBe(1);
    expect(r.Busy()).toBe(false);
    r.WaitMove();
    let stopped = false;
    RDK.onStop = () => { stopped = true; };
    r.Stop();
    expect(stopped).toBe(true);
    expect(r.setLink(tool)).toBe(r);
    expect(r.AccuracyActive()).toBe(false);
    r.setAccuracyActive(true);
    expect(r.AccuracyActive()).toBe(true);
    // DH parameters round trip
    const dhm = r.RobotParams();
    expect(dhm.length).toBe(6);
    const q = r.Joints();
    r.setRobotParams(dhm, robomath.transl(0, 0, 5), robomath.transl(0, 0, 10));
    expect(r.DOF()).toBe(6);
    expect(r.Joints()).toEqual(q);
    expect(r.Pose().toArray().every((v) => Number.isFinite(v))).toBe(true);
    expect(RDK.setRobotParams(r, dhm)).toBe(true);
  });
});

describe('RobolinkItem: programs and targets', () => {
  it('records instructions, links, run types and generates code', () => {
    const st = new Station('S');
    const RDK = new Robolink(st);
    const r = RDK.AddRobot('UR5e');
    const tool = r.AddTool(robomath.transl(0, 0, 50), 'T');
    const frame = RDK.AddFrame('F');
    frame.setPose(robomath.transl(300, 0, 0));
    r.setPoseFrame(frame);
    r.setJoints([0, -90, 90, -90, -90, 0]);
    const prog = RDK.AddProgram('P', r);
    expect(prog.Type()).toBe(RL.ITEM_TYPE_PROGRAM);
    prog.setPoseFrame(frame);
    prog.setPoseTool(tool);
    expect(prog.getLink(RL.ITEM_TYPE_FRAME).item).toBe(frame.item);
    expect(prog.getLink(RL.ITEM_TYPE_TOOL).item).toBe(tool.item);
    expect(prog.getLink(RL.ITEM_TYPE_ROBOT).item).toBe(r.item);
    expect(prog.getLink(RL.ITEM_TYPE_OBJECT).Valid()).toBe(false);
    const t1 = r.AddTarget('T1');
    expect(t1.Joints().length).toBe(6);
    expect(t1.isJointTarget()).toBe(false);
    t1.setAsJointTarget();
    expect(t1.isJointTarget()).toBe(true);
    t1.setAsCartesianTarget();
    expect(t1.isJointTarget()).toBe(false);
    t1.setJoints([1, -90, 90, -90, -90, 0]);
    expect(t1.Joints()[0]).toBe(1);
    t1.setLink(r);
    expect((t1.item as Target).robotId).toBe(r.item!.id);
    const f2 = r.AddFrame('F2');
    expect(f2.Parent().item).toBe(r.item);
    const t2 = RDK.AddTarget('T2', frame, r);
    t2.setPose(t1.Pose().mul(robomath.transl(0, 0, 30)));
    const t3 = RDK.AddTarget('T3', frame, r);
    t3.setPose(t1.Pose().mul(robomath.transl(0, 30, 30)));
    prog.setSpeed(100, 50, 500, 100);
    prog.setRounding(2);
    prog.setZoneData(1);
    prog.setAcceleration(400);
    prog.setAccelerationJoints(120);
    prog.setSpeedJoints(40);
    prog.MoveJ(t1);
    prog.MoveL(t2);
    prog.MoveC(t2, t3);
    prog.MoveJ([0, -90, 90, -90, -90, 0]);
    prog.MoveL(t2.Pose());
    prog.addMoveJ(t1);
    prog.addMoveL(t2);
    prog.Pause(100);
    prog.setDO('DO1', 1);
    prog.setDO('DO2', '0');
    prog.setAO('AO1', 3);
    prog.waitDI('DI1', '1', 500);
    prog.RunInstruction('attach');
    prog.RunInstruction('note', RL.INSTRUCTION_COMMENT);
    prog.RunInstruction('hello', RL.INSTRUCTION_SHOW_MESSAGE);
    prog.RunInstruction('x = 1', RL.INSTRUCTION_INSERT_CODE);
    prog.RunInstruction('SubProg');
    prog.RunCodeCustom('Other');
    prog.customInstruction('Custom', '/usr/bin/tool', '', true, 'ROBOT_CMD');
    prog.setValue('cycle', 3);
    expect(prog.Value('cycle')).toBe(3);
    expect(prog.Value()).toMatchObject({ cycle: 3 });
    expect(prog.ShowInstructions()).toBe(prog);
    expect(prog.ShowTargets(false)).toBe(prog);
    const n = prog.InstructionCount();
    expect(n).toBeGreaterThan(20);
    const list = prog.InstructionList();
    expect(list.length).toBe(n);
    const moveIdx = list.findIndex((i) => i.moveType === RL.MOVE_TYPE_JOINT);
    const ins0 = prog.Instruction(moveIdx);
    expect(ins0.pose).not.toBeNull();
    expect(ins0.joints?.length).toBe(6);
    expect(list.some((i) => i.moveType === RL.MOVE_TYPE_LINEAR)).toBe(true);
    expect(list.some((i) => i.moveType === RL.MOVE_TYPE_CIRCULAR)).toBe(true);
    expect(list.filter((i) => i.moveType === 0).length).toBeGreaterThan(5);
    const jointMoveIdx = list.findIndex((i) => i.moveType === RL.MOVE_TYPE_JOINT && i.pose === null);
    expect(jointMoveIdx).toBeGreaterThan(0);
    // setInstruction on a target-based and an inline move
    prog.setInstruction(moveIdx, 'Renamed move', RL.INS_TYPE_MOVE, RL.MOVE_TYPE_LINEAR, true, t1.Pose(), [2, -90, 90, -90, -90, 0]);
    expect(prog.Instruction(moveIdx).name).toBe('Renamed move');
    expect(prog.Instruction(moveIdx).moveType).toBe(RL.MOVE_TYPE_LINEAR);
    expect(prog.Instruction(moveIdx).isJointTarget).toBe(true);
    expect(t1.Joints()[0]).toBe(2);
    prog.setInstruction(jointMoveIdx, 'Inline', RL.INS_TYPE_MOVE, RL.MOVE_TYPE_JOINT, false, robomath.transl(1, 2, 3), [3, -90, 90, -90, -90, 0]);
    expect(prog.Instruction(jointMoveIdx).joints?.[0]).toBe(3);
    expect(prog.setInstruction(999, 'nothing', 0, 0, false, null, null)).toBe(prog);
    prog.InstructionSelect(moveIdx);
    expect(st.selection[0]).toBe((prog.item as Program).instructions()[moveIdx]);
    prog.InstructionSelect();
    expect(st.selection[0]).toBe((prog.item as Program).instructions()[n - 1]);
    prog.InstructionDelete(n - 1);
    expect(prog.InstructionCount()).toBe(n - 1);
    // run type, robot link, run hooks
    expect(prog.RunType()).toBe(RL.PROGRAM_RUN_ON_SIMULATOR);
    prog.setRunType(RL.PROGRAM_RUN_ON_ROBOT);
    expect(prog.RunType()).toBe(RL.PROGRAM_RUN_ON_ROBOT);
    expect(prog.WaitFinished()).toBe(prog);
    const ran: string[] = [];
    RDK.onRunProgram = (p) => ran.push(p.name);
    expect(prog.RunProgram()).toBe(0);
    expect(prog.RunCode()).toBe(0);
    expect(ran).toEqual(['P', 'P']);
    const p2 = RDK.AddProgram('P2');
    p2.setRobot(r);
    p2.setLink(r);
    expect(p2.getLink(RL.ITEM_TYPE_ROBOT).item).toBe(r.item);
    expect(prog.ProgramStart('P3')).toBe(1);
    expect(RDK.Item('P3', RL.ITEM_TYPE_PROGRAM).Valid()).toBe(true);
    const [ok, code, file] = prog.MakeProgram('/tmp/', 'Universal_Robots');
    expect(ok).toBe(true);
    expect(code.length).toBeGreaterThan(10);
    expect(file.startsWith('/tmp/')).toBe(true);
    const [valid, time] = prog.Update();
    expect(valid).toBeGreaterThan(0);
    expect(time).toBeGreaterThan(0);
    const [badMsg, , badStatus] = prog.InstructionListJoints();
    expect(badStatus).toBe(-1); // calls a program that does not exist
    expect(badMsg).not.toBe('Success');
    p2.MoveJ(t1);
    const t4 = r.AddTarget('T4');
    t4.setPose(robomath.transl(0, 0, -10).mul(t1.Pose()));
    p2.MoveL(t4);
    const [msg, rows, status] = p2.InstructionListJoints(1, 1, '', 0, 0, 0.1);
    expect(msg).toBe('Success');
    expect(status).toBe(0);
    expect(rows.length).toBeGreaterThan(0);
    expect(rows[0].length).toBe(8);
    expect(prog.Save().length).toBeGreaterThan(50);
    expect(RDK.Item('', RL.ITEM_TYPE_STATION).Save().length).toBeGreaterThan(100);
    // moving the robot with different target types
    r.MoveJ(t1);
    expect(r.Joints()[0]).toBeCloseTo(2, 3);
    r.MoveL(t2);
    expect(r.Pose().Pos()[2]).toBeCloseTo(t2.Pose().Pos()[2], 0);
    r.MoveJ([0, -90, 90, -90, -90, 0]);
    expect(r.Joints()).toEqual([0, -90, 90, -90, -90, 0]);
    r.MoveC(t2, t3);
    expect(r.Pose().Pos()[1]).toBeCloseTo(t3.Pose().Pos()[1], 0);
  });
});

describe('RobolinkItem: objects, attach/detach, collisions and colours', () => {
  it('works on the pick & place demo cell', () => {
    const { st, RDK, robot, prog } = demoCell();
    const box = RDK.Item('Box 1', RL.ITEM_TYPE_OBJECT);
    const table = RDK.Item('Table top', RL.ITEM_TYPE_OBJECT);
    // colours
    box.setColor([1, 0, 0]);
    expect(box.Color().slice(0, 3)).toEqual([1, 0, 0]);
    box.Recolor('#00ff00');
    expect(box.Color()[1]).toBe(1);
    box.setColorShape([0, 0, 1], 0);
    expect((box.item as SceneObject).geometry[0].color).toBe('#0000ff');
    box.setColorShape('#123456', 99);
    box.setColorCurve([0.5, 0.5, 0.5]);
    expect(box.getParam('curveColor')).toBe('#808080');
    box.setParam('sku', 'A1');
    expect(box.getParam('sku')).toBe('A1');
    // geometry pose
    box.setGeometryPose(robomath.transl(0, 0, 10));
    expect(box.GeometryPose().Pos()[2]).toBe(10);
    const plain = RDK.AddFrame('Plain');
    expect(plain.GeometryPose().Pos()).toEqual([0, 0, 0]);
    expect(plain.setGeometryPose(robomath.transl(1, 1, 1))).toBe(plain);
    // object links & scale with mesh geometry and curves
    expect(RDK.Item('Table', RL.ITEM_TYPE_FRAME).ObjectLink(0).Name()).toBe('Table top');
    expect(box.ObjectLink(5).Valid()).toBe(false);
    const meshObj = RDK.AddCurve([[0, 0, 0], [100, 0, 0]]);
    (meshObj.item as SceneObject).geometry = [{ mesh: 'm1', scale: [1, 1, 1] }, { primitive: { kind: 'sphere', radius: 10 } }, { primitive: { kind: 'cylinder', radius: 5, length: 20 } }];
    meshObj.Scale([2, 3]);
    const g = (meshObj.item as SceneObject).geometry;
    expect(g[0].scale).toEqual([2, 3, 2]);
    expect((g[1].primitive as any).radius).toBe(20);
    expect((g[2].primitive as any).length).toBe(40);
    expect((meshObj.item as SceneObject).curves[0].points[1][0]).toBe(200);
    // attach / detach closest
    robot.MoveJ(RDK.Item('Pick 1'));
    const attached = robot.AttachClosest();
    expect(attached.Name()).toBe('Box 1');
    expect(RDK.events.drain().some((e) => e.type === 'attach')).toBe(true);
    const detached = robot.DetachClosest();
    expect(detached.item).toBe(attached.item);
    expect(detached.Parent().Type()).toBe(RL.ITEM_TYPE_STATION);
    expect(robot.DetachClosest().Valid()).toBe(false);
    const tool = robot.getLink(RL.ITEM_TYPE_TOOL);
    expect(tool.AttachClosest(1).Valid()).toBe(false);
    const again = tool.AttachClosest();
    expect(again.Valid()).toBe(true);
    expect((tool.item as Tool).attached).toContain(again.item!.id);
    const holder = RDK.AddFrame('Holder');
    tool.DetachClosest(holder);
    expect(again.Parent().item).toBe(holder.item);
    expect((tool.item as Tool).attached).toEqual([]);
    tool.AttachClosest();
    robot.MoveJ(RDK.Item('Above 2'));
    expect(tool.AttachClosest().Name()).toBe('Box 2');
    expect(tool.Childs().length).toBe(2);
    expect(tool.DetachClosest().Name()).toBe('Box 1'); // the nearer of the two attached objects (Box 2 hangs 300 mm below)
    expect(tool.Childs().map((c) => c.Name())).toEqual(['Box 2']);
    tool.DetachAll(holder);
    expect(tool.Childs().length).toBe(0);
    // collisions
    expect(box.Collision(new RobolinkItem(RDK, null))).toBe(0);
    expect(box.Collision(table)).toBeGreaterThanOrEqual(0);
    const b2 = RDK.Item('Box 2', RL.ITEM_TYPE_OBJECT);
    b2.setPoseAbs(box.PoseAbs());
    expect(box.Collision(b2)).toBe(1);
    // copy / paste at item level
    box.Copy();
    const pasted = box.Parent().Paste();
    expect(pasted.Valid()).toBe(true);
    expect(pasted.Name()).not.toBe('Box 1');
    // MoveL_Test and SearchL
    robot.MoveJ(RDK.Item('Home'));
    const q0 = robot.Joints();
    const pose = robot.Pose();
    expect(robot.MoveL_Test(q0, pose.mul(robomath.transl(0, 0, -20)))).toBe(0);
    expect(robot.MoveJ_Test(q0, q0.map((v, i) => (i === 5 ? v + 20 : v)))).toBe(0);
    expect(robot.MoveL_Test(q0, robomath.transl(20000, 0, 0))).toBe(-2);
    const contact = robot.SearchL(pose.mul(robomath.transl(0, 0, 5)));
    expect(contact.length).toBe(6);
    robot.setJoints(q0);
    const t = RDK.Item('Above 1');
    const near = robot.SearchL(t);
    expect(near.length).toBe(6);
    robot.setJoints(q0);
    // machining params on a plain item
    const mp = RDK.AddMillingProject('Mill');
    const [, pts] = mp.setMachiningParameters('part.nc', box, 'Step=5');
    expect(pts).toBe(0);
    expect(mp.MachiningParameters()).toMatchObject({ ncfile: 'part.nc', params: 'Step=5', part: box.item!.id });
    void prog; void st;
  });
});

describe('Robolink: station-level API', () => {
  it('items, selection, stations, flags, hooks and misc commands', () => {
    const { st, RDK, robot, prog } = demoCell();
    let rendered = 0;
    RDK.onRender = () => { rendered++; };
    RDK.Render();
    RDK.Update();
    expect(rendered).toBe(2);
    expect(RDK.Item('', RL.ITEM_TYPE_ANY).item).toBe(st);
    expect(RDK.Item('box 2').Name()).toBe('Box 2');
    expect(RDK.Item('nothing-here').Valid()).toBe(false);
    expect(RDK.ItemList(RL.ITEM_TYPE_TARGET).length).toBeGreaterThan(5);
    expect(RDK.ItemUserPick('pick', RL.ITEM_TYPE_ROBOT).item).toBe(robot.item);
    expect(RDK.ItemUserPick().Valid()).toBe(false);
    RDK.setSelection([prog, new RobolinkItem(RDK, null)]);
    expect(RDK.Selection().map((s) => s.Name())).toEqual(['PickPlace']);
    expect(RDK.ItemUserPick('', RL.ITEM_TYPE_PROGRAM).item).toBe(prog.item);
    expect(RDK.ItemUserPick().item).toBe(prog.item);
    // mobile robot, folders, files, points, shapes
    const amr = RDK.AddMobileRobot('AMR');
    expect(amr.Type()).toBe(ItemType.MOBILE_ROBOT);
    const msgs: Array<[string, boolean]> = [];
    RDK.onMessage = (m, p) => msgs.push([m, p]);
    expect(RDK.AddFile('/tmp/x.step').Valid()).toBe(false);
    RDK.ShowMessage('hello', false);
    RDK.RunMessage('comment', true);
    RDK.RunMessage('display');
    expect(RDK.RunCode('PickPlace', true)).toBe(0);
    expect(RDK.RunCode('free text')).toBe(0);
    expect(msgs.map((m) => m[0])).toEqual(['AddFile: drop the file onto the viewport or use File > Import', 'hello', 'display', 'free text']);
    const ran: string[] = [];
    RDK.onRunProgram = (p) => ran.push(p.name);
    expect(RDK.RunProgram('PickPlace()')).toBe(0);
    expect(RDK.RunProgram('Missing')).toBe(-1);
    expect(ran).toEqual(['PickPlace']);
    const pts = RDK.AddPoints([[0, 0, 0], [1, 1, 1]]);
    expect((pts.item as SceneObject).points.length).toBe(2);
    RDK.AddPoints([[2, 2, 2]], pts);
    expect((pts.item as SceneObject).points.length).toBe(3);
    const holder = RDK.AddFolder('Curves');
    const curve = RDK.AddCurve([[0, 0, 0], [10, 0, 0]], holder);
    expect(curve.Parent().item).toBe(holder.item);
    RDK.AddCurve([[0, 0, 0], [0, 10, 0]], curve);
    expect((curve.item as SceneObject).curves.length).toBe(2);
    const registered: string[] = [];
    RDK.assetsRegister = (id) => registered.push(id);
    const shape = RDK.AddShape([[0, 0, 0, 10, 0, 0, 0, 10, 0]], holder, 'Tri');
    expect(registered.length).toBe(1);
    expect(shape.Name()).toBe('Tri');
    // merge objects with curves; empty merge is invalid
    const merged = RDK.MergeItems([curve, shape]);
    expect((merged.item as SceneObject).curves.length).toBe(2);
    expect((merged.item as SceneObject).geometry.length).toBe(1);
    expect(RDK.MergeItems([holder]).Valid()).toBe(false);
    // duplicate / clipboard
    const dup = RDK.Duplicate(RDK.Item('Box 3', RL.ITEM_TYPE_OBJECT));
    expect(dup.Valid()).toBe(true);
    expect(RDK.Duplicate(new RobolinkItem(RDK, null)).Valid()).toBe(false);
    RDK.Copy(RDK.Item('Box 3', RL.ITEM_TYPE_OBJECT));
    const many = RDK.Paste(holder, 2) as RL.RobolinkItem[];
    expect(many.length).toBe(2);
    expect(many.every((m) => m.Parent().item === holder.item)).toBe(true);
    // joints / poses in bulk
    const all = RDK.Joints();
    expect(all.length).toBe(1);
    expect(all[0].length).toBe(6);
    RDK.setJoints([robot], [[0, -100, 110, -100, -90, 5]]);
    expect(robot.Joints()[5]).toBe(5);
    const f = RDK.AddFrame('Bulk');
    RDK.setPoses([f], [robomath.transl(1, 2, 3)]);
    expect(f.Pose().Pos()).toEqual([1, 2, 3]);
    RDK.ShowSequence([[0, -100, 110, -100, -90, 10]]);
    expect(robot.Joints()[5]).toBe(10);
    let shown: number[][] = [];
    RDK.onShowSequence = (_r, rows) => { shown = rows; };
    RDK.ShowSequence([[1, 2, 3, 4, 5, 6]]);
    expect(shown.length).toBe(1);
    const [fp, fq] = RDK.FilterTarget(robot.Pose(), robot.Joints());
    expect(fp.Pos().length).toBe(3);
    expect(fq.length).toBe(6);
    // params, settings, commands, version
    RDK.setParam('site', 'lab');
    expect(RDK.getParam('site')).toBe('lab');
    expect(RDK.getParam('units')).toBe('mm');
    expect(RDK.getParams().some(([k]) => k === 'site')).toBe(true);
    expect(RDK.Command('Trace', 'On')).toBe('OK');
    expect(st.getParam('cmd:Trace')).toBe('On');
    expect(RDK.Version()).toMatch(/RoboDK API compatible/);
    expect(RDK.License()[1]).toBe('MIT');
    expect(RDK.Save('x.rdk').length).toBeGreaterThan(100);
    expect(RDK.Save('x.rdk', f)).toContain('Bulk');
    RDK.setRunMode(RL.RUNMODE_RUN_ROBOT);
    expect(RDK.RunMode()).toBe(RL.RUNMODE_RUN_ROBOT);
    RDK.setSimulationSpeed(5);
    expect(RDK.SimulationSpeed()).toBe(1);
    RDK.setSimulationTime(12);
    expect(RDK.SimulationTime()).toBe(12);
    expect(st.simTime).toBe(12);
    let t = 3;
    RDK.simTime = { get: () => t, set: (v) => { t = v; } };
    RDK.setSimulationTime(4);
    expect(RDK.SimulationTime()).toBe(4);
    RDK.Finish();
    RDK.Disconnect();
    expect(RDK.Connect()).toBe(true);
    // flags / window / view / stations hooks
    expect(RDK.getFlagsRoboDK()).toBe(RL.FLAG_ROBODK_ALL);
    const win: Array<[string, any]> = [];
    RDK.onWindow = (c, v) => win.push([c, v]);
    expect(RDK.setFlagsRoboDK(RL.FLAG_ROBODK_TREE_ACTIVE)).toBe(RL.FLAG_ROBODK_TREE_ACTIVE);
    expect(RDK.getFlagsRoboDK()).toBe(RL.FLAG_ROBODK_TREE_ACTIVE);
    RDK.HideRoboDK(); RDK.ShowRoboDK(); RDK.setWindowState(RL.WINDOWSTATE_MAXIMIZED); RDK.CloseRoboDK();
    expect(win.map((w) => w[0])).toEqual(['flags', 'hide', 'show', 'state', 'close']);
    expect(RDK.getFlagsItem(new RobolinkItem(RDK, null))).toBe(RL.FLAG_ITEM_ALL);
    expect(RDK.setFlagsItem(new RobolinkItem(RDK, null), 3)).toBe(3);
    let mode = -1;
    RDK.onInteractiveMode = (m) => { mode = m; };
    RDK.setInteractiveMode(RL.SELECT_ROTATE);
    expect(mode).toBe(RL.SELECT_ROTATE);
    expect(RDK.ViewPose().Pos()).toEqual([0, 0, 0]);
    let view = identity();
    RDK.onViewPose = { get: () => view, set: (m) => { view = m; } };
    RDK.setViewPose(robomath.transl(0, 0, 500));
    expect(RDK.ViewPose().Pos()[2]).toBe(500);
    RDK.setViewPose(Array.from(transl(0, 0, 250)));
    expect(RDK.ViewPose().Pos()[2]).toBe(250);
    const other = new Station('Other');
    const stations = [st, other];
    const calls: string[] = [];
    RDK.onStations = { list: () => stations, setActive: (s) => calls.push(`active:${s.name}`), add: (n) => new Station(n), close: () => calls.push('close') };
    expect(RDK.getOpenStations().length).toBe(2);
    RDK.setActiveStation(new RobolinkItem(RDK, other));
    expect(RDK.station).toBe(other);
    RDK.setActiveStation(f);
    expect(RDK.station).toBe(other);
    RDK.CloseStation();
    expect(calls).toEqual(['active:Other', 'close']);
    RDK.onStations = null;
    RDK.CloseStation();
    expect(RDK.station.name).toBe('New station');
    expect(RDK.getOpenStations()[0].item).toBe(RDK.station);
  });

  it('cameras, calibration helpers, collisions, spray, events and plugins', async () => {
    const { st, RDK, robot } = demoCell();
    // cameras
    const cam = RDK.Cam2D_Add(robot, 'FOV=45 SIZE=320x240 FAR_LENGTH=5000 NEAR_LENGTH=5 DEPTH');
    const c = cam.item as Camera;
    expect(cam.Parent().item).toBe(robot.item);
    expect([c.fov, c.width, c.height, c.far, c.near, c.kind]).toEqual([45, 320, 240, 5000, 5, 'depth']);
    expect(RDK.Cam2D_SetParams('FOV=30 FAR=4000 NEAR=1')).toBe(true);
    expect([c.fov, c.far, c.near]).toEqual([30, 4000, 1]);
    expect(RDK.Cam2D_SetParams('FOV=20', cam)).toBe(true);
    expect(c.fov).toBe(20);
    expect(RDK.Cam2D_Snapshot()).toBe('');
    RDK.onSnapshot = (item, w, h) => `png:${item.name}:${w}x${h}`;
    expect(RDK.Cam2D_Snapshot('', cam)).toBe('png:Camera:320x240');
    expect(RDK.Cam2D_Snapshot()).toBe('png:Camera:320x240');
    expect(RDK.Cam2D_Close(cam)).toBe(true);
    expect(cam.Valid()).toBe(false);
    expect(RDK.Cam2D_SetParams('FOV=10')).toBe(false);
    expect(RDK.Cam2D_Snapshot()).toBe('');
    const cam2 = RDK.Cam2D_Add(new RobolinkItem(RDK, null));
    expect(cam2.Parent().item).toBe(st);
    expect(RDK.Cam2D_Close()).toBe(true);
    expect(cam2.Valid()).toBe(false);
    // measurement helpers
    const xyz = RDK.LaserTracker_Measure();
    expect(xyz.length).toBe(3);
    const tcp = robot.PoseAbs().Pos();
    expect(Math.hypot(xyz[0] - tcp[0], xyz[1] - tcp[1], xyz[2] - tcp[2])).toBeLessThan(5);
    const [mp, ok] = RDK.MeasurePose();
    expect(ok).toBe(1);
    expect(Math.abs(mp.Pos()[2] - tcp[2])).toBeLessThan(5);
    expect(RDK.StereoCamera_Measure()[1]).toBe(1);
    const q = robot.Joints();
    const ref = RDK.Calibrate_Reference([q, q.map((v, i) => (i === 0 ? v + 10 : v)), q.map((v, i) => (i === 1 ? v + 10 : v))], RL.CALIBRATE_FRAME_3P_P1_ORIGIN, true, robot);
    expect(ref.Pos().every((v) => Number.isFinite(v))).toBe(true);
    const flange = (robot.item as Robot).solveFKFlange(q);
    const kuka = [flange[12], flange[13], flange[14], 0, 0, 0];
    const [tcpXyz, stats] = RDK.CalibrateTool([kuka, kuka, kuka, kuka, kuka], 0, RL.CALIBRATE_TCP_BY_LINE);
    expect(tcpXyz.length).toBe(3);
    expect(stats.length).toBeGreaterThanOrEqual(2);
    expect(RDK.BallbarProgram(robot, [800, 0, 600], 150).Valid()).toBe(true);
    const empty = new Robolink(new Station('E'));
    expect(empty.BallbarProgram().Valid()).toBe(false);
    expect(empty.Popup_ISO9283_CubeProgram().Valid()).toBe(false);
    expect(() => empty.Calibrate_Robot([[0, 0, 0, 0, 0, 0, 1, 2, 3]])).toThrow(/No robot/);
    expect(empty.LaserTracker_Measure([1, 2, 3])).toEqual([1, 2, 3]);
    expect(empty.MeasurePose()[1]).toBe(-1);
    expect(empty.Joints()).toEqual([]);
    empty.ShowSequence([[1, 2, 3]]);
    // collisions
    const box = RDK.Item('Box 1', RL.ITEM_TYPE_OBJECT), b2 = RDK.Item('Box 2', RL.ITEM_TYPE_OBJECT);
    expect(RDK.Collision_SetPairList([box, b2], [b2, box], [], [], [true, false])).toBe(2);
    expect(RDK.Collision_SetPairList([box], [new RobolinkItem(RDK, null)])).toBe(0);
    expect(RDK.setCollisionActivePair(RL.COLLISION_ON, box, b2)).toBe(true);
    expect(RDK.Collision_SetPair(box, new RobolinkItem(RDK, null))).toBe(false);
    b2.setPose(box.Pose());
    expect(RDK.Collisions()).toBeGreaterThan(0);
    expect(RDK.CollisionItems().length).toBeGreaterThanOrEqual(2);
    const pairs = RDK.CollisionPairs();
    expect(pairs.length).toBeGreaterThan(0);
    expect(pairs[0].length).toBe(4);
    const [hit, item, point] = RDK.Collision_Line([100, 150, 2000], [100, 150, -100], robomath.transl(700, -300, 0));
    expect(hit).toBe(true);
    expect(item.Valid()).toBe(true);
    expect(point[2]).toBeGreaterThan(400);
    const projected = RDK.ProjectPoints([[800, -150, 2000, 7], [5000, 5000, 100]]);
    expect(projected[0][2]).toBeGreaterThan(400);
    expect(projected[0][2]).toBeLessThan(1000);
    expect(projected[0][3]).toBe(7);
    expect(projected[1]).toEqual([5000, 5000, 100]);
    expect(RDK.ProjectPoints([[800, -150, 2000]], RDK.AddFrame('nobody'))[0][2]).toBe(2000);
    // inside test with plain boxes
    const inner = RDK.AddShape([[0, 0, 0, 1, 0, 0, 0, 1, 0]]);
    (inner.item as SceneObject).geometry = [{ primitive: { kind: 'box', size: [50, 50, 50] } }];
    const outer = RDK.AddShape([[0, 0, 0, 1, 0, 0, 0, 1, 0]]);
    (outer.item as SceneObject).geometry = [{ primitive: { kind: 'box', size: [1000, 1000, 1000] } }];
    inner.setPose(robomath.transl(5000, 5000, 100));
    outer.setPose(robomath.transl(5000, 5000, 0));
    expect(RDK.IsInside(inner, outer)).toBe(1);
    inner.setPose(robomath.transl(9000, 9000, 100));
    expect(RDK.IsInside(inner, outer)).toBe(0);
    expect(RDK.IsInside(inner, new RobolinkItem(RDK, null))).toBe(0);
    expect(RDK.IsInside(RDK.AddFrame('nocollider'), outer)).toBe(0);
    // spray with the 'all' and -1 selectors
    const tool = robot.getLink(RL.ITEM_TYPE_TOOL);
    const gid = RDK.Spray_Add(tool, box, 'ANGLE=20 RANGE=300');
    expect(gid).toBeGreaterThan(0);
    expect(RDK.Spray_Add(new RobolinkItem(RDK, null), new RobolinkItem(RDK, null))).toBeGreaterThan(0);
    expect(RDK.Spray_SetState(1, -1)).toBe(1);
    expect(RDK.Spray_GetStats(-1)[1].length).toBe(6);
    expect(RDK.Spray_Clear(-1)).toBe(1);
    expect(empty.Spray_Add()).toBe(-1);
    // events & plugins
    expect(RDK.EventsLoop()).toBe(false);
    RDK.EventsListen();
    expect(RDK.EventsLoop()).toBe(true);
    expect(await RDK.WaitForEvent(0.01)).toBeNull();
    RDK.events.push({ type: 'renamed', itemId: box.item!.id });
    RDK.events.push({ type: 'unknown' });
    const ev = await RDK.WaitForEvent(1);
    expect(ev?.[0]).toBe(RL.EVENT_ITEM_RENAMED);
    expect(ev?.[1].item).toBe(box.item);
    const ev2 = await RDK.WaitForEvent(1);
    expect(ev2?.[0]).toBe(RL.EVENT_ITEM_CHANGED);
    expect(ev2?.[1].Valid()).toBe(false);
    let unloaded = false;
    RDK.registerPlugin('p1', { command: (c) => c.toUpperCase(), unload: () => { unloaded = true; } });
    expect(RDK.Plugins()).toEqual(['p1']);
    expect(RDK.PluginCommand('p1', 'go')).toBe('GO');
    expect(RDK.PluginCommand('nope')).toMatch(/not loaded/);
    expect(RDK.PluginLoad('other')).toBe(false);
    RDK.onPluginLoad = (n) => n === 'other';
    expect(RDK.PluginLoad('other')).toBe(true);
    expect(RDK.PluginLoad('p1', 0)).toBe(true);
    expect(unloaded).toBe(true);
    expect(RDK.Plugins()).toEqual([]);
    RDK.Delete([box, new RobolinkItem(RDK, null)]);
    expect(box.Valid()).toBe(false);
  });

  it('generates NC machining programs from curves with a kind', () => {
    const st = new Station('NC');
    const RDK = new Robolink(st);
    const r = RDK.AddRobot('UR5e');
    r.AddTool(robomath.transl(0, 0, 60), 'Spindle');
    const part = RDK.AddCurve([[0, 0, 0], [40, 0, 0], [40, 40, 0]]);
    (part.item as SceneObject).curves = [{ name: 'rapid', points: [[0, 0, 20], [0, 0, 0]], kind: 'rapid' } as any, { name: 'cut', points: [[0, 0, 0], [40, 0, 0], [40, 40, 0]], kind: 'cut' } as any];
    part.setPose(robomath.transl(400, 0, 250).mul(robomath.rotx(180 * DEG)));
    const proj = RDK.AddMachiningProject('Mill', r);
    const [, points, unreachable] = proj.setMachiningParameters('part.nc', part, 'Approach=20 Speed=15 SpindleIO=Spindle RotZ=0 Rounding=2');
    expect(points).toBeGreaterThan(0);
    expect(unreachable).toBe(0);
    expect(proj.getParam('machiningStats')).toMatchObject({ cutLength: expect.any(Number) });
    const pid = String(proj.getParam('programId'));
    expect(st.findById(pid)).toBeInstanceOf(Program);
    // regenerating replaces the previous program
    proj.setMachiningParameters('part.nc', part, 'Approach=20 Normal');
    expect(st.findById(pid)).toBeNull();
    expect(RDK.updateMachining(proj.item!)).not.toBeNull();
    expect(RDK.updateMachining(RDK.AddMillingProject('Empty').item!)).toBeNull();
  });
});

describe('JSON-RPC layer', () => {
  it('decodes items / poses, awaits promises and routes app calls', async () => {
    const { RDK, robot } = demoCell();
    const id = robot.item!.id;
    const r1 = executeRpc(RDK, { id: 1, method: 'Pose', target: id });
    const rows = r1.result.$pose;
    const r2 = executeRpc(RDK, { id: 2, method: 'setPose', target: id, params: [rows] });
    expect(r2.error).toBeUndefined();
    const r3 = executeRpc(RDK, { id: 3, method: 'setPose', target: id, params: [{ $pose: robot.Pose().toArray() }] });
    expect(r3.error).toBeUndefined();
    const r4 = executeRpc(RDK, { id: 4, method: 'setPoseFrame', target: id, params: [{ $item: null }] });
    expect(r4.error).toBeUndefined();
    const r5 = executeRpc(RDK, { id: 5, method: 'Name', target: 'does-not-exist' });
    expect(r5.result).toBe('');
    const r6 = executeRpc(RDK, { id: 6, method: 'setName', target: 'does-not-exist', params: ['x'] });
    expect(r6.error).toMatch(/Invalid item/);
    const r7 = executeRpc(RDK, { id: 7, method: 'JointLimits', target: id });
    expect(r7.result.length).toBe(2);
    const r8 = executeRpc(RDK, { id: 8, method: 'MachiningParameters', target: id });
    expect(r8.result).toMatchObject({ ncfile: undefined });
    const r9 = executeRpc(RDK, { id: 9, method: 'Calibrate_Reference', params: [[[0, 0, 0], [1, 0, 0], [0, 1, 0]]] });
    expect(r9.result.$pose.length).toBe(4);
    const r10 = executeRpc(RDK, { id: 10, method: 'Selection' });
    expect(Array.isArray(r10.result)).toBe(true);
    const r11 = executeRpc(RDK, { id: 11, method: 'CollisionPairs' });
    expect(Array.isArray(r11.result)).toBe(true);
    // promises
    const pending = executeRpc(RDK, { id: 12, method: 'WaitForEvent', params: [0.01] });
    expect(typeof pending.result.then).toBe('function');
    const a1 = await executeRpcAsync(RDK, { id: 13, method: 'WaitForEvent', params: [0.01] });
    expect(a1).toEqual({ id: 13, result: null });
    RDK.events.push({ type: 'moved', itemId: id });
    const a2 = await executeRpcAsync(RDK, { id: 14, method: 'WaitForEvent', params: [1] });
    expect(a2.result[0]).toBe(RL.EVENT_ITEM_MOVED);
    expect(a2.result[1].$item).toBe(id);
    const a3 = await executeRpcAsync(RDK, { id: 15, method: 'Name', target: id });
    expect(a3.result).toBe('UR10e');
    // app routing
    const app = { ctl: { value: 42, add: (a: number, b: number) => a + b, fail: async () => { throw new Error('boom'); }, pose: () => robot.Pose() } };
    expect(executeRpc(RDK, { id: 16, method: '__app__', params: ['ctl.value'] }, { app }).result).toBe(42);
    expect(executeRpc(RDK, { id: 17, method: '__app__', params: ['ctl.add', 2, 3] }, { app }).result).toBe(5);
    expect(executeRpc(RDK, { id: 18, method: '__app__', params: ['ctl.pose'] }, { app }).result.$pose.length).toBe(4);
    const a4 = await executeRpcAsync(RDK, { id: 19, method: '__app__', params: ['ctl.fail'] }, { app });
    expect(a4.error).toBe('boom');
    expect(executeRpc(RDK, { id: 20, method: '__app__', params: ['ctl.value'] }).error).toMatch(/Unknown method/);
  });
});

describe('studio server WebSocket bridge (browser side)', () => {
  const servers: WebSocketServer[] = [];
  afterAll(async () => { for (const s of servers) await new Promise<void>((r) => { for (const c of s.clients) c.terminate(); s.close(() => r()); }); });

  function makeApp(st: Station) {
    return { station: st, log: vi.fn(), snapshot: vi.fn(), previewProgram: vi.fn() } as any;
  }

  it('registers as host, answers RPC requests and refreshes the app after mutating calls', async () => {
    const { st, RDK, robot } = demoCell();
    const app = makeApp(st);
    const wss = new WebSocketServer({ port: 0, host: '127.0.0.1' });
    servers.push(wss);
    await new Promise<void>((r) => wss.on('listening', () => r()));
    const port = (wss.address() as any).port;
    const received: any[] = [];
    let socket: WsClient | null = null;
    const gotSocket = new Promise<WsClient>((resolve) => wss.on('connection', (s) => { socket = s; s.on('message', (d) => received.push(JSON.parse(d.toString()))); resolve(s); }));
    await connectToStudioServer(app, RDK, `ws://127.0.0.1:${port}`);
    const s = await gotSocket;
    const until = async (cond: () => boolean) => { const t0 = Date.now(); while (!cond()) { if (Date.now() - t0 > 5000) throw new Error('timeout'); await new Promise((r) => setTimeout(r, 10)); } };
    await until(() => received.length >= 1);
    expect(received[0]).toEqual({ role: 'host', name: 'browser' });
    expect(app.log).toHaveBeenCalledWith(expect.stringContaining('Connected to studio server'));
    s.send('this is not json');
    s.send(JSON.stringify({ hello: 'no method' }));
    s.send(JSON.stringify({ id: 1, method: 'Item', params: ['UR10e', RL.ITEM_TYPE_ROBOT] }));
    await until(() => received.length >= 2);
    expect(received[1]).toMatchObject({ id: 1, result: { $item: robot.item!.id, name: 'UR10e' } });
    expect(app.snapshot).not.toHaveBeenCalled();
    s.send(JSON.stringify({ id: 2, method: 'setJoints', target: robot.item!.id, params: [[0, -100, 110, -100, -90, 33]] }));
    await until(() => received.length >= 3);
    expect(received[2]).toMatchObject({ id: 2 });
    expect(robot.Joints()[5]).toBe(33);
    await until(() => app.snapshot.mock.calls.length >= 1);
    expect(app.previewProgram).toHaveBeenCalled();
    s.send(JSON.stringify({ id: 3, method: 'WaitForEvent', params: [0.01] }));
    await until(() => received.length >= 4);
    expect(received[3]).toEqual({ id: 3, result: null });
    s.close();
    await until(() => app.log.mock.calls.some((c: any[]) => c[0] === 'Studio server disconnected'));
    void socket;
  });

  it('rejects when the server is unreachable and ignores invalid URLs', async () => {
    const st = new Station('x');
    const RDK = new Robolink(st);
    const app = makeApp(st);
    await expect(connectToStudioServer(app, RDK, 'ws://127.0.0.1:1')).rejects.toThrow(/ws error/);
    await expect(connectToStudioServer(app, RDK, 'not a url')).resolves.toBeUndefined();
    expect(app.log).not.toHaveBeenCalled();
  });
});

void Frame; void mul; void rotz;
