import { describe, it, expect } from 'vitest';
import { parseConsensus, parseSwarm, parseAllocation, parseGridMapf, parseCoverage, parseEstimation, parseSafety, parseWarehouse, parseGame, parseMarl, parseEvo, parseCa, parseFuzzy, parseResilience, parseMission, MRS_TEMPLATES, MRS_PARSERS, detectMrsKind } from '../src/mrs/dsl';
import { MRS_KINDS } from '../src/mrs/model';
import { analyse } from '../src/ctl/analysis';

describe('group-control DSL — parsers', () => {
  it('every kind has a parser and a template that the parser accepts; detection reads the first keyword', () => {
    for (const k of MRS_KINDS) { expect(typeof MRS_PARSERS[k.kind]).toBe('function'); expect(() => MRS_PARSERS[k.kind](MRS_TEMPLATES[k.kind])).not.toThrow(); expect(detectMrsKind(MRS_TEMPLATES[k.kind])).toBe(k.kind); }
    expect(detectMrsKind('des something')).toBeNull(); expect(() => parseConsensus('swarm x')).toThrow(/must start with "consensus/);
  });
  it('consensus: graph types, robots, options and errors', () => {
    const d = parseConsensus('consensus c\ngraph edges\nedge 1 2\nedge 2 3 0.5\nx0 1 2 3\neps 0.2\nsteps 5\nwmsr F=1 malicious=3 pattern=constant\nevent sigma=0.2\ntransport target=1,1 kp=2\ncomm radius=2 drop=0.1\nfail 2 at=3');
    expect(d.graph.type).toBe('edges'); expect(d.graph.n).toBe(3); expect(d.graph.edges).toEqual([[0, 1, 1], [1, 2, 0.5]]); expect(d.wmsr!.malicious).toEqual([2]); expect(d.event!.sigma).toBe(0.2); expect(d.transport!.kp).toBe(2); expect(d.comm).toEqual({ radius: 2, drop: 0.1 }); expect(d.failures).toEqual([{ robot: 1, at: 3 }]); expect(d.robots.map((r) => r.name)).toEqual(['r1', 'r2', 'r3']);
    const disk = parseConsensus('consensus d\nrobot a at=0,0\nrobot b at=1,0\ngraph disk radius=1.5'); expect(disk.graph.type).toBe('disk'); expect(disk.robots[1].at).toEqual([1, 0]);
    expect(() => parseConsensus('consensus e\ngraph hexagon n=3')).toThrow(/unknown graph type/); expect(() => parseConsensus('consensus e\nedge a b')).toThrow(/1-based/); expect(() => parseConsensus('consensus e\nrobots 0')).toThrow(/robots <n>/);
  });
  it('swarm / allocation / gridmapf / coverage / estimation options and errors', () => {
    const s = parseSwarm('swarm s\nmodel vicsek n=50 eta=0.5,2\ndistractor at=1,1 amp=0.2'); expect(s.model).toBe('vicsek'); expect(s.n).toBe(50); expect(s.etas).toEqual([0.5, 2]); expect(s.distractors[0][2]).toBe(0.2);
    expect(() => parseSwarm('swarm s\nmodel ants')).toThrow(/unknown swarm model/); expect(() => parseSwarm('swarm s\nfoo')).toThrow(/unknown swarm line/);
    const a = parseAllocation('allocation a\nrobot r at=0,0\ntask t at=1,1 reward=5 value=9\nmethods greedy\ncbba capacity=2 lambda=0.9 graph=path'); expect(a.tasks[0].reward).toBe(5); expect(a.cbba).toMatchObject({ capacity: 2, lam: 0.9, graph: 'path' }); expect(() => parseAllocation('allocation a\nmethods ssi')).toThrow(/robot \/ task lines/);
    const g = parseGridMapf('gridmapf g\nmap cell=0.5\n  ...\n  .#.\nend\nrandom agents=2 seed=3\nexecute delay=0.1'); expect(g.cellSize).toBe(0.5); expect(g.map).toEqual(['...', '.#.']); expect(g.random).toEqual({ agents: 2, seed: 3 }); expect(g.execute).toEqual({ delay: 0.1, runs: 5, seed: 12 });
    expect(() => parseGridMapf('gridmapf g\nagent a start=0,0 goal=0,1')).toThrow(/map block/); expect(() => parseGridMapf('gridmapf g\nmap\n  ...\n  ..\nend\nagent a start=0,0 goal=0,1')).toThrow(/same length/);
    const c = parseCoverage('coverage c\narea 0 2 0 2 res=0.5\ndensity uniform\nrobot r1 at=1,1\nrobots 3 seed=2\nrange 0.5'); expect(c.density.kind).toBe('uniform'); expect(c.n).toBe(3); expect(c.robots.length).toBe(3); expect(c.range).toBe(0.5); expect(() => parseCoverage('coverage c\narea 0 2')).toThrow(/area xmin/);
    const e = parseEstimation('estimation e\ntarget 1,2\nrobots 5 graph=ring\nnoise 0.1\nci a=0,0 A=1,1 b=1,1 B=2,2'); expect(e.graph).toBe('ring'); expect(e.noise).toEqual([0.1, 0.1]); expect(e.ci!.B).toEqual([2, 2]);
  });
  it('safety / warehouse / game / marl / evo / ca / fuzzy / resilience options and errors', () => {
    const sf = parseSafety('safety s\nrobot a at=0,0 goal=1,0 speed=0.1\nparams d_safe=0.3 compare=false\nunstuck angle=-30 hold=10\nstale lag=5\nuncooperative 1'); expect(sf.scenario).toBe('custom'); expect(sf.robots[0].speed).toBe(0.1); expect(sf.unstuck!.angle).toBeCloseTo(-Math.PI / 6, 9); expect(sf.compareNominal).toBe(false); expect(sf.uncooperative).toEqual([0]); expect(() => parseSafety('safety s\nscenario ring')).toThrow(/unknown scenario/);
    const w = parseWarehouse('warehouse w\ncell 1\nmap\n  ....\n  #..#\nend\nstation A 0,0 kind=pickup\nstation B 0,3 kind=drop\nstation H 1,1 kind=home\nrobots r1 homes=H speed=1\norders rate=0 first=2 pickups=A drops=B\norder o9 A B at=5\nfault r1 at=3 kind=mute\nduration 30 dt=0.5 seed=7'); expect(w.cfg.warehouse.cell).toBe(1); expect(w.cfg.warehouse.stations).toEqual({ A: [0, 0], B: [0, 3], H: [1, 1] }); expect(w.stationKinds).toEqual({ A: 'pickup', B: 'drop', H: 'home' }); expect(w.cfg.orders.fixed![0]).toMatchObject({ id: 'o9', at: 5 }); expect(w.cfg.faults[0].kind).toBe('mute'); expect(w.cfg.duration).toBe(30);
    expect(() => parseWarehouse('warehouse w\nmap\n  ..\nend')).toThrow(/custom map needs station/); expect(() => parseWarehouse('warehouse w\nfault r1 at=1 kind=explode')).toThrow(/stop\|mute\|recover/); expect(() => parseWarehouse('warehouse w\nstation Z 1,1\nrobots r1 homes=Z\norders rate=0 first=0')).toThrow(/no orders/);
    const g = parseGame('game g\nstrategies a b ; c d\npayoff a c 1 2\npayoff a d 3 4\npayoff b c 5 6\npayoff b d 7 8\nstart b d\ncoalition A=1 B=2 AB=5'); expect(g.game!.u[1][1]).toEqual([7, 8]); expect(g.start).toEqual([1, 1]); expect(g.coalition).toEqual({ v: { '0': 1, '1': 2, '0,1': 5 }, n: 2, names: ['A', 'B'] }); expect(() => parseGame('game g\nstrategies a b ; c\npayoff a c 1 1')).toThrow(/missing payoff/);
    const m = parseMarl('marl m\nmap\n  S.#\n  ..G\nend\nparams alpha=0.2 method=sarsa path=right\nagents 2 starts=0,0;1,2 goals=1,2;0,0'); expect(m.map).toEqual(['S.#', '..G']); expect(m.sarsa).toBe(true); expect(m.forceRight).toBe(true); expect(m.agents!.goals[1]).toEqual([0, 0]); expect(() => parseMarl('marl m\nparams alpha=0.1')).toThrow(/map block/);
    const ev = parseEvo('evo e\nmethod de benchmark=sphere dim=3\nmethod es objective=consensus graph=ring n=5'); expect(ev.methods[0]).toMatchObject({ method: 'de', dim: 3 }); expect(ev.methods[1].objective).toBe('consensus'); expect(() => parseEvo('evo e\nmethod pso')).toThrow(/ga \| de \| es/);
    const ca = parseCa('ca c\nlife steps=3 size=6\n  ##\n  ##\nend\npheromone path=1,1;1,2'); expect(ca.life!.pattern).toEqual(['##', '##']); expect(ca.pheromone!.path).toEqual([[1, 1], [1, 2]]); expect(() => parseCa('ca c')).toThrow(/wolfram, life or pheromone/);
    const fz = parseFuzzy('fuzzy f\ninput dL=1 dF=1 dR=1\nrule far far far -> large straight\ngoal 2,0\nstart 0,1'); expect(fz.rules[0]).toEqual({ if: { dL: 'far', dF: 'far', dR: 'far' }, then: { v: 'large', omega: 'straight' } }); expect(fz.start).toEqual([0, 1]); expect(() => parseFuzzy('fuzzy f\nrule far far -> large')).toThrow(/rule <dL>/);
    const rs = parseResilience('resilience r\nagent A go\nagent B go lies A=stop\ntrust n=4 liar=4\ndegrade order=1\nswitched A1=1,0,0,1 A2=0,1,1,0 tau=0.1,2'); expect(rs.agents[1].lies).toEqual({ A: 'stop' }); expect(rs.agents[0].lies).toBeUndefined(); expect(rs.trust!.liars).toEqual([3]); expect(rs.switched!.modes.length).toBe(2); expect(() => parseResilience('resilience r\nswitched A1=1,2')).toThrow(/row-major/);
  });
  it('mission: robots, architectures, phases, faults and errors', () => {
    const d = parseMission('mission m\nrobots a b c box=2 seed=3\narchitecture decentralised\ncomm radius=3 drop=0.2 lost=2\ncoordinator at=1,1 range=5 fail=10 recover=20\nphase form line r=0.5 name=lineup\nphase goto zone=Dock speed=0.2\nphase allocate zones=Z1,Z2\nphase cover area=0,2,0,2\nphase hold seconds=3\nphase home\nsafety d_safe=0.3\nobstacle at=1,0 r=0.2 name=pillar\nfail b at=5\nduration 100 dt=0.2 vmax=0.4\ndrive pose\nsupervisor Fleet supervisor\nmodes Fleet modes');
    expect(d.robots.map((r) => r.name)).toEqual(['a', 'b', 'c']); expect(Number.isFinite(d.robots[0].at[0])).toBe(true); expect(d.architecture).toBe('decentralized'); expect(d.comm).toMatchObject({ radius: 3, drop: 0.2, lost: 2 }); expect(d.coordinator).toEqual({ at: [1, 1], range: 5, fail: 10, recover: 20 });
    expect(d.phases.map((p) => p.kind)).toEqual(['form', 'goto', 'allocate', 'cover', 'hold', 'home']); expect(d.phases[0]).toMatchObject({ shape: 'line', r: 0.5, name: 'lineup' }); expect(d.phases[1].zone).toBe('Dock'); expect(d.phases[2].targetNames).toEqual(['Z1', 'Z2']); expect(d.phases[3].area).toEqual([0, 2, 0, 2]); expect(d.failures).toEqual([{ robot: 1, at: 5 }]); expect(d.drive).toBe('pose'); expect(d.supervisor).toBe('Fleet supervisor'); expect(d.modes).toBe('Fleet modes'); expect(d.obstacles[0].name).toBe('pillar');
    expect(() => parseMission('mission m\nphase goto')).toThrow(/needs at=/); expect(() => parseMission('mission m\nphase allocate')).toThrow(/targets=/); expect(() => parseMission('mission m\nphase cover')).toThrow(/area=/); expect(() => parseMission('mission m\narchitecture star')).toThrow(/architecture centralized/); expect(() => parseMission('mission m\nrobots a\nphase home\nfail z at=1')).toThrow(/unknown robot/); expect(() => parseMission('mission m\nrobots a')).toThrow(/at least one phase/);
  });
  it('analysis errors are reported with the line number instead of crashing', () => {
    const r = analyse('consensus', 'consensus x\ngraph ring n=4\nsteps abc\nfoo'); expect(r.error).toMatch(/line 4/); expect(r.ok).toBe(false);
    const w = analyse('mission', 'mission x\nphase goto at=1,1\nfail 9 at=1'); expect(w.error).toMatch(/unknown robot/);
  });
});
