/**
 * Lightweight localisation: English strings are the keys; `t()` returns the translation for the
 * current language (falls back to the key). The current language is stored in localStorage.
 */
export type Lang = 'en' | 'ru';

let current: Lang = 'en';
try { const saved = localStorage.getItem('vbs.lang'); if (saved === 'ru' || saved === 'en') current = saved; } catch { /* ignore */ }

const listeners = new Set<() => void>();
export function getLang(): Lang { return current; }
export function setLang(l: Lang): void {
  current = l;
  try { localStorage.setItem('vbs.lang', l); } catch { /* ignore */ }
  for (const fn of listeners) fn();
}
export function onLangChange(fn: () => void): () => void { listeners.add(fn); return () => listeners.delete(fn); }

export function t(s: string): string {
  if (current === 'en') return s;
  const d = DICT[current];
  if (d[s]) return d[s];
  // strip trailing ellipsis / shortcut decorations for lookup
  const base = s.replace(/…$/, '');
  if (d[base]) return d[base] + (s.endsWith('…') ? '…' : '');
  return s;
}

const RU: Record<string, string> = {
  // machine vision
  'Demo scenarios (navigation & vision)': 'Демо-сценарии (навигация и зрение)', 'Load into the studio': 'Загрузить в студию', 'Run headless': 'Прогнать без UI', 'Run all (headless)': 'Прогнать все', 'Download report (.md)': 'Скачать отчёт (.md)', 'All scenarios': 'Все сценарии', 'How to': 'Как воспроизвести', 'Running': 'Выполняется', 'scenarios pass': 'сценариев пройдено',
  'Machine vision': 'Машинное зрение', 'Select vision stack': 'Выбрать стек СТЗ', 'Change vision stack': 'Изменить стек СТЗ', 'Vision tab': 'Вкладка Зрение', 'Vision': 'Зрение', 'Camera / vision sensor': 'Камера / датчик зрения', 'Machine vision stack (camera)': 'Стек машинного зрения (камера)', 'Run vision pipeline (Vision tab)': 'Запустить конвейер зрения (вкладка Зрение)', 'Export ROS 2 perception package (YOLO / tracker / VLM / VLA)': 'Экспорт ROS 2 пакета восприятия (YOLO / трекер / VLM / VLA)', 'Runtime & endpoints (plug in real models)': 'Среда выполнения и эндпоинты (подключение реальных моделей)', 'Pipeline': 'Конвейер', 'Camera: ': 'Камера: ', 'Add camera': 'Добавить камеру', 'live': 'онлайн', 'truth': 'истина', 'Targets → station': 'Цели → станция', 'Reset stats': 'Сбросить статистику', 'Follow with: ': 'Следовать роботом: ', 'follow tracked target': 'следовать за целью', 'Analyse imported cloud': 'Анализ импортированного облака', 'Export cloud (.pcd)': 'Экспорт облака (.pcd)', 'Ask / step': 'Спросить / шаг', 'Camera / sensor': 'Камера / датчик', 'No vision stack on this camera — press Stack… to choose one.': 'На этой камере нет стека зрения — нажмите «Стек…».', 'Add a camera (Add › Camera / vision sensor) and select a vision stack.': 'Добавьте камеру (Добавить › Камера / датчик зрения) и выберите стек зрения.', 'No stack satisfies these constraints — relax the modality, compute or cost.': 'Ни один стек не удовлетворяет ограничениям — ослабьте модальность, вычислитель или стоимость.',
  // menus
  'File': 'Файл', 'Edit': 'Правка', 'Add': 'Добавить', 'Program': 'Программа', 'Robot': 'Робот', 'Mobile & Fleet': 'Мобильные и флот', 'Agriculture': 'Агро', 'Connect': 'Подключение', 'View': 'Вид', 'Help': 'Справка',
  'New station': 'Новая станция', 'Open / import': 'Открыть / импорт', 'Save station (.vbstation)': 'Сохранить станцию (.vbstation)', 'Demo stations': 'Демо-станции',
  'Export program (post processor)': 'Экспорт программы (постпроцессор)', 'Export station as RoboDK API script (.py)': 'Экспорт станции как RoboDK API скрипт (.py)', 'Export station JSON (for rdk_export.py / server)': 'Экспорт станции JSON (для rdk_export.py / сервера)', 'Export screenshot (PNG)': 'Экспорт снимка экрана (PNG)',
  'Undo': 'Отменить', 'Redo': 'Повторить', 'Delete selection': 'Удалить выделенное', 'Rename station': 'Переименовать станцию', 'Station name': 'Имя станции',
  'Robot from library': 'Робот из библиотеки', 'Navigation & SLAM stack': 'Стек навигации и SLAM', 'Export ROS 2 navigation package (Nav2 + SLAM)': 'Экспорт ROS 2 пакета навигации (Nav2 + SLAM)', 'Navigation & localization': 'Навигация и локализация', 'Select stack…': 'Выбрать стек…', 'Change stack…': 'Сменить стек…', 'Export ROS 2 package': 'Экспорт ROS 2 пакета', 'Navigation tab': 'Вкладка Навигация', 'Navigation': 'Навигация', 'Apply stack': 'Применить стек', 'Sensors on the vehicle': 'Датчики на машине', 'Recommended stacks (click to select)': 'Рекомендуемые стеки (щёлкните для выбора)', 'Platform': 'Платформа', 'Environment': 'Среда', 'Simulate localization (estimate drives the controller)': 'Симулировать локализацию (контроллер ведёт по оценке)', 'Simulate localization errors in the world simulation': 'Симулировать ошибки локализации в мировой симуляции', 'Save for Blender add-on (.vbstation + animation)': 'Сохранить для аддона Blender (.vbstation + анимация)', 'VDA 5050 fleet interface (AGV / AMR, KUKA Fleet, MiR)': 'Интерфейс флота VDA 5050 (AGV / AMR, KUKA Fleet, MiR)', 'Disconnect VDA 5050': 'Отключить VDA 5050', 'VDA 5050 fleet interface (AGV / AMR)': 'Интерфейс флота VDA 5050 (AGV / AMR)', 'MQTT broker URL': 'Адрес MQTT-брокера', 'Role': 'Роль', 'Reconnect': 'Переподключить', 'Robot machining project (NC / G-code / 3D print)': 'Проект обработки роботом (NC / G-code / 3D-печать)', 'Robot machining project (NC / G-code)': 'Проект обработки роботом (NC / G-code)', 'Generate program': 'Сгенерировать программу', 'Part / NC program object': 'Деталь / объект NC-программы', 'Approach / retract distance (mm)': 'Подход / отвод (мм)', 'Rapid speed (mm/s)': 'Скорость холостых ходов (мм/с)', 'Export URDF package (robot / station, zip)': 'Экспорт URDF-пакета (робот / станция, zip)', 'Export animation as glTF (Blender)': 'Экспорт анимации в glTF (Blender)', 'Import RoboDK post processors (.py)': 'Импорт постпроцессоров RoboDK (.py)', 'Export animation (glTF for Blender)': 'Экспорт анимации (glTF для Blender)', 'Export URDF package': 'Экспорт URDF-пакета', 'Keyframes per second': 'Ключевых кадров в секунду', 'Include frame / target helpers': 'Включить системы координат / цели', 'Content': 'Содержимое', 'ROS package name (optional)': 'Имя ROS-пакета (необязательно)', 'Export': 'Экспорт', 'Robot from online library (ROS-Industrial)': 'Робот из онлайн-библиотеки (ROS-Industrial)', 'Add robot from online library': 'Добавить робота из онлайн-библиотеки', 'Download 3D meshes': 'Скачать 3D-модели', 'Reference frame': 'Система координат', 'Target (teach)': 'Цель (обучить)', 'Target (at robot TCP)': 'Цель (в TCP робота)', 'Folder': 'Папка', 'Box': 'Параллелепипед', 'Cylinder': 'Цилиндр', 'Sphere': 'Сфера',
  'Process component (VC-style)': 'Компонент процесса (стиль VC)', 'Process component': 'Компонент процесса', 'Import URDF / STL / program / .rdk': 'Импорт URDF / STL / программы / .rdk',
  'New program': 'Новая программа', 'Teach MoveJ': 'Обучить MoveJ', 'Teach MoveL': 'Обучить MoveL', 'Run': 'Запуск', 'Pause': 'Пауза', 'Stop': 'Стоп', 'Validate (compile)': 'Проверить (компиляция)', 'Export with post processor': 'Экспорт постпроцессором',
  'Home active robot': 'Активный робот в исходное', 'Add tool to active robot': 'Добавить инструмент активному роботу', 'Fruit picking program for active robot': 'Программа сбора плодов для активного робота', 'Follow curve / points of an object': 'Следовать по кривой / точкам объекта', 'Move with external axes (rail / gantry)': 'Движение с внешними осями (рельс / портал)', 'Move with external axes (rail/gantry)': 'Движение с внешними осями (рельс/портал)',
  'Check collisions now (static)': 'Проверить коллизии сейчас (статически)', 'Check collisions during program validation': 'Проверять коллизии при проверке программы',
  'Add mobile robot': 'Добавить мобильного робота', 'Create fleet': 'Создать флот', 'Occupancy map': 'Карта проходимости', 'Zone (charging / no-go)': 'Зона (зарядка / запрет)', 'Start world simulation': 'Запустить симуляцию мира', 'Pause world': 'Пауза мира', 'Reset world': 'Сброс мира',
  'Create field / orchard': 'Создать поле / сад', 'Create mission': 'Создать миссию', 'Import field from GeoJSON': 'Импорт поля из GeoJSON', 'Demo: apple orchard with harvesting fleet': 'Демо: яблоневый сад с флотом сборщиков', 'Demo: greenhouse tomato with rail robots': 'Демо: теплица с томатами и рельсовыми роботами',
  'ROS 2 via rosbridge': 'ROS 2 через rosbridge', 'Disconnect rosbridge': 'Отключить rosbridge', 'Studio server (Python RoboDK API clients)': 'Сервер студии (Python клиенты RoboDK API)',
  'Fit all': 'Показать всё', 'Top': 'Сверху', 'Front': 'Спереди', 'Side': 'Сбоку', 'Isometric': 'Изометрия', 'Show reference frames': 'Показывать системы координат', 'Show targets': 'Показывать цели', 'Gizmo: translate': 'Манипулятор: перемещение', 'Gizmo: rotate': 'Манипулятор: вращение', 'Toggle bottom panel': 'Скрыть/показать нижнюю панель', 'Language: Русский': 'Язык: English',
  'Quick start': 'Быстрый старт', 'RoboDK API compatibility notes': 'Совместимость с RoboDK API', 'About': 'О программе',
  // context menu
  'Move robot here (MoveJ)': 'Переместить робота сюда (MoveJ)', 'Move robot here (MoveL)': 'Переместить робота сюда (MoveL)', 'Teach current position': 'Записать текущее положение', 'Set as Cartesian target': 'Сделать декартовой целью', 'Set as Joint target': 'Сделать суставной целью', 'Add MoveJ to program': 'Добавить MoveJ в программу', 'Add MoveL to program': 'Добавить MoveL в программу',
  'Set as active robot': 'Сделать активным роботом', 'Home': 'Исходное', 'Generate picking program for nearby fruit': 'Сгенерировать программу сбора ближайших плодов', 'Set as active reference': 'Сделать активной СК', 'Set as active tool': 'Сделать активным инструментом', 'Validate': 'Проверить', 'Export (post processor)': 'Экспорт (постпроцессор)',
  'Regenerate rows': 'Перегенерировать ряды', 'Build navigation map': 'Построить карту навигации', 'Plan mission (create fleet tasks)': 'Спланировать миссию (создать задачи флота)', 'Set home here': 'Задать дом здесь', 'Navigate to point': 'Ехать в точку', 'Add all mobile robots to fleet': 'Добавить всех мобильных роботов во флот',
  'Focus': 'Сфокусировать', 'Hide': 'Скрыть', 'Show': 'Показать', 'Rename': 'Переименовать', 'Delete': 'Удалить', 'Name': 'Имя', 'Tool (on active robot)': 'Инструмент (на активном роботе)', 'Mobile robot': 'Мобильный робот', 'Field / orchard': 'Поле / сад', 'Fleet': 'Флот', 'Mission': 'Миссия', 'Map (occupancy grid)': 'Карта (сетка проходимости)',
  // dialogs
  'Add robot from library': 'Добавить робота из библиотеки', 'Type': 'Тип', 'Crop': 'Культура', 'Field width (m)': 'Ширина поля (м)', 'Field length (m)': 'Длина поля (м)', 'Row spacing (m)': 'Междурядье (м)', 'Plant spacing (m)': 'Шаг растений (м)', 'Row heading (deg)': 'Направление рядов (°)', 'Headland (m)': 'Поворотная полоса (м)', 'Ripe fraction': 'Доля спелых', 'Greenhouse (indoor)': 'Теплица (закрытый грунт)', 'Build navigation map + headland zones': 'Построить карту навигации и зоны разворота',
  'Fleet name': 'Имя флота', 'Number of robots': 'Число роботов', 'Robot type': 'Тип робота', 'Allocation': 'Распределение', 'Add charging zone at start': 'Добавить зону зарядки в начале', 'Cost-based auction': 'Аукцион по стоимости', 'Nearest': 'Ближайший', 'Round robin': 'По кругу',
  'Field': 'Поле', 'Rows (e.g. 1-5,8; empty = all)': 'Ряды (например 1-5,8; пусто = все)', 'Work speed (m/s)': 'Рабочая скорость (м/с)', 'Work both sides of each row': 'Обрабатывать обе стороны ряда', 'Plan now (create fleet tasks)': 'Спланировать сейчас (создать задачи)',
  'Create occupancy map': 'Создать карту проходимости', 'Width (m)': 'Ширина (м)', 'Height (m)': 'Высота (м)', 'Length (m)': 'Длина (м)', 'Resolution (m/cell)': 'Разрешение (м/ячейка)', 'Rasterise objects footprints': 'Растеризовать габариты объектов', 'Create zone': 'Создать зону', 'Kind': 'Вид',
  'Add process component': 'Добавить компонент процесса', 'Connect output to': 'Соединить выход с', 'Feeder (creates products)': 'Источник (создаёт изделия)', 'Conveyor': 'Конвейер', 'Process / machine': 'Процесс / станок', 'Buffer / pallet': 'Буфер / паллета', 'Sink (consumes)': 'Сток (потребляет)',
  'Post processor': 'Постпроцессор', 'Download': 'Скачать', 'Cancel': 'Отмена', 'OK': 'ОК', 'Yes': 'Да',
  'Max fruit': 'Макс. плодов', 'Approach distance (mm)': 'Дистанция подхода (мм)', 'Approach': 'Подход', 'Generate fruit picking program': 'Сгенерировать программу сбора плодов',
  'Parameters': 'Параметры', 'Linear speed (mm/s)': 'Линейная скорость (мм/с)', 'Joint speed (deg/s)': 'Скорость суставов (°/с)', 'Linear accel (mm/s²)': 'Линейное ускорение (мм/с²)', 'Joint accel (deg/s²)': 'Ускорение суставов (°/с²)', 'Controller IP / ROS namespace': 'IP контроллера / ROS namespace',
  'Connect to ROS 2 (rosbridge_server)': 'Подключение к ROS 2 (rosbridge_server)', 'rosbridge websocket URL': 'URL websocket rosbridge', 'Mode': 'Режим', 'Publish rate (Hz)': 'Частота публикации (Гц)', 'Studio server': 'Сервер студии',
  // panels
  'Station': 'Станция', 'Properties': 'Свойства', 'Select an item in the tree or the 3D view.': 'Выберите элемент в дереве или в 3D-виде.', 'Simulation': 'Симуляция', 'Process': 'Процесс', 'Console (RoboDK API)': 'Консоль (RoboDK API)', 'Log': 'Журнал',
  'Joints (deg / mm)': 'Суставы (° / мм)', 'Cartesian jog (tool frame)': 'Декартов джог (СК инструмента)', 'Status': 'Состояние', 'Frames': 'Системы координат', 'Active reference frame': 'Активная система координат', 'Active tool': 'Активный инструмент', 'Teach target': 'Записать цель', 'Set active': 'Сделать активным',
  'Target': 'Цель', 'Joint target (use recorded joints)': 'Суставная цель (использовать записанные суставы)', 'Recorded joints': 'Записанные суставы', 'Reachable by active robot': 'Достижима активным роботом', 'MoveJ here': 'MoveJ сюда', 'MoveL here': 'MoveL сюда', 'Teach': 'Записать',
  'Tool': 'Инструмент', 'Tool kind': 'Вид инструмента', 'Instructions': 'Инструкции', 'Cycle time': 'Время цикла', 'Distance': 'Дистанция', 'Move type': 'Тип движения', 'Enabled': 'Включено', 'Message': 'Сообщение',
  'State': 'Состояние', 'Kinematics': 'Кинематика', 'Drive': 'Привод', 'Battery & capabilities': 'Батарея и возможности', 'Capacity (Wh)': 'Ёмкость (Вт·ч)', 'Capabilities (comma separated)': 'Возможности (через запятую)', 'ROS 2 namespace': 'ROS 2 namespace',
  'Crop row': 'Ряд культуры', 'Plants': 'Растения', 'Ripe fruit': 'Спелые плоды', 'Robots per row segment': 'Роботов на сегмент ряда', 'Component': 'Компонент', 'Output to': 'Выход на', 'Object': 'Объект', 'Colour': 'Цвет', 'Zone': 'Зона', 'Map': 'Карта',
  'Tools': 'Инструменты', 'Collision map': 'Карта коллизий', 'Measure (two selected items / item to TCP)': 'Измерить (два выбранных элемента / элемент до TCP)', 'Camera parameters': 'Параметры камеры', 'Record video of the 3D view (WebM)': 'Записать видео 3D-вида (WebM)', 'Stop video recording': 'Остановить запись видео', 'Export 3D HTML (self-contained viewer)': 'Экспорт 3D HTML (автономный просмотрщик)', 'Export scene as glTF (.glb)': 'Экспорт сцены в glTF (.glb)', 'New station tab': 'Новая вкладка станции', 'Close station tab': 'Закрыть вкладку станции',
  'Camera': 'Камера', 'Camera (on selected item)': 'Камера (на выбранном элементе)', 'Render view': 'Отрисовать вид', 'Save PNG': 'Сохранить PNG', 'Show robot reach': 'Показывать зону досягаемости',
  'Plan': 'Спланировать', 'Run world': 'Запустить мир', 'Start': 'Старт', 'Reset': 'Сброс', 'Speed': 'Скорость', 'End': 'Конец',
  'Control': 'Управление', 'Control design': 'Проектирование управления', 'Control model': 'Модель управления', 'New control model': 'Новая модель управления', 'New': 'Новая', 'Course examples': 'Примеры курса', 'Add all examples': 'Добавить все примеры', 'Analyse': 'Анализ', 'Analyse all': 'Анализ всех', 'Detect kind': 'Определить тип', 'Run mission': 'Запустить миссию', 'Stop mission': 'Остановить миссию', 'Mission runtime:': 'Исполнение миссии:', 'targets': 'целей', 'Report (Markdown)': 'Отчёт (Markdown)', 'Document (.ctl.txt)': 'Документ (.ctl.txt)', 'Graph view (SVG)': 'Граф (SVG)', 'Supervisor table (JSON)': 'Таблица супервизора (JSON)', 'Supervisor runtime (Python)': 'Супервизор (Python)', 'Mission trace (CSV)': 'Трасса миссии (CSV)', 'Mission log': 'Журнал миссии', 'No model selected': 'Модель не выбрана', 'issues found': 'найдены проблемы', 'Metrics': 'Метрики', 'Open in Control tab': 'Открыть во вкладке «Управление»', 'Course chapter': 'Глава курса', 'Lines': 'Строк', 'Last verdict': 'Последний вердикт', 'Last verdict:': 'Последний вердикт:', 'press Analyse (Ctrl+Enter) for the full report': 'нажмите «Анализ» (Ctrl+Enter) для полного отчёта', 'plant': 'объект', 'mode': 'режим', 'denied': 'запрещено', 'violations': 'нарушений', 'Select a model on the left, or create one with New ▾ / Course examples ▾': 'Выберите модель слева или создайте её через «Новая ▾» / «Примеры курса ▾»', 'No control models. Use New ▾ or Course examples ▾, or Help › Demo scenarios (control design).': 'Моделей управления нет. Используйте «Новая ▾», «Примеры курса ▾» или Справка › Демо-сценарии (проектирование управления).', 'Zones named as in the tree (home, table, bin, dock) are used as goto targets; an item named "Human" is the human position.': 'Зоны с именами из дерева (home, table, bin, dock) — цели действия goto; элемент с именем «Human» задаёт положение человека.', 'New control model…': 'Новая модель управления…', 'Course examples (A: mobile manipulator, B: production cell)…': 'Примеры курса (A: мобильный манипулятор, B: производственная ячейка)…', 'Open Control tab': 'Открыть вкладку «Управление»', 'Analyse all models (deadlocks, livelocks, specifications, synthesis)': 'Анализ всех моделей (дедлоки, лайвлоки, спецификации, синтез)', 'Run mission (selected behavior tree on the selected robot)': 'Запустить миссию (выбранное дерево поведения на выбранном роботе)', 'Demo scenarios: control design…': 'Демо-сценарии: проектирование управления…', 'Demo scenarios (navigation, vision, control design)…': 'Демо-сценарии (навигация, зрение, проектирование управления)…',
  'Text': 'Текст', 'Diagram': 'Схема', 'Select': 'Выбор', '+ State': '+ Состояние', '+ Place': '+ Позиция', '+ Transition': '+ Переход', '+ Edge': '+ Дуга', '+ Arc': '+ Дуга', 'Auto layout': 'Авторазмещение', '+ Automaton': '+ Автомат', '+ Spec': '+ Спецификация', 'Drag to move · click to inspect · double-click the canvas to add': 'Перетаскивайте узлы · щёлкните для свойств · двойной щелчок по полю добавляет узел', 'Click on the canvas to add': 'Щёлкните по полю, чтобы добавить', 'Click on the canvas to add a transition': 'Щёлкните по полю, чтобы добавить переход', 'Click the source node': 'Щёлкните исходный узел', 'Click a node or an edge to remove it': 'Щёлкните узел или дугу, чтобы удалить', 'Document': 'Документ', 'Uncontrollable': 'Неуправляемые', 'Unobservable': 'Ненаблюдаемые', 'Faults': 'Отказы', 'Specification': 'Спецификация', 'Automaton': 'Автомат', 'Alphabet': 'Алфавит', 'Petri net': 'Сеть Петри', 'Horizon (s)': 'Горизонт (с)', 'Initial': 'Начальное', 'Marked': 'Маркированное', 'Place': 'Позиция', 'Tokens': 'Фишки', 'Capacity': 'Ёмкость', 'Label': 'Подпись', 'Transition': 'Переход', 'Delay (s)': 'Задержка (с)', 'Rate (1/s)': 'Интенсивность (1/с)', 'Immediate': 'Мгновенный', 'Weight': 'Вес', 'Priority': 'Приоритет', 'Edge': 'Дуга', 'Events': 'События', 'Arc': 'Дуга', 'Inhibitor': 'Ингибиторная', 'Reverse': 'Развернуть', 'No document loaded': 'Документ не загружен', 'Events used by transitions are always in the alphabet; declare extra ones here (e.g. a spec that forbids an event).': 'События переходов всегда входят в алфавит; здесь объявляются дополнительные (например, событие, запрещаемое спецификацией).', 'Uncontrollable events are drawn dashed; edit the list in the document properties.': 'Неуправляемые события рисуются пунктиром; список редактируется в свойствах документа.', 'Drag nodes, click to inspect': 'Перетаскивание узлов, щелчок — свойства', 'Click the source node, then the target': 'Щёлкните исходный узел, затем целевой', 'Recompute the positions of this diagram': 'Пересчитать расположение узлов', 'Add a plant component': 'Добавить компонент объекта', 'Add a specification automaton': 'Добавить автомат спецификации', 'Remove this automaton': 'Удалить этот автомат', 'Swap direction': 'Поменять направление',
  'Run on station': 'Запустить на станции', 'Undo the last edit of this model (Ctrl+Z in the diagram)': 'Отменить последнюю правку модели (Ctrl+Z в схеме)', 'Redo (Ctrl+Y / Ctrl+Shift+Z in the diagram)': 'Вернуть (Ctrl+Y / Ctrl+Shift+Z в схеме)', 'Expand the editor over the model list and the report': 'Развернуть редактор на место списка моделей и отчёта', 'firings': 'срабатываний', 'mismatches': 'рассогласований', 'running': 'выполняется', 'Entry action (robot)': 'Действие при входе (робот)', 'Operation (robot)': 'Операция (робот)', 'Action': 'Действие', 'none': 'нет', 'run program': 'выполнить программу', 'move to target': 'перейти в цель', 'go to zone': 'ехать в зону', 'set signal': 'установить сигнал', 'wait': 'ждать', 'emit event': 'выдать событие', 'set blackboard': 'записать в blackboard', 'Runs when the state is entered; done= fires the event that leaves it.': 'Выполняется при входе в состояние; done= выдаёт событие, по которому состояние покидается.', 'Runs when the transition fires; the output tokens appear when it finishes.': 'Выполняется при срабатывании перехода; выходные фишки появляются по завершении.', 'Linear (MoveL)': 'Линейно (MoveL)', 'Signal': 'Сигнал', 'Value': 'Значение', 'Seconds': 'Секунды', 'Event': 'Событие', 'Key': 'Ключ', 'Done event (fired when finished)': 'Событие завершения (выдаётся по окончании)', 'Run on station executes the automaton / net: entry actions and transition operations bound in the diagram inspector drive the robots, programs, targets and signals of the station.': '«Запустить на станции» исполняет автомат / сеть: действия состояний и операции переходов, назначенные в инспекторе схемы, управляют роботами, программами, целями и сигналами станции.',
  '+ Child': '+ Потомок', '+ Sibling': '+ Сосед', 'Add a child to the selected node (or to the root)': 'Добавить потомка выбранному узлу (или корню)', 'Insert a sibling after the selected node': 'Вставить соседа после выбранного узла', 'Move out of the parent': 'Вынести из родителя', 'Click to inspect · drag a node onto a composite to move it inside, onto a leaf to place it after · + Child adds under the selection': 'Щелчок — свойства · перетащите узел на композит, чтобы поместить внутрь, на лист — чтобы поставить после него · «+ Потомок» добавляет под выделение', 'Behavior tree': 'Дерево поведения', 'Supervisor (des model)': 'Супервизор (модель des)', 'Mode automaton (hybrid model)': 'Автомат режимов (модель hybrid)', 'Monitors (LTL, one per line)': 'Мониторы (LTL, по одному в строке)', 'Leaf models (leaf p= ticks=)': 'Модели листьев (leaf p= ticks=)', 'Outcomes (leaf=success,running)': 'Исходы (leaf=success,running)', 'nodes': 'узлов', 'Root node': 'Корневой узел', 'Node': 'Узел', 'Memory (resume the running child)': 'Память (продолжать с выполняющегося потомка)', 'Success threshold': 'Порог успеха', 'Count': 'Количество', 'children': 'потомков', 'Expression or blackboard key': 'Выражение или ключ blackboard', 'Binding': 'Привязка', 'Emit event': 'Выдать событие', 'Success probability p': 'Вероятность успеха p', 'Supervisor events': 'События супервизора', 'event= (controllable, asked before start)': 'event= (управляемое, запрашивается перед стартом)', 'done= (observed on success)': 'done= (наблюдается при успехе)', 'arrive= / ok= / miss= / put= (world events)': 'arrive= / ok= / miss= / put= (события мира)', 'Contract': 'Контракт', 'Timeout (s)': 'Тайм-аут (с)', 'Precondition': 'Предусловие', 'Postcondition': 'Постусловие', 'Other arguments (key=value …)': 'Прочие аргументы (key=value …)', 'Name (optional)': 'Имя (необязательно)',
  'Group': 'Группа', 'Group control': 'Групповое управление', 'Group examples': 'Примеры (группы)', 'Add all group examples': 'Добавить все примеры группового управления', 'Build scene': 'Построить сцену', 'Run on fleet': 'Запустить на флоте', 'Fleet log': 'Журнал флота', 'New group-control model': 'Новая модель группового управления', 'New group-control model…': 'Новая модель группового управления…', 'Course examples: group control (ПР1–ПР6, warehouse homework, chapters)…': 'Примеры курса: групповое управление (ПР1–ПР6, склад из ДЗ, главы)…', 'Run selected model on the fleet (consensus, swarm, coverage, safety, MAPF, warehouse)': 'Запустить выбранную модель на флоте (консенсус, рой, покрытие, безопасность, MAPF, склад)', 'Stop fleet run': 'Остановить запуск на флоте', 'Build warehouse scene from the selected model': 'Построить сцену склада по выбранной модели', 'Demo scenarios: group control…': 'Демо-сценарии: групповое управление…', 'Course examples of the group-control module: practicum ПР1–ПР6, the warehouse homework and the chapter examples': 'Примеры курса модуля группового управления: практикум ПР1–ПР6, склад из домашнего задания и примеры глав', 'Build the map, the station zones and the robots of the selected warehouse model': 'Построить карту, зоны станций и роботов выбранной модели склада', 'Run on fleet drives the mobile robots of the station with the group law of the model (mission under a chosen architecture, consensus / formation, swarm, coverage, safety filter, grid MAPF plan, warehouse fleet); a warehouse model builds its scene with Build scene.': '«Запустить на флоте» ведёт мобильных роботов станции по групповому закону модели (миссия в выбранной архитектуре, консенсус / формация, рой, покрытие, фильтр безопасности, план MAPF, склад); для модели склада сцена строится кнопкой «Построить сцену».', 'This group-control model is analysed only (report with charts); runnable kinds: mission, consensus, swarm, coverage, safety, gridmapf, warehouse.': 'Эта модель группового управления только анализируется (отчёт с графиками); исполняемые виды: mission, consensus, swarm, coverage, safety, gridmapf, warehouse.', 'Group control (multi-robot systems)': 'Групповое управление (многороботные системы)', 'Discrete-event models': 'Дискретно-событийные модели', 'Executive layer': 'Исполнительный уровень', 'Verification & synthesis': 'Верификация и синтез', 'Planning & decisions': 'Планирование и решения', 'Coordination & scheduling': 'Координация и расписания', 'Engineering: real-time, reliability, V&V': 'Инженерия: реальное время, надёжность, V&V',
};
const DICT: Record<Lang, Record<string, string>> = { en: {}, ru: RU };
