/**
 * Test report: coverage per module, unit / A/B / browser results and the scenario suite in one Markdown page
 * (`studio/docs/test-report.md`, included by the documentation). Sources, all optional:
 *   coverage/coverage-summary.json  — `npm run test:coverage` (v8 json-summary)
 *   coverage/unit-results.json      — `npm run test:coverage` (vitest json reporter)
 *   test-results/e2e-results.json   — `npm run test:e2e` (outside coverage/, which every coverage run cleans)
 *   docs/scenario-results.md        — `npm run scenarios`
 * Usage: node scripts/test-report.mjs   (run from studio/)
 */
import fs from 'node:fs';
import path from 'node:path';

const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
const read = (p) => { try { return JSON.parse(fs.readFileSync(path.join(root, p), 'utf8')); } catch { return null; } };
const cov = read('coverage/coverage-summary.json');
const unit = read('coverage/unit-results.json');
const e2e = read('test-results/e2e-results.json');
const scenarios = (() => { try { return fs.readFileSync(path.join(root, 'docs/scenario-results.md'), 'utf8'); } catch { return ''; } })();
const pct = (x) => `${x.toFixed(1)} %`;
const out = [];
out.push('<!-- generated by `npm run test:report` in studio/ — do not edit by hand -->', '');
out.push(`Generated ${new Date().toISOString().slice(0, 10)}`, '');

// --- summary ------------------------------------------------------------------------------------------------------
out.push('### Summary', '', '| Layer | Result |', '|---|---|');
if (unit) out.push(`| Unit, integration and A/B tests (vitest, node + jsdom) | ${unit.numPassedTests}/${unit.numTotalTests - (unit.numPendingTests ?? 0)} tests pass in ${unit.testResults.length} files${unit.numPendingTests ? ` (${unit.numPendingTests} network tests skipped offline)` : ''}${unit.numFailedTests ? ` — **${unit.numFailedTests} failing**` : ''} |`);
if (cov?.total) out.push(`| Line coverage of \`src/\` | ${pct(cov.total.lines.pct)} lines · ${pct(cov.total.functions.pct)} functions · ${pct(cov.total.branches.pct)} branches |`);
if (e2e) out.push(`| Browser end-to-end (Playwright over the production build) | ${e2e.numPassedTests}/${e2e.numTotalTests} tests pass${e2e.numFailedTests ? ` — **${e2e.numFailedTests} failing**` : ''} |`);
{ const m = /(\d+)\/(\d+) scenarios pass/.exec(scenarios); if (m) out.push(`| Demo scenarios (navigation, vision, control design, group control) | ${m[1]}/${m[2]} pass |`); }
out.push('');

// --- coverage per module ------------------------------------------------------------------------------------------
if (cov) {
  const mods = new Map();
  for (const [file, v] of Object.entries(cov)) {
    if (file === 'total') continue; const rel = file.split('/src/')[1] ?? file; const mod = rel.includes('/') ? rel.split('/')[0] : 'app / demos (root)';
    const m = mods.get(mod) ?? { lines: [0, 0], funcs: [0, 0], branches: [0, 0], files: [] }; mods.set(mod, m);
    m.lines[0] += v.lines.covered; m.lines[1] += v.lines.total; m.funcs[0] += v.functions.covered; m.funcs[1] += v.functions.total; m.branches[0] += v.branches.covered; m.branches[1] += v.branches.total; m.files.push([rel, v.lines.pct, v.lines.total]);
  }
  const DESC = { core: 'items, kinematics, motion, collision, calibration', io: 'station files, URDF, meshes, RoboDK, programs, zip containers', posts: 'post processors', api: 'RoboDK-compatible API, RPC, server client', ctl: 'control design (DES, Petri nets, logic, planning, scheduling, V&V)', mrs: 'group control (consensus, swarms, allocation, MAPF, coverage, safety, missions)', mobile: 'mobile robots, planners, navigation stack', fleet: 'fleet manager, VDA 5050', vision: 'machine-vision stack', agri: 'fields, orchards, missions', ros: 'rosbridge publishers', vc: 'process components', scene: 'three.js renderer (browser only — covered by the e2e suite)', ui: 'panels, menus, dialogs, editors (jsdom + e2e)', scenarios: 'demo scenarios', 'app / demos (root)': 'App class, demo stations' };
  out.push('### Coverage per module', '', '| Module | What | Lines | Functions | Branches | Lowest files |', '|---|---|---|---|---|---|');
  for (const [mod, m] of [...mods.entries()].sort((a, b) => a[0].localeCompare(b[0]))) {
    const low = m.files.filter((f) => f[2] >= 20).sort((a, b) => a[1] - b[1]).slice(0, 2).map((f) => `\`${f[0].replace(/^[^/]+\//, '')}\` ${f[1].toFixed(0)} %`).join(', ');
    out.push(`| \`${mod}\` | ${DESC[mod] ?? ''} | ${pct(100 * m.lines[0] / Math.max(1, m.lines[1]))} (${m.lines[0]}/${m.lines[1]}) | ${pct(100 * m.funcs[0] / Math.max(1, m.funcs[1]))} | ${pct(100 * m.branches[0] / Math.max(1, m.branches[1]))} | ${low} |`);
  }
  out.push('');
}

// --- test files ---------------------------------------------------------------------------------------------------
if (unit) {
  const groups = [['A/B paired-variant tests', /ab_variants/], ['UI and App (jsdom)', /\/ui_/], ['Coverage suites added for the module audit', /\/cov_/], ['Control design', /\/ctl_/], ['Group control', /\/mrs_/], ['Scenarios', /scenarios\.test/], ['Everything else (kinematics, programs, io, vision, fleet, api…)', /./]];
  out.push('### Test files', '', '| Group | Files | Tests | Time |', '|---|---|---|---|');
  const seen = new Set();
  for (const [name, re] of groups) {
    const files = unit.testResults.filter((f) => !seen.has(f.name) && re.test(f.name)); files.forEach((f) => seen.add(f.name));
    if (!files.length) continue; const tests = files.reduce((s, f) => s + f.assertionResults.length, 0); const failed = files.reduce((s, f) => s + f.assertionResults.filter((a) => a.status === 'failed').length, 0); const ms = files.reduce((s, f) => s + (f.endTime - f.startTime), 0);
    out.push(`| ${name} | ${files.length} | ${tests}${failed ? ` (**${failed} failing**)` : ''} | ${(ms / 1000).toFixed(1)} s |`);
  }
  out.push('');
  const ab = unit.testResults.find((f) => /ab_variants/.test(f.name));
  if (ab) {
    out.push('### A/B pairs', '', 'Each pair runs the same job two ways and asserts the relation between the results.', '', '| Pair | Result |', '|---|---|');
    for (const a of ab.assertionResults) out.push(`| ${a.title.replace(/\|/g, '\\|')} | ${a.status === 'passed' ? '✓' : '**' + a.status + '**'} |`);
    out.push('');
  }
}

// --- browser ------------------------------------------------------------------------------------------------------
if (e2e) {
  out.push('### Browser end-to-end', '', 'Playwright drives the production build in Chromium (software GL): a page error or a console error anywhere fails the test.', '', '| Test | Result | Time |', '|---|---|---|');
  for (const f of e2e.testResults) for (const a of f.assertionResults) out.push(`| ${a.title.replace(/\|/g, '\\|')} | ${a.status === 'passed' ? '✓' : '**' + a.status + '**'} | ${((a.duration ?? 0) / 1000).toFixed(0)} s |`);
  out.push('');
}

// --- scenarios ----------------------------------------------------------------------------------------------------
if (scenarios) {
  const groupsCount = [...scenarios.matchAll(/^### (.+)$/gm)].map((m) => m[1]);
  out.push('### Demo scenarios', '', `${groupsCount.length} groups (${groupsCount.join(', ')}); the full table with every metric is on the *Demo scenarios* page.`, '');
}

fs.writeFileSync(path.join(root, 'docs/test-report.md'), out.join('\n'));
console.log(`wrote docs/test-report.md (${out.length} lines)`);
