import { PostProcessor, PostProgram, PostFile, f, safeName, registerPost } from './base';
import { poseToQuat, getPos } from '../core/math/pose';

const robtarget = (m: Float64Array, conf: number[] = [0, 0, 0, 0]) => {
  const [x, y, z] = getPos(m);
  const [w, qx, qy, qz] = poseToQuat(m);
  return `[[${f(x)},${f(y)},${f(z)}],[${f(w, 6)},${f(qx, 6)},${f(qy, 6)},${f(qz, 6)}],[${conf.join(',')}],[9E9,9E9,9E9,9E9,9E9,9E9]]`;
};
const jointtarget = (q: number[]) => `[[${[0, 1, 2, 3, 4, 5].map((i) => f(q[i] ?? 0)).join(',')}],[${q[6] !== undefined ? f(q[6]) : '9E9'},9E9,9E9,9E9,9E9,9E9]]`;
const pose = (m: Float64Array) => {
  const [x, y, z] = getPos(m);
  const [w, qx, qy, qz] = poseToQuat(m);
  return `[[${f(x)},${f(y)},${f(z)}],[${f(w, 6)},${f(qx, 6)},${f(qy, 6)},${f(qz, 6)}]]`;
};
/** ABB configuration data cf1,cf4,cf6,cfx from joint angles (quadrants of j1,j4,j6). */
const confOf = (q: number[] | null) => (q ? [Math.floor((q[0] ?? 0) / 90), Math.floor((q[3] ?? 0) / 90), Math.floor((q[5] ?? 0) / 90), 0] : [0, 0, 0, 0]);
const zoneOf = (r: number) => (r <= 0 ? 'fine' : r <= 1 ? 'z1' : r <= 5 ? 'z5' : r <= 10 ? 'z10' : r <= 20 ? 'z20' : r <= 50 ? 'z50' : r <= 100 ? 'z100' : 'z200');

/** ABB RAPID (IRC5 / OmniCore) module post processor. */
export const ABB_RAPID: PostProcessor = {
  id: 'ABB_RAPID_IRC5',
  name: 'ABB RAPID (IRC5/OmniCore)',
  brand: 'ABB',
  extension: 'mod',
  generate(p: PostProgram, options: Record<string, any> = {}): PostFile[] {
    const modName = safeName(p.name);
    const head: string[] = [`MODULE ${modName}`, `  ! Generated by VerticalBot Studio for ${p.robotName}`];
    const body: string[] = [];
    let speed = 'v500';
    let zone = 'fine';
    let toolName = safeName(p.tool.name || 'tool0');
    let wobjName = safeName(p.frame.name || 'wobj0');
    head.push(`  PERS tooldata ${toolName} := [TRUE,${pose(p.tool.pose)},[1,[0,0,50],[1,0,0,0],0,0,0]];`);
    head.push(`  PERS wobjdata ${wobjName} := [FALSE,TRUE,"",${pose(p.frame.pose)},[[0,0,0],[1,0,0,0]]];`);
    let speedDecl = new Set<string>();
    body.push(`  PROC main()`);
    body.push(`    ConfL \\Off;`, `    ConfJ \\Off;`);
    let jTarget = 0;
    for (const ev of p.events) {
      switch (ev.kind) {
        case 'moveJ': {
          jTarget++;
          const nm = `jt_${safeName(ev.name)}_${jTarget}`;
          head.push(`  CONST jointtarget ${nm} := ${jointtarget(ev.joints)};`);
          body.push(`    MoveAbsJ ${nm},${speed},${zone},${toolName}\\WObj:=${wobjName};`);
          break;
        }
        case 'moveL': body.push(`    MoveL ${robtarget(ev.pose, confOf(ev.joints))},${speed},${zone},${toolName}\\WObj:=${wobjName};  ! ${ev.name}`); break;
        case 'moveC': body.push(`    MoveC ${robtarget(ev.via)},${robtarget(ev.pose, confOf(ev.joints))},${speed},${zone},${toolName}\\WObj:=${wobjName};  ! ${ev.name}`); break;
        case 'setFrame': wobjName = safeName(ev.name); head.push(`  PERS wobjdata ${wobjName} := [FALSE,TRUE,"",${pose(ev.pose)},[[0,0,0],[1,0,0,0]]];`); break;
        case 'setTool': toolName = safeName(ev.name); head.push(`  PERS tooldata ${toolName} := [TRUE,${pose(ev.pose)},[1,[0,0,50],[1,0,0,0],0,0,0]];`); break;
        case 'setSpeed':
          if (ev.speedLinear !== undefined) {
            const v = Math.round(ev.speedLinear);
            speed = `vbs_v${v}`;
            if (!speedDecl.has(speed)) { speedDecl.add(speed); head.push(`  PERS speeddata ${speed} := [${v},${Math.round(ev.speedJoints ?? 500)},5000,1000];`); }
          }
          break;
        case 'setRounding': zone = zoneOf(ev.radius); break;
        case 'pause': body.push(ev.timeMs < 0 ? `    Stop;` : `    WaitTime ${f(ev.timeMs / 1000, 2)};`); break;
        case 'setDO': body.push(`    SetDO ${safeName(ev.io)}, ${ev.value ? 1 : 0};`); break;
        case 'waitDI': body.push(`    WaitDI ${safeName(ev.io)}, ${ev.value ? 1 : 0};`); break;
        case 'runCode': body.push(`    ${ev.code}${ev.isCall ? ';' : ''}`); break;
        case 'comment': body.push(`    ! ${ev.text}`); break;
        case 'message': body.push(`    TPWrite "${ev.text.replace(/"/g, "'")}";`); break;
        case 'callProgram': body.push(`    ${safeName(ev.name)};`); break;
        case 'gripper': body.push(`    SetDO doGripper, ${ev.close ? 1 : 0};`); break;
        case 'navigate': body.push(`    ! NAVIGATE ${f(ev.x)} ${f(ev.y)}`); break;
        case 'task': body.push(`    ! TASK ${ev.task}`); break;
      }
    }
    body.push(`  ENDPROC`);
    for (const s of p.subprograms) {
      const sub = ABB_RAPID.generate(s, options)[0].content;
      // inline sub procedure: extract PROC main body and rename
      const m = sub.match(/PROC main\(\)([\s\S]*?)ENDPROC/);
      if (m) body.push(`  PROC ${safeName(s.name)}()${m[1]}ENDPROC`);
    }
    return [{ name: `${modName}.mod`, content: [...head, ...body, `ENDMODULE`].join('\n') + '\n' }];
  },
};
registerPost(ABB_RAPID);
