import { PostProcessor, PostProgram, PostFile, f, safeName, registerPost } from './base';
import { poseToKuka } from '../core/math/pose';

const frame = (m: Float64Array) => {
  const [x, y, z, a, b, c] = poseToKuka(m);
  return `{X ${f(x)},Y ${f(y)},Z ${f(z)},A ${f(a)},B ${f(b)},C ${f(c)}}`;
};
const e6 = (q: number[]) => `{A1 ${f(q[0] ?? 0)},A2 ${f(q[1] ?? 0)},A3 ${f(q[2] ?? 0)},A4 ${f(q[3] ?? 0)},A5 ${f(q[4] ?? 0)},A6 ${f(q[5] ?? 0)},E1 ${f(q[6] ?? 0)},E2 ${f(q[7] ?? 0)},E3 0,E4 0,E5 0,E6 0}`;

/** KUKA KRC4 (KRL .src/.dat) post processor. */
export const KUKA_KRC4: PostProcessor = {
  id: 'KUKA_KRC4',
  name: 'KUKA KRC4 (KRL)',
  brand: 'KUKA',
  extension: 'src',
  generate(p: PostProgram, options: Record<string, any> = {}): PostFile[] {
    const name = safeName(p.name).toUpperCase();
    const lines: string[] = [];
    let speedL = 0.5; // m/s
    let rounding = -1;
    let toolIdx = options.toolIndex ?? 1;
    let baseIdx = options.baseIndex ?? 1;
    lines.push(`&ACCESS RVP`, `&REL 1`, `&PARAM EDITMASK = *`, `&PARAM TEMPLATE = C:\\KRC\\Roboter\\Template\\vorgabe`, `DEF ${name} ( )`);
    lines.push(`; Generated by VerticalBot Studio for ${p.robotName}`);
    lines.push(`;FOLD INI`, `  BAS (#INITMOV,0 )`, `;ENDFOLD (INI)`);
    lines.push(`$APO.CPTP = 50`, `$APO.CDIS = 5`);
    lines.push(`$VEL.CP = ${f(speedL, 3)}`, `$ACC.CP = 2.0`);
    lines.push(`$TOOL = {FRAME: ${frame(p.tool.pose)}} ; ${p.tool.name}`);
    lines.push(`$BASE = {FRAME: ${frame(p.frame.pose)}} ; ${p.frame.name}`);
    const approx = () => (rounding > 0 ? ' C_DIS' : '');
    for (const ev of p.events) {
      switch (ev.kind) {
        case 'moveJ': lines.push(`PTP ${e6(ev.joints)}${rounding > 0 ? ' C_PTP' : ''} ; ${ev.name}`); break;
        case 'moveL': lines.push(`LIN ${frame(ev.pose)}${approx()} ; ${ev.name}`); break;
        case 'moveC': lines.push(`CIRC ${frame(ev.via)}, ${frame(ev.pose)}${approx()} ; ${ev.name}`); break;
        case 'setFrame': lines.push(`$BASE = {FRAME: ${frame(ev.pose)}} ; ${ev.name}`); baseIdx++; break;
        case 'setTool': lines.push(`$TOOL = {FRAME: ${frame(ev.pose)}} ; ${ev.name}`); toolIdx++; break;
        case 'setSpeed':
          if (ev.speedLinear !== undefined) { speedL = ev.speedLinear / 1000; lines.push(`$VEL.CP = ${f(speedL, 3)}`); }
          if (ev.speedJoints !== undefined) lines.push(`$VEL_AXIS[1] = ${f(Math.min(100, ev.speedJoints / 3.6), 0)}`, `$VEL_AXIS[2] = ${f(Math.min(100, ev.speedJoints / 3.6), 0)}`, `$VEL_AXIS[3] = ${f(Math.min(100, ev.speedJoints / 3.6), 0)}`, `$VEL_AXIS[4] = ${f(Math.min(100, ev.speedJoints / 3.6), 0)}`, `$VEL_AXIS[5] = ${f(Math.min(100, ev.speedJoints / 3.6), 0)}`, `$VEL_AXIS[6] = ${f(Math.min(100, ev.speedJoints / 3.6), 0)}`);
          if (ev.accelLinear !== undefined) lines.push(`$ACC.CP = ${f(ev.accelLinear / 1000, 3)}`);
          break;
        case 'setRounding': rounding = ev.radius; if (ev.radius > 0) lines.push(`$APO.CDIS = ${f(ev.radius, 1)}`, `$APO.CPTP = ${f(Math.min(100, ev.radius), 0)}`); break;
        case 'pause': lines.push(ev.timeMs < 0 ? `HALT` : `WAIT SEC ${f(ev.timeMs / 1000, 3)}`); break;
        case 'setDO': lines.push(`$OUT[${ev.io.replace(/\D/g, '') || ev.io}] = ${ev.value ? 'TRUE' : 'FALSE'}`); break;
        case 'waitDI': lines.push(`WAIT FOR $IN[${ev.io.replace(/\D/g, '') || ev.io}] == ${ev.value ? 'TRUE' : 'FALSE'}`); break;
        case 'runCode': lines.push(ev.isCall ? `${ev.code}()` : ev.code); break;
        case 'comment': lines.push(`; ${ev.text}`); break;
        case 'message': lines.push(`MsgNotify("${ev.text.replace(/"/g, "'")}")`); break;
        case 'callProgram': lines.push(`${safeName(ev.name).toUpperCase()}()`); break;
        case 'gripper': lines.push(`$OUT[1] = ${ev.close ? 'TRUE' : 'FALSE'} ; gripper ${ev.close ? 'close' : 'open'}`); break;
        case 'navigate': lines.push(`; NAVIGATE X ${f(ev.x)} Y ${f(ev.y)}`); break;
        case 'task': lines.push(`; TASK ${ev.task} ${JSON.stringify(ev.params)}`); break;
      }
    }
    lines.push(`END`);
    void toolIdx; void baseIdx;
    const files: PostFile[] = [{ name: `${name}.src`, content: lines.join('\n') + '\n' }];
    files.push({ name: `${name}.dat`, content: `&ACCESS RVP\n&REL 1\nDEFDAT ${name}\nENDDAT\n` });
    for (const s of p.subprograms) files.push(...KUKA_KRC4.generate(s, options));
    return files;
  },
};
registerPost(KUKA_KRC4);
