import { PostProcessor, PostProgram, PostFile, f, safeName, registerPost } from './base';
import { poseToKuka, poseToXyzrpw, poseToZyz, getPos, poseToQuat } from './euler';

/** Yaskawa Motoman INFORM (.JBI) post processor. */
export const MOTOMAN: PostProcessor = {
  id: 'Motoman',
  name: 'Yaskawa Motoman (INFORM JBI)',
  brand: 'Yaskawa',
  extension: 'JBI',
  generate(p: PostProgram): PostFile[] {
    const name = safeName(p.name).toUpperCase().slice(0, 32);
    const pos: string[] = [];
    const ins: string[] = [];
    let c = 0;
    let vl = 500; // mm/s -> V=mm/s*10? INFORM uses 0.1mm/s units
    let vj = 50;
    let pl = 0;
    for (const ev of p.events) {
      switch (ev.kind) {
        case 'moveJ': pos.push(`C${String(c).padStart(5, '0')}=${[0, 1, 2, 3, 4, 5].map((i) => f(ev.joints[i] ?? 0, 4)).join(',')}`); ins.push(`MOVJ C${String(c).padStart(5, '0')} VJ=${f(vj, 2)}${pl ? ` PL=${pl}` : ''}`); c++; break;
        case 'moveL': { const [x, y, z, rz, ry, rx] = poseToKuka(ev.pose); pos.push(`C${String(c).padStart(5, '0')}=${f(x)},${f(y)},${f(z)},${f(rx, 4)},${f(ry, 4)},${f(rz, 4)}`); ins.push(`MOVL C${String(c).padStart(5, '0')} V=${f(vl, 1)}${pl ? ` PL=${pl}` : ''}`); c++; break; }
        case 'moveC': { for (const m of [ev.via, ev.pose]) { const [x, y, z, rz, ry, rx] = poseToKuka(m); pos.push(`C${String(c).padStart(5, '0')}=${f(x)},${f(y)},${f(z)},${f(rx, 4)},${f(ry, 4)},${f(rz, 4)}`); ins.push(`MOVC C${String(c).padStart(5, '0')} V=${f(vl, 1)}`); c++; } break; }
        case 'setSpeed': if (ev.speedLinear !== undefined) vl = ev.speedLinear; if (ev.speedJoints !== undefined) vj = Math.min(100, ev.speedJoints / 2); break;
        case 'setRounding': pl = ev.radius <= 0 ? 0 : Math.min(8, Math.ceil(ev.radius / 10)); break;
        case 'pause': ins.push(ev.timeMs < 0 ? `PAUSE` : `TIMER T=${f(ev.timeMs / 1000, 2)}`); break;
        case 'setDO': ins.push(`DOUT OT#(${ev.io.replace(/\D/g, '') || 1}) ${ev.value ? 'ON' : 'OFF'}`); break;
        case 'waitDI': ins.push(`WAIT IN#(${ev.io.replace(/\D/g, '') || 1})=${ev.value ? 'ON' : 'OFF'}`); break;
        case 'runCode': ins.push(ev.isCall ? `CALL JOB:${safeName(ev.code).toUpperCase()}` : ev.code); break;
        case 'comment': ins.push(`'${ev.text.slice(0, 32)}`); break;
        case 'message': ins.push(`MSG "${ev.text.slice(0, 32)}"`); break;
        case 'callProgram': ins.push(`CALL JOB:${safeName(ev.name).toUpperCase()}`); break;
        case 'gripper': ins.push(`DOUT OT#(1) ${ev.close ? 'ON' : 'OFF'}`); break;
        case 'setFrame': case 'setTool': ins.push(`'${ev.kind} ${ev.name}`); break;
        case 'navigate': ins.push(`'NAV ${f(ev.x, 0)} ${f(ev.y, 0)}`); break;
        case 'task': ins.push(`'TASK ${ev.task}`); break;
      }
    }
    const content = [`/JOB`, `//NAME ${name}`, `//POS`, `///NPOS ${c},0,0,0,0,0`, `///TOOL 0`, `///POSTYPE PULSE`, `///PULSE`, ...pos, `//INST`, `///DATE ${new Date().toISOString().slice(0, 10)}`, `///ATTR SC,RW`, `///GROUP1 RB1`, `NOP`, ...ins, `END`].join('\n') + '\n';
    return [{ name: `${name}.JBI`, content }];
  },
};
registerPost(MOTOMAN);

/** Stäubli VAL3 post processor (.pgx + .dtx simplified). */
export const STAUBLI_VAL3: PostProcessor = {
  id: 'Staubli_VAL3',
  name: 'Stäubli VAL3',
  brand: 'Staubli',
  extension: 'pgx',
  generate(p: PostProgram): PostFile[] {
    const name = safeName(p.name);
    const L: string[] = [`<?xml version="1.0" encoding="utf-8"?>`, `<Programs xmlns="http://www.staubli.com/robotics/VAL3/Program/2">`, `  <Program name="${name}">`, `    <Code><![CDATA[begin`, `  // Generated by VerticalBot Studio for ${p.robotName}`];
    let vel = 'mNomSpeed';
    for (const ev of p.events) {
      const pt = (m: Float64Array) => { const [x, y, z, rx, ry, rz] = poseToXyzrpw(m); return `{${f(x)},${f(y)},${f(z)},${f(rx)},${f(ry)},${f(rz)}}`; };
      switch (ev.kind) {
        case 'moveJ': L.push(`  movej({${[0, 1, 2, 3, 4, 5].map((i) => f(ev.joints[i] ?? 0)).join(',')}}, tTool, ${vel})  // ${ev.name}`); break;
        case 'moveL': L.push(`  movel(appro(pFrame, ${pt(ev.pose)}), tTool, ${vel})  // ${ev.name}`); break;
        case 'moveC': L.push(`  movec(appro(pFrame, ${pt(ev.via)}), appro(pFrame, ${pt(ev.pose)}), tTool, ${vel})`); break;
        case 'setSpeed': if (ev.speedLinear !== undefined) { L.push(`  mNomSpeed.tvel = ${f(ev.speedLinear)}`); } break;
        case 'setRounding': L.push(`  mNomSpeed.blend = ${ev.radius > 0 ? 'joint' : 'off'}`, `  mNomSpeed.leave = ${f(Math.max(0, ev.radius))}`, `  mNomSpeed.reach = ${f(Math.max(0, ev.radius))}`); break;
        case 'pause': L.push(ev.timeMs < 0 ? `  wait(dioContinue)` : `  delay(${f(ev.timeMs / 1000, 3)})`); break;
        case 'setDO': L.push(`  dio${safeName(ev.io)} = ${ev.value ? 'true' : 'false'}`); break;
        case 'waitDI': L.push(`  wait(dio${safeName(ev.io)} == ${ev.value ? 'true' : 'false'})`); break;
        case 'runCode': L.push(`  ${ev.code}${ev.isCall ? '()' : ''}`); break;
        case 'comment': L.push(`  // ${ev.text}`); break;
        case 'message': L.push(`  putln("${ev.text}")`); break;
        case 'callProgram': L.push(`  call ${safeName(ev.name)}()`); break;
        case 'gripper': L.push(`  dioGripper = ${ev.close}`); break;
        case 'setFrame': L.push(`  pFrame.trsf = ${pt(ev.pose)}  // ${ev.name}`); break;
        case 'setTool': L.push(`  tTool.trsf = ${pt(ev.pose)}  // ${ev.name}`); break;
        case 'navigate': L.push(`  // NAV ${f(ev.x)} ${f(ev.y)}`); break;
        case 'task': L.push(`  // TASK ${ev.task}`); break;
      }
    }
    L.push(`end]]></Code>`, `  </Program>`, `</Programs>`);
    return [{ name: `${name}.pgx`, content: L.join('\n') + '\n' }];
  },
};
registerPost(STAUBLI_VAL3);

/** Doosan DRL (Python-like) post processor. */
export const DOOSAN: PostProcessor = {
  id: 'Doosan_Robotics',
  name: 'Doosan Robotics (DRL)',
  brand: 'Doosan',
  extension: 'drl',
  generate(p: PostProgram): PostFile[] {
    const L: string[] = [`# ${p.name} — generated by VerticalBot Studio`, `set_velx(250, 80)`, `set_accx(1000, 300)`, `set_velj(60)`, `set_accj(100)`];
    const px = (m: Float64Array) => { const [x, y, z, a, b, c] = poseToZyz(m); return `posx(${f(x)}, ${f(y)}, ${f(z)}, ${f(a)}, ${f(b)}, ${f(c)})`; };
    let r = 0;
    for (const ev of p.events) {
      switch (ev.kind) {
        case 'moveJ': L.push(`movej(posj(${[0, 1, 2, 3, 4, 5].map((i) => f(ev.joints[i] ?? 0)).join(', ')}), radius=${f(r)})  # ${ev.name}`); break;
        case 'moveL': L.push(`movel(${px(ev.pose)}, radius=${f(r)}, ref=DR_BASE)  # ${ev.name}`); break;
        case 'moveC': L.push(`movec(${px(ev.via)}, ${px(ev.pose)}, radius=${f(r)})`); break;
        case 'setSpeed': if (ev.speedLinear !== undefined) L.push(`set_velx(${f(ev.speedLinear)}, 80)`); if (ev.speedJoints !== undefined) L.push(`set_velj(${f(ev.speedJoints)})`); break;
        case 'setRounding': r = Math.max(0, ev.radius); break;
        case 'pause': L.push(ev.timeMs < 0 ? `wait_manual_guide()` : `wait(${f(ev.timeMs / 1000, 3)})`); break;
        case 'setDO': L.push(`set_digital_output(${ev.io.replace(/\D/g, '') || 1}, ${ev.value ? 'ON' : 'OFF'})`); break;
        case 'waitDI': L.push(`wait_digital_input(${ev.io.replace(/\D/g, '') || 1}, ${ev.value ? 'ON' : 'OFF'})`); break;
        case 'runCode': L.push(`${ev.code}${ev.isCall && !ev.code.includes('(') ? '()' : ''}`); break;
        case 'comment': L.push(`# ${ev.text}`); break;
        case 'message': L.push(`tp_log("${ev.text}")`); break;
        case 'callProgram': L.push(`${safeName(ev.name)}()`); break;
        case 'gripper': L.push(`set_tool_digital_output(1, ${ev.close ? 'ON' : 'OFF'})`); break;
        case 'setFrame': L.push(`# frame ${ev.name}`); break;
        case 'setTool': L.push(`set_tcp("${safeName(ev.name)}")`); break;
        case 'navigate': L.push(`# NAV ${f(ev.x)} ${f(ev.y)}`); break;
        case 'task': L.push(`# TASK ${ev.task}`); break;
      }
    }
    return [{ name: `${safeName(p.name)}.drl`, content: L.join('\n') + '\n' }];
  },
};
registerPost(DOOSAN);

/** Mecademic (Python API-like) */
export const MECADEMIC: PostProcessor = {
  id: 'Mecademic',
  name: 'Mecademic (Python)',
  brand: 'Mecademic',
  extension: 'py',
  generate(p: PostProgram): PostFile[] {
    const L: string[] = [`import mecademicpy.robot as mdr`, `robot = mdr.Robot()`, `robot.Connect(address='192.168.0.100')`, `robot.ActivateAndHome()`, `robot.WaitHomed()`];
    for (const ev of p.events) {
      const px = (m: Float64Array) => { const [x, y, z, rx, ry, rz] = poseToXyzrpw(m); return `${f(x)}, ${f(y)}, ${f(z)}, ${f(rx)}, ${f(ry)}, ${f(rz)}`; };
      switch (ev.kind) {
        case 'moveJ': L.push(`robot.MoveJoints(${[0, 1, 2, 3, 4, 5].map((i) => f(ev.joints[i] ?? 0)).join(', ')})  # ${ev.name}`); break;
        case 'moveL': L.push(`robot.MoveLin(${px(ev.pose)})  # ${ev.name}`); break;
        case 'moveC': L.push(`robot.MoveLin(${px(ev.via)})`, `robot.MoveLin(${px(ev.pose)})`); break;
        case 'setSpeed': if (ev.speedLinear !== undefined) L.push(`robot.SetCartLinVel(${f(ev.speedLinear)})`); if (ev.speedJoints !== undefined) L.push(`robot.SetJointVel(${f(Math.min(100, ev.speedJoints / 1.5))})`); break;
        case 'setRounding': L.push(`robot.SetBlending(${f(Math.min(100, Math.max(0, ev.radius)))})`); break;
        case 'pause': L.push(`robot.Delay(${f(Math.max(0, ev.timeMs) / 1000, 3)})`); break;
        case 'setDO': L.push(`robot.SetOutputState(${ev.io.replace(/\D/g, '') || 0}, ${ev.value ? 1 : 0})`); break;
        case 'waitDI': L.push(`# wait DI ${ev.io}`); break;
        case 'runCode': L.push(ev.code); break;
        case 'comment': L.push(`# ${ev.text}`); break;
        case 'message': L.push(`print("${ev.text}")`); break;
        case 'callProgram': L.push(`${safeName(ev.name)}()`); break;
        case 'gripper': L.push(ev.close ? `robot.GripperClose()` : `robot.GripperOpen()`); break;
        case 'setFrame': L.push(`robot.SetWrf(${px(ev.pose)})  # ${ev.name}`); break;
        case 'setTool': L.push(`robot.SetTrf(${px(ev.pose)})  # ${ev.name}`); break;
        case 'navigate': L.push(`# NAV`); break;
        case 'task': L.push(`# TASK ${ev.task}`); break;
      }
    }
    L.push(`robot.WaitIdle()`, `robot.DeactivateRobot()`, `robot.Disconnect()`);
    return [{ name: `${safeName(p.name)}.py`, content: L.join('\n') + '\n' }];
  },
};
registerPost(MECADEMIC);

/** Generic CSV trace: one line per move with pose (XYZRPW) and joints. */
export const GENERIC_CSV: PostProcessor = {
  id: 'Generic',
  name: 'Generic (CSV / text)',
  brand: 'Generic',
  extension: 'csv',
  generate(p: PostProgram): PostFile[] {
    const L = [`# ${p.name} generated by VerticalBot Studio; poses w.r.t. ${p.frame.name} in mm/deg (X,Y,Z,Rx,Ry,Rz), joints in deg/mm`, `type,name,x,y,z,rx,ry,rz,${p.jointNames.join(',') || 'j1,j2,j3,j4,j5,j6'}`];
    for (const ev of p.events) {
      if (ev.kind === 'moveJ' || ev.kind === 'moveL' || ev.kind === 'moveC') {
        const pose = ev.pose ? poseToXyzrpw(ev.pose).map((v) => f(v)).join(',') : ',,,,,';
        L.push(`${ev.kind},${ev.name},${pose},${(ev.joints ?? []).map((v) => f(v)).join(',')}`);
      } else if (ev.kind === 'comment') L.push(`# ${ev.text}`);
      else L.push(`${ev.kind},${JSON.stringify(ev).replace(/,/g, ';')}`);
    }
    return [{ name: `${safeName(p.name)}.csv`, content: L.join('\n') + '\n' }];
  },
};
registerPost(GENERIC_CSV);

/** JSON dump (full fidelity), used by the ROS 2 bridge and the fleet server. */
export const JSON_POST: PostProcessor = {
  id: 'JSON',
  name: 'JSON (VerticalBot / ROS 2 bridge)',
  brand: 'Generic',
  extension: 'json',
  generate(p: PostProgram): PostFile[] {
    const out = {
      program: p.name,
      robot: p.robotName,
      joint_names: p.jointNames,
      frame: { name: p.frame.name, pose: Array.from(p.frame.pose) },
      tool: { name: p.tool.name, pose: Array.from(p.tool.pose) },
      events: p.events.map((e) => {
        const o: any = { ...e };
        for (const k of ['pose', 'via']) if (o[k] instanceof Float64Array) o[k] = Array.from(o[k]);
        if (o.pose) { const [x, y, z, rx, ry, rz] = poseToXyzrpw(o.pose); o.xyzrpw = [x, y, z, rx, ry, rz]; const [w, qx, qy, qz] = poseToQuat(o.pose); o.quat_wxyz = [w, qx, qy, qz]; o.position_m = getPos(o.pose).map((v: number) => v / 1000); }
        return o;
      }),
      subprograms: p.subprograms.map((s) => JSON.parse(JSON_POST.generate(s)[0].content)),
    };
    return [{ name: `${safeName(p.name)}.json`, content: JSON.stringify(out, null, 2), mime: 'application/json' }];
  },
};
registerPost(JSON_POST);
