import { PostProcessor, PostProgram, PostFile, f, safeName, registerPost } from './base';
import { toRows } from '../core/math/pose';

const mat = (m: Float64Array) => `Mat(${JSON.stringify(toRows(m).map((r) => r.map((v) => +v.toFixed(6))))})`;

/**
 * RoboDK Python API post: the generated script recreates the program inside a running RoboDK
 * instance (robolink), which can then save it as part of an .rdk station. This is the supported
 * bidirectional bridge to RoboDK projects.
 */
export const ROBODK_PYTHON: PostProcessor = {
  id: 'RoboDK_Python',
  name: 'RoboDK API (Python script)',
  brand: 'RoboDK',
  extension: 'py',
  generate(p: PostProgram): PostFile[] {
    const name = safeName(p.name);
    const L: string[] = [
      `# ${p.name} — generated by VerticalBot Studio. Run inside RoboDK (Tools > Run Script) or with robodk installed.`,
      `from robodk.robolink import *`,
      `from robodk.robomath import *`,
      ``,
      `RDK = Robolink()`,
      `robot = RDK.Item(${JSON.stringify(p.robotName)}, ITEM_TYPE_ROBOT)`,
      `if not robot.Valid():`,
      `    robot = RDK.ItemUserPick('Select a robot', ITEM_TYPE_ROBOT)`,
      `frame = RDK.Item(${JSON.stringify(p.frame.name)}, ITEM_TYPE_FRAME)`,
      `if not frame.Valid():`,
      `    frame = RDK.AddFrame(${JSON.stringify(p.frame.name)}, robot.Parent())`,
      `    frame.setPose(${mat(p.frame.pose)})`,
      `tool = RDK.Item(${JSON.stringify(p.tool.name)}, ITEM_TYPE_TOOL)`,
      `if not tool.Valid():`,
      `    tool = robot.AddTool(${mat(p.tool.pose)}, ${JSON.stringify(p.tool.name)})`,
      `robot.setPoseFrame(frame)`,
      `robot.setPoseTool(tool)`,
      `old = RDK.Item(${JSON.stringify(p.name)}, ITEM_TYPE_PROGRAM)`,
      `if old.Valid():`,
      `    old.Delete()`,
      `prog = RDK.AddProgram(${JSON.stringify(p.name)}, robot)`,
      `prog.setPoseFrame(frame)`,
      `prog.setPoseTool(tool)`,
      ``,
    ];
    let n = 0;
    const addTarget = (nm: string, pose: Float64Array | null, joints: number[] | null, joint: boolean) => {
      n++;
      const v = `t${n}`;
      L.push(`${v} = RDK.AddTarget(${JSON.stringify(nm)}, frame, robot)`);
      if (joint && joints) L.push(`${v}.setAsJointTarget()`, `${v}.setJoints(${JSON.stringify(joints.map((x) => +x.toFixed(4)))})`);
      else {
        L.push(`${v}.setAsCartesianTarget()`);
        if (pose) L.push(`${v}.setPose(${mat(pose)})`);
        if (joints) L.push(`${v}.setJoints(${JSON.stringify(joints.map((x) => +x.toFixed(4)))})`);
      }
      return v;
    };
    for (const ev of p.events) {
      switch (ev.kind) {
        case 'moveJ': { const v = addTarget(ev.name, ev.pose, ev.joints, true); L.push(`prog.MoveJ(${v})`); break; }
        case 'moveL': { const v = addTarget(ev.name, ev.pose, ev.joints, false); L.push(`prog.MoveL(${v})`); break; }
        case 'moveC': { const a = addTarget(ev.viaName, ev.via, null, false); const b = addTarget(ev.name, ev.pose, ev.joints, false); L.push(`prog.MoveC(${a}, ${b})`); break; }
        case 'setFrame': L.push(`fr = RDK.Item(${JSON.stringify(ev.name)}, ITEM_TYPE_FRAME)`, `if not fr.Valid():`, `    fr = RDK.AddFrame(${JSON.stringify(ev.name)}, robot.Parent()); fr.setPose(${mat(ev.pose)})`, `prog.setPoseFrame(fr)`, `frame = fr`); break;
        case 'setTool': L.push(`tl = RDK.Item(${JSON.stringify(ev.name)}, ITEM_TYPE_TOOL)`, `if not tl.Valid():`, `    tl = robot.AddTool(${mat(ev.pose)}, ${JSON.stringify(ev.name)})`, `prog.setPoseTool(tl)`); break;
        case 'setSpeed': L.push(`prog.setSpeed(${ev.speedLinear ?? -1}, ${ev.speedJoints ?? -1}, ${ev.accelLinear ?? -1}, ${ev.accelJoints ?? -1})`); break;
        case 'setRounding': L.push(`prog.setRounding(${f(ev.radius, 2)})`); break;
        case 'pause': L.push(`prog.Pause(${ev.timeMs})`); break;
        case 'setDO': L.push(`prog.setDO(${JSON.stringify(ev.io)}, ${JSON.stringify(String(typeof ev.value === 'boolean' ? (ev.value ? 1 : 0) : ev.value))})`); break;
        case 'waitDI': L.push(`prog.waitDI(${JSON.stringify(ev.io)}, ${JSON.stringify(String(typeof ev.value === 'boolean' ? (ev.value ? 1 : 0) : ev.value))}, ${ev.timeoutMs})`); break;
        case 'runCode': L.push(`prog.RunInstruction(${JSON.stringify(ev.code)}, ${ev.isCall ? 'INSTRUCTION_CALL_PROGRAM' : 'INSTRUCTION_INSERT_CODE'})`); break;
        case 'comment': L.push(`prog.RunInstruction(${JSON.stringify(ev.text)}, INSTRUCTION_COMMENT)`); break;
        case 'message': L.push(`prog.RunInstruction(${JSON.stringify(ev.text)}, INSTRUCTION_SHOW_MESSAGE)`); break;
        case 'callProgram': L.push(`prog.RunInstruction(${JSON.stringify(ev.name)}, INSTRUCTION_CALL_PROGRAM)`); break;
        case 'gripper': L.push(`prog.RunInstruction(${JSON.stringify(ev.close ? 'Attach' : 'Detach')}, INSTRUCTION_CALL_PROGRAM)`); break;
        case 'navigate': L.push(`prog.RunInstruction(${JSON.stringify(`NAVIGATE ${f(ev.x)} ${f(ev.y)}`)}, INSTRUCTION_COMMENT)`); break;
        case 'task': L.push(`prog.RunInstruction(${JSON.stringify(`TASK ${ev.task}`)}, INSTRUCTION_COMMENT)`); break;
      }
    }
    L.push(``, `print("Program ${p.name} created in RoboDK")`);
    const files: PostFile[] = [{ name: `${name}_robodk.py`, content: L.join('\n') + '\n' }];
    for (const s of p.subprograms) files.push(...ROBODK_PYTHON.generate(s));
    return files;
  },
};
registerPost(ROBODK_PYTHON);
