import { PostProcessor, PostProgram, PostFile, f, safeName, registerPost } from './base';
import { DEG, poseToQuat, getPos } from '../core/math/pose';

/**
 * ROS 2 post: emits (1) a JointTrajectory-compatible JSON (positions in rad / m) and (2) an rclpy node
 * that publishes it via FollowJointTrajectory or plain topics, matching the topics used in this repository
 * (/cmd_joint_state, /cmd_point, /joint_states, /cmd_vel).
 */
export const ROS2_POST: PostProcessor = {
  id: 'ROS2',
  name: 'ROS 2 (rclpy trajectory node + JSON)',
  brand: 'ROS2',
  extension: 'py',
  generate(p: PostProgram, options: Record<string, any> = {}): PostFile[] {
    const jointNames = p.jointNames.length ? p.jointNames : Array.from({ length: p.dof }, (_, i) => `joint_${i + 1}`);
    const isPrism = p.robot ? p.robot.chain.joints.filter((j) => j.type !== 'fixed' && !j.mimic).map((j) => j.type === 'prismatic') : jointNames.map(() => false);
    const conv = (q: number[]) => q.map((v, i) => (isPrism[i] ? v / 1000 : v * DEG));
    const points: any[] = [];
    const waypoints: any[] = [];
    let t = 0;
    let vj = 60;
    let prev: number[] | null = null;
    for (const ev of p.events) {
      if (ev.kind === 'setSpeed' && ev.speedJoints) vj = ev.speedJoints;
      if ((ev.kind === 'moveJ' || ev.kind === 'moveL' || ev.kind === 'moveC') && ev.joints) {
        const dmax = prev ? Math.max(...ev.joints.map((v, i) => Math.abs(v - prev![i]))) : 0;
        t += Math.max(0.5, dmax / vj);
        prev = ev.joints;
        points.push({ positions: conv(ev.joints).map((v) => +v.toFixed(6)), time_from_start: { sec: Math.floor(t), nanosec: Math.round((t % 1) * 1e9) }, name: ev.name });
        if (ev.pose) {
          const [x, y, z] = getPos(ev.pose);
          const [w, qx, qy, qz] = poseToQuat(ev.pose);
          waypoints.push({ name: ev.name, position: { x: x / 1000, y: y / 1000, z: z / 1000 }, orientation: { x: qx, y: qy, z: qz, w } });
        }
      }
      if (ev.kind === 'navigate') waypoints.push({ name: ev.label ?? 'nav', navigate: { x: ev.x / 1000, y: ev.y / 1000, yaw: (ev.heading ?? 0) * DEG } });
      if (ev.kind === 'setDO') waypoints.push({ set_io: ev.io, value: ev.value });
    }
    const traj = { joint_names: jointNames, points, frame_id: p.frame.name, waypoints };
    const node = `#!/usr/bin/env python3
"""${p.name} — generated by VerticalBot Studio for ROS 2 (rclpy).
Publishes the trajectory as trajectory_msgs/JointTrajectory on ${options.topic ?? '/joint_trajectory'}
and also streams sensor_msgs/JointState on /cmd_joint_state (compatible with vertical_bot_ros controllers).
"""
import json, time, math
import rclpy
from rclpy.node import Node
from trajectory_msgs.msg import JointTrajectory, JointTrajectoryPoint
from sensor_msgs.msg import JointState
from std_msgs.msg import Float32MultiArray
from builtin_interfaces.msg import Duration

TRAJ = json.loads(r'''${JSON.stringify(traj)}''')

class ${safeName(p.name)}Node(Node):
    def __init__(self):
        super().__init__('${safeName(p.name).toLowerCase()}')
        self.pub_traj = self.create_publisher(JointTrajectory, '${options.topic ?? '/joint_trajectory'}', 10)
        self.pub_js = self.create_publisher(JointState, '/cmd_joint_state', 10)
        self.pub_point = self.create_publisher(Float32MultiArray, '/cmd_point', 10)

    def send_trajectory(self):
        msg = JointTrajectory()
        msg.joint_names = TRAJ['joint_names']
        for p in TRAJ['points']:
            pt = JointTrajectoryPoint()
            pt.positions = p['positions']
            pt.time_from_start = Duration(sec=p['time_from_start']['sec'], nanosec=p['time_from_start']['nanosec'])
            msg.points.append(pt)
        self.pub_traj.publish(msg)
        self.get_logger().info('Published trajectory with %d points' % len(msg.points))

    def stream_joint_states(self):
        t_prev = 0.0
        for p in TRAJ['points']:
            t = p['time_from_start']['sec'] + p['time_from_start']['nanosec'] * 1e-9
            time.sleep(max(0.0, t - t_prev)); t_prev = t
            js = JointState(); js.name = TRAJ['joint_names']; js.position = p['positions']
            js.header.stamp = self.get_clock().now().to_msg()
            self.pub_js.publish(js)
            self.get_logger().info('-> %s' % p.get('name', ''))

def main():
    rclpy.init()
    node = ${safeName(p.name)}Node()
    node.send_trajectory()
    node.stream_joint_states()
    node.destroy_node(); rclpy.shutdown()

if __name__ == '__main__':
    main()
`;
    return [
      { name: `${safeName(p.name)}_ros2.py`, content: node },
      { name: `${safeName(p.name)}_trajectory.json`, content: JSON.stringify(traj, null, 2), mime: 'application/json' },
    ];
  },
};
registerPost(ROS2_POST);
export { f };
