import { PostProcessor, PostProgram, PostFile, f, safeName, registerPost } from './base';
import { poseToUr, DEG } from '../core/math/pose';

const p6 = (m: Float64Array) => {
  const [x, y, z, rx, ry, rz] = poseToUr(m);
  return `p[${f(x / 1000, 6)}, ${f(y / 1000, 6)}, ${f(z / 1000, 6)}, ${f(rx, 6)}, ${f(ry, 6)}, ${f(rz, 6)}]`;
};
const jr = (q: number[]) => `[${[0, 1, 2, 3, 4, 5].map((i) => f((q[i] ?? 0) * DEG, 6)).join(', ')}]`;

/** Universal Robots URScript post processor (.script). */
export const UR_SCRIPT: PostProcessor = {
  id: 'Universal_Robots',
  name: 'Universal Robots (URScript)',
  brand: 'UR',
  extension: 'script',
  generate(p: PostProgram, options: Record<string, any> = {}): PostFile[] {
    const name = safeName(p.name);
    const L: string[] = [];
    let v = 0.25, a = 1.2, vj = 1.05, aj = 1.4, blend = 0;
    L.push(`def ${name}():`);
    L.push(`  # Generated by VerticalBot Studio for ${p.robotName}`);
    L.push(`  set_tcp(${p6(p.tool.pose)})  # ${p.tool.name}`);
    L.push(`  frame = ${p6(p.frame.pose)}  # ${p.frame.name}`);
    for (const ev of p.events) {
      switch (ev.kind) {
        case 'moveJ': L.push(`  movej(${jr(ev.joints)}, a=${f(aj, 3)}, v=${f(vj, 3)}, r=${f(blend, 4)})  # ${ev.name}`); break;
        case 'moveL': L.push(`  movel(pose_trans(frame, ${p6(ev.pose)}), a=${f(a, 3)}, v=${f((ev.speed ?? v * 1000) / 1000, 3)}, r=${f(blend, 4)})  # ${ev.name}`); break;
        case 'moveC': L.push(`  movec(pose_trans(frame, ${p6(ev.via)}), pose_trans(frame, ${p6(ev.pose)}), a=${f(a, 3)}, v=${f(v, 3)}, r=${f(blend, 4)})  # ${ev.name}`); break;
        case 'setFrame': L.push(`  frame = ${p6(ev.pose)}  # ${ev.name}`); break;
        case 'setTool': L.push(`  set_tcp(${p6(ev.pose)})  # ${ev.name}`); break;
        case 'setSpeed':
          if (ev.speedLinear !== undefined) v = ev.speedLinear / 1000;
          if (ev.speedJoints !== undefined) vj = ev.speedJoints * DEG;
          if (ev.accelLinear !== undefined) a = ev.accelLinear / 1000;
          if (ev.accelJoints !== undefined) aj = ev.accelJoints * DEG;
          break;
        case 'setRounding': blend = Math.max(0, ev.radius) / 1000; break;
        case 'pause': L.push(ev.timeMs < 0 ? `  popup("Paused: press continue", blocking=True)` : `  sleep(${f(ev.timeMs / 1000, 3)})`); break;
        case 'setDO': L.push(`  set_standard_digital_out(${ev.io.replace(/\D/g, '') || 0}, ${ev.value ? 'True' : 'False'})`); break;
        case 'waitDI': L.push(`  while get_standard_digital_in(${ev.io.replace(/\D/g, '') || 0}) != ${ev.value ? 'True' : 'False'}:`, `    sleep(0.01)`, `  end`); break;
        case 'runCode': L.push(`  ${ev.code}${ev.isCall && !ev.code.includes('(') ? '()' : ''}`); break;
        case 'comment': L.push(`  # ${ev.text}`); break;
        case 'message': L.push(`  textmsg("${ev.text.replace(/"/g, "'")}")`); break;
        case 'callProgram': L.push(`  ${safeName(ev.name)}()`); break;
        case 'gripper': L.push(`  set_tool_digital_out(0, ${ev.close ? 'True' : 'False'})  # gripper ${ev.close ? 'close' : 'open'}`); break;
        case 'navigate': L.push(`  # NAVIGATE ${f(ev.x)} ${f(ev.y)}`); break;
        case 'task': L.push(`  # TASK ${ev.task}`); break;
      }
    }
    L.push(`end`);
    const subs = p.subprograms.map((s) => UR_SCRIPT.generate(s, options)[0].content).join('\n');
    L.push(`${name}()`);
    return [{ name: `${name}.script`, content: (subs ? subs + '\n' : '') + L.join('\n') + '\n' }];
  },
};
registerPost(UR_SCRIPT);
